"use strict";
// ============================================================
// CLImb — desafios-extra.js
// +45 atividades pra engordar as trilhas (chega a 250 no total).
// Usa só comandos JÁ suportados pelo simulador; validadores por estado.
// Empurra em DESAFIOS reusando as trilhas (servico) que já existem.
// ============================================================
(function () {
  if (typeof DESAFIOS === "undefined") return;
  const D = [
    // ==================== S3 (+3) ====================
    { id: "s3-12", servico: "s3", nivel: 2, xp: 70, titulo: "Copie entre buckets",
      descricao: "Copie um objeto de um bucket pra outro (cópia <b>s3 → s3</b>, sem passar pelo seu disco).",
      dicas: ["Crie os dois buckets, suba o arquivo no primeiro e use cp de s3:// pra s3://."],
      solucao: ["aws s3 mb s3://dados-origem", "aws s3 cp relatorio.csv s3://dados-origem/", "aws s3 mb s3://dados-copia", "aws s3 cp s3://dados-origem/relatorio.csv s3://dados-copia/"],
      validar: (c) => { const b = c.s3.buckets["dados-copia"]; return !!b && !!b.objetos["relatorio.csv"]; } },
    { id: "s3-13", servico: "s3", nivel: 2, xp: 70, titulo: "Deploy de um site",
      descricao: "Existe a pasta <b>./site</b> no disco. Crie o bucket <b>site-deploy</b> e <b>sincronize</b> a pasta inteira nele.",
      dicas: ["aws s3 sync ./site s3://site-deploy"],
      solucao: ["aws s3 mb s3://site-deploy", "aws s3 sync ./site s3://site-deploy"],
      validar: (c) => { const b = c.s3.buckets["site-deploy"]; return !!b && !!b.objetos["index.html"]; } },
    { id: "s3-14", servico: "s3", nivel: 3, xp: 70, titulo: "Apague tudo com força",
      descricao: "Crie o <b>temp-bucket</b>, jogue um arquivo nele e remova o bucket <b>com tudo dentro</b> de uma vez.",
      dicas: ["Bucket com objetos só sai com --force: aws s3 rb s3://temp-bucket --force"],
      solucao: ["aws s3 mb s3://temp-bucket", "aws s3 cp relatorio.csv s3://temp-bucket/", "aws s3 rb s3://temp-bucket --force"],
      validar: (c, cmd, ok) => ok && ehCmd(cmd, "s3", "rb") && !c.s3.buckets["temp-bucket"] },

    // ==================== EC2 (+3) ====================
    { id: "ec2-10", servico: "ec2", nivel: 3, xp: 80, titulo: "Libere o HTTPS (443)",
      descricao: "Crie o security group <b>web-https</b> e libere a <b>porta 443</b> pra qualquer IP.",
      dicas: ["authorize-security-group-ingress --protocol tcp --port 443 --cidr 0.0.0.0/0"],
      solucao: ['aws ec2 create-security-group --group-name web-https --description "Servidores HTTPS"', "aws ec2 authorize-security-group-ingress --group-name web-https --protocol tcp --port 443 --cidr 0.0.0.0/0"],
      validar: (c) => Object.values(c.ec2.securityGroups).some((g) => g.nome === "web-https" && g.regras.some((r) => r.porta === 443)) },
    { id: "ec2-11", servico: "ec2", nivel: 2, xp: 80, titulo: "Máquina com chave de acesso",
      descricao: "Crie um par de chaves <b>chave-app</b> e suba uma <b>t3.micro</b> já usando essa chave.",
      dicas: ["Crie a chave primeiro; depois run-instances com --key-name chave-app."],
      solucao: ["aws ec2 create-key-pair --key-name chave-app", "aws ec2 run-instances --image-id ami-0abcd1234ef567890 --instance-type t3.micro --key-name chave-app"],
      validar: (c) => Object.values(c.ec2.instancias).some((i) => i.chave === "chave-app") },
    { id: "ec2-12", servico: "ec2", nivel: 1, xp: 40, titulo: "Liste seus pares de chave",
      descricao: "Veja os <b>pares de chave</b> da conta.",
      dicas: ["aws ec2 describe-key-pairs"], solucao: ["aws ec2 describe-key-pairs"],
      validar: (c, cmd, ok) => ok && ehCmd(cmd, "ec2", "describe-key-pairs") },

    // ==================== VPC (+6) ====================
    { id: "vpc-5", servico: "vpc", nivel: 1, xp: 50, titulo: "Uma segunda rede",
      descricao: "Crie outra VPC, agora com o bloco <b>172.16.0.0/16</b>.",
      dicas: ["aws ec2 create-vpc --cidr-block 172.16.0.0/16"], solucao: ["aws ec2 create-vpc --cidr-block 172.16.0.0/16"],
      validar: (c) => !!(c.vpc && Object.values(c.vpc.vpcs).some((v) => v.cidr === "172.16.0.0/16")) },
    { id: "vpc-6", servico: "vpc", nivel: 1, xp: 40, titulo: "Liste as sub-redes",
      descricao: "Veja as <b>sub-redes</b> da conta.",
      dicas: ["aws ec2 describe-subnets"], solucao: ["aws ec2 describe-subnets"],
      validar: (c, cmd, ok) => ok && ehCmd(cmd, "ec2", "describe-subnets") },
    { id: "vpc-7", servico: "vpc", nivel: 2, xp: 70, titulo: "Sub-rede numa rede nova",
      descricao: "Crie uma VPC <b>10.30.0.0/16</b> e dentro dela uma sub-rede <b>10.30.1.0/24</b>.",
      dicas: ["Crie a VPC, pegue o id e crie a subnet com --vpc-id."],
      solucao: ["aws ec2 create-vpc --cidr-block 10.30.0.0/16", "aws ec2 create-subnet --vpc-id <vpc-id> --cidr-block 10.30.1.0/24"],
      validar: (c) => !!(c.vpc && Object.values(c.vpc.subnets).some((s) => s.cidr === "10.30.1.0/24")) },
    { id: "vpc-8", servico: "vpc", nivel: 1, xp: 40, titulo: "Liste suas VPCs",
      descricao: "Confira as <b>VPCs</b> que você tem.",
      dicas: ["aws ec2 describe-vpcs"], solucao: ["aws ec2 describe-vpcs"],
      validar: (c, cmd, ok) => ok && ehCmd(cmd, "ec2", "describe-vpcs") },
    { id: "vpc-9", servico: "vpc", nivel: 2, xp: 60, titulo: "Crie e descarte uma rede",
      descricao: "Crie uma VPC de teste <b>192.168.0.0/16</b> e <b>apague</b> ela em seguida.",
      dicas: ["Pegue o id no describe-vpcs e use delete-vpc --vpc-id."],
      solucao: ["aws ec2 create-vpc --cidr-block 192.168.0.0/16", "aws ec2 delete-vpc --vpc-id <vpc-id>"],
      validar: (c, cmd, ok) => ok && ehCmd(cmd, "ec2", "delete-vpc") && !!c.vpc && !Object.values(c.vpc.vpcs).some((v) => v.cidr === "192.168.0.0/16") },
    { id: "vpc-10", servico: "vpc", nivel: 3, xp: 100, titulo: "Rede completa de ponta a ponta",
      descricao: "Monte uma rede pronta pra internet: VPC <b>10.20.0.0/16</b>, uma sub-rede, um internet gateway e <b>conecte</b> os dois.",
      dicas: ["São 4 passos: create-vpc, create-subnet, create-internet-gateway, attach-internet-gateway."],
      solucao: ["aws ec2 create-vpc --cidr-block 10.20.0.0/16", "aws ec2 create-subnet --vpc-id <vpc-id> --cidr-block 10.20.1.0/24", "aws ec2 create-internet-gateway", "aws ec2 attach-internet-gateway --internet-gateway-id <igw-id> --vpc-id <vpc-id>"],
      validar: (c) => { const v = c.vpc && Object.values(c.vpc.vpcs).find((x) => x.cidr === "10.20.0.0/16"); return !!(v && v.igw); } },

    // ==================== IAM (+4) ====================
    { id: "iam-8", servico: "iam", nivel: 2, xp: 70, titulo: "Role com trust pronto",
      descricao: "Crie a role <b>papel-ec2</b> usando o documento de confiança pronto <b>trust.json</b>.",
      dicas: ["aws iam create-role --role-name papel-ec2 --assume-role-policy-document file://trust.json"],
      solucao: ["aws iam create-role --role-name papel-ec2 --assume-role-policy-document file://trust.json"],
      validar: (c) => !!c.iam.roles["papel-ec2"] },
    { id: "iam-9", servico: "iam", nivel: 3, xp: 80, titulo: "Política gerenciada própria",
      descricao: "Crie uma <b>política</b> chamada <b>acesso-s3</b> a partir do arquivo <b>politica-publica.json</b>.",
      dicas: ["aws iam create-policy --policy-name acesso-s3 --policy-document file://politica-publica.json"],
      solucao: ["aws iam create-policy --policy-name acesso-s3 --policy-document file://politica-publica.json"],
      validar: (c) => !!c.iam.policies["acesso-s3"] },
    { id: "iam-10", servico: "iam", nivel: 2, xp: 60, titulo: "Suas políticas locais",
      descricao: "Liste só as políticas <b>criadas por você</b> (escopo Local).",
      dicas: ["aws iam list-policies --scope Local"], solucao: ["aws iam list-policies --scope Local"],
      validar: (c, cmd, ok) => ok && ehCmd(cmd, "iam", "list-policies") },
    { id: "iam-11", servico: "iam", nivel: 2, xp: 70, titulo: "Analistas só-leitura",
      descricao: "Crie o grupo <b>analistas</b> e anexe a ele a política <b>AmazonS3ReadOnlyAccess</b>.",
      dicas: ["aws iam attach-group-policy --group-name analistas --policy-arn arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess"],
      solucao: ["aws iam create-group --group-name analistas", "aws iam attach-group-policy --group-name analistas --policy-arn arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess"],
      validar: (c) => { const g = c.iam.grupos["analistas"]; return !!g && (g.politicas || []).length > 0; } },

    // ==================== Lambda (+4) ====================
    { id: "lambda-6", servico: "lambda", nivel: 2, xp: 70, titulo: "Invoque a função",
      descricao: "Crie a função <b>processa</b> e <b>invoque</b> ela (salvando a saída em saida.json).",
      dicas: ["aws lambda invoke --function-name processa saida.json"],
      solucao: ["aws lambda create-function --function-name processa --runtime python3.12 --role arn:aws:iam::123456789012:role/lambda-exec --handler index.handler --zip-file fileb://app.zip", "aws lambda invoke --function-name processa saida.json"],
      validar: (c) => { const f = c.lambda.funcoes["processa"]; return !!f && f.invocada; } },
    { id: "lambda-7", servico: "lambda", nivel: 2, xp: 70, titulo: "Aumente o tempo limite",
      descricao: "Crie a função <b>tarefa</b> e ajuste o <b>timeout</b> dela pra <b>30</b> segundos.",
      dicas: ["aws lambda update-function-configuration --function-name tarefa --timeout 30"],
      solucao: ["aws lambda create-function --function-name tarefa --runtime python3.12 --role arn:aws:iam::123456789012:role/lambda-exec --handler index.handler --zip-file fileb://app.zip", "aws lambda update-function-configuration --function-name tarefa --timeout 30"],
      validar: (c) => { const f = c.lambda.funcoes["tarefa"]; return !!f && f.timeout === 30; } },
    { id: "lambda-8", servico: "lambda", nivel: 3, xp: 80, titulo: "Mais memória",
      descricao: "Crie a função <b>pesada</b> (Node 20) e suba a <b>memória</b> pra <b>512</b> MB.",
      dicas: ["aws lambda update-function-configuration --function-name pesada --memory-size 512"],
      solucao: ["aws lambda create-function --function-name pesada --runtime nodejs20.x --role arn:aws:iam::123456789012:role/lambda-exec --handler index.handler --zip-file fileb://app.zip", "aws lambda update-function-configuration --function-name pesada --memory-size 512"],
      validar: (c) => { const f = c.lambda.funcoes["pesada"]; return !!f && f.memoria === 512; } },
    { id: "lambda-9", servico: "lambda", nivel: 1, xp: 50, titulo: "Detalhe da função",
      descricao: "Crie a função <b>consulta</b> e veja a <b>configuração</b> dela.",
      dicas: ["aws lambda get-function --function-name consulta"],
      solucao: ["aws lambda create-function --function-name consulta --runtime python3.12 --role arn:aws:iam::123456789012:role/lambda-exec --handler index.handler --zip-file fileb://app.zip", "aws lambda get-function --function-name consulta"],
      validar: (c, cmd, ok) => ok && ehCmd(cmd, "lambda", "get-function") },

    // ==================== DynamoDB (+4) ====================
    { id: "dynamodb-6", servico: "dynamodb", nivel: 2, xp: 70, titulo: "Busque um item",
      descricao: "Crie a tabela <b>Clientes</b> (chave <b>cpf</b>), grave um item e <b>busque</b> ele pela chave.",
      dicas: ["aws dynamodb get-item --table-name Clientes --key '{\"cpf\":{\"S\":\"123\"}}'"],
      solucao: ["aws dynamodb create-table --table-name Clientes --attribute-definitions AttributeName=cpf,AttributeType=S --key-schema AttributeName=cpf,KeyType=HASH --billing-mode PAY_PER_REQUEST", "aws dynamodb put-item --table-name Clientes --item '{\"cpf\":{\"S\":\"123\"}}'", "aws dynamodb get-item --table-name Clientes --key '{\"cpf\":{\"S\":\"123\"}}'"],
      validar: (c, cmd, ok) => ok && ehCmd(cmd, "dynamodb", "get-item") },
    { id: "dynamodb-7", servico: "dynamodb", nivel: 2, xp: 60, titulo: "Varra a tabela",
      descricao: "Crie a tabela <b>Pedidos</b>, grave um item e faça um <b>scan</b> pra ver tudo.",
      dicas: ["aws dynamodb scan --table-name Pedidos"],
      solucao: ["aws dynamodb create-table --table-name Pedidos --attribute-definitions AttributeName=id,AttributeType=S --key-schema AttributeName=id,KeyType=HASH --billing-mode PAY_PER_REQUEST", "aws dynamodb put-item --table-name Pedidos --item '{\"id\":{\"S\":\"p1\"}}'", "aws dynamodb scan --table-name Pedidos"],
      validar: (c, cmd, ok) => ok && ehCmd(cmd, "dynamodb", "scan") },
    { id: "dynamodb-8", servico: "dynamodb", nivel: 1, xp: 50, titulo: "Detalhe da tabela",
      descricao: "Crie a tabela <b>Estoque</b> (chave <b>sku</b>) e veja os detalhes dela.",
      dicas: ["aws dynamodb describe-table --table-name Estoque"],
      solucao: ["aws dynamodb create-table --table-name Estoque --attribute-definitions AttributeName=sku,AttributeType=S --key-schema AttributeName=sku,KeyType=HASH --billing-mode PAY_PER_REQUEST", "aws dynamodb describe-table --table-name Estoque"],
      validar: (c, cmd, ok) => ok && ehCmd(cmd, "dynamodb", "describe-table") },
    { id: "dynamodb-9", servico: "dynamodb", nivel: 1, xp: 40, titulo: "Liste as tabelas",
      descricao: "Veja todas as <b>tabelas</b> da conta.",
      dicas: ["aws dynamodb list-tables"], solucao: ["aws dynamodb list-tables"],
      validar: (c, cmd, ok) => ok && ehCmd(cmd, "dynamodb", "list-tables") },

    // ==================== RDS (+6) ====================
    { id: "rds-5", servico: "rds", nivel: 1, xp: 70, titulo: "Banco PostgreSQL",
      descricao: "Suba um banco <b>PostgreSQL</b> chamado <b>banco-pg</b> (db.t3.micro, usuário admin).",
      dicas: ["--engine postgres"],
      solucao: ["aws rds create-db-instance --db-instance-identifier banco-pg --db-instance-class db.t3.micro --engine postgres --master-username admin --allocated-storage 20"],
      validar: (c) => !!(c.rds && c.rds.instancias["banco-pg"] && c.rds.instancias["banco-pg"].engine === "postgres") },
    { id: "rds-6", servico: "rds", nivel: 1, xp: 40, titulo: "Liste os bancos",
      descricao: "Veja as instâncias de banco da conta.",
      dicas: ["aws rds describe-db-instances"], solucao: ["aws rds describe-db-instances"],
      validar: (c, cmd, ok) => ok && ehCmd(cmd, "rds", "describe-db-instances") },
    { id: "rds-7", servico: "rds", nivel: 2, xp: 70, titulo: "Banco maior pra loja",
      descricao: "Crie um <b>MariaDB</b> <b>banco-loja</b> (db.t3.small) com <b>100 GB</b> de armazenamento.",
      dicas: ["--engine mariadb --allocated-storage 100"],
      solucao: ["aws rds create-db-instance --db-instance-identifier banco-loja --db-instance-class db.t3.small --engine mariadb --master-username root --allocated-storage 100"],
      validar: (c) => { const d = c.rds && c.rds.instancias["banco-loja"]; return !!d && d.storage === 100; } },
    { id: "rds-8", servico: "rds", nivel: 2, xp: 60, titulo: "Economize parando o banco",
      descricao: "Crie o <b>banco-stop</b> e <b>pare</b> ele.",
      dicas: ["aws rds stop-db-instance --db-instance-identifier banco-stop"],
      solucao: ["aws rds create-db-instance --db-instance-identifier banco-stop --db-instance-class db.t3.micro --engine mysql --master-username admin --allocated-storage 20", "aws rds stop-db-instance --db-instance-identifier banco-stop"],
      validar: (c) => { const d = c.rds && c.rds.instancias["banco-stop"]; return !!d && d.status === "stopped"; } },
    { id: "rds-9", servico: "rds", nivel: 2, xp: 60, titulo: "Religue o banco",
      descricao: "Crie o <b>banco-start</b>, pare e depois <b>ligue</b> de novo.",
      dicas: ["start-db-instance é o contrário do stop."],
      solucao: ["aws rds create-db-instance --db-instance-identifier banco-start --db-instance-class db.t3.micro --engine mysql --master-username admin --allocated-storage 20", "aws rds stop-db-instance --db-instance-identifier banco-start", "aws rds start-db-instance --db-instance-identifier banco-start"],
      validar: (c) => { const d = c.rds && c.rds.instancias["banco-start"]; return !!d && d.status === "available"; } },
    { id: "rds-10", servico: "rds", nivel: 3, xp: 70, titulo: "Descarte o banco temporário",
      descricao: "Crie o <b>banco-temp</b> e <b>apague</b> ele (pulando o snapshot final).",
      dicas: ["aws rds delete-db-instance --db-instance-identifier banco-temp --skip-final-snapshot"],
      solucao: ["aws rds create-db-instance --db-instance-identifier banco-temp --db-instance-class db.t3.micro --engine mysql --master-username admin --allocated-storage 20", "aws rds delete-db-instance --db-instance-identifier banco-temp --skip-final-snapshot"],
      validar: (c, cmd, ok) => ok && ehCmd(cmd, "rds", "delete-db-instance") && !(c.rds && c.rds.instancias["banco-temp"]) },

    // ==================== CloudWatch (+6) ====================
    { id: "cw-4", servico: "cloudwatch", nivel: 1, xp: 40, titulo: "Métricas disponíveis",
      descricao: "Liste as <b>métricas</b> disponíveis.",
      dicas: ["aws cloudwatch list-metrics"], solucao: ["aws cloudwatch list-metrics"],
      validar: (c, cmd, ok) => ok && ehCmd(cmd, "cloudwatch", "list-metrics") },
    { id: "cw-5", servico: "cloudwatch", nivel: 2, xp: 70, titulo: "Alarme de memória",
      descricao: "Crie um alarme <b>mem-alta</b> na métrica <b>MemoryUtilization</b> com limite <b>90</b>.",
      dicas: ["aws cloudwatch put-metric-alarm --alarm-name mem-alta --metric-name MemoryUtilization --namespace CWAgent --threshold 90 --comparison-operator GreaterThanThreshold"],
      solucao: ["aws cloudwatch put-metric-alarm --alarm-name mem-alta --metric-name MemoryUtilization --namespace CWAgent --threshold 90 --comparison-operator GreaterThanThreshold"],
      validar: (c) => !!(c.cloudwatch && c.cloudwatch.alarmes["mem-alta"]) },
    { id: "cw-6", servico: "cloudwatch", nivel: 2, xp: 60, titulo: "Remova um alarme",
      descricao: "Crie o alarme <b>temp-alarme</b> e <b>apague</b> ele.",
      dicas: ["aws cloudwatch delete-alarms --alarm-names temp-alarme"],
      solucao: ["aws cloudwatch put-metric-alarm --alarm-name temp-alarme --metric-name CPUUtilization --namespace AWS/EC2 --threshold 50 --comparison-operator GreaterThanThreshold", "aws cloudwatch delete-alarms --alarm-names temp-alarme"],
      validar: (c, cmd, ok) => ok && ehCmd(cmd, "cloudwatch", "delete-alarms") && !!c.cloudwatch && !c.cloudwatch.alarmes["temp-alarme"] },
    { id: "cw-7", servico: "cloudwatch", nivel: 1, xp: 50, titulo: "Liste os grupos de logs",
      descricao: "Crie o grupo <b>/app/prod</b> e liste os grupos de logs.",
      dicas: ["aws logs describe-log-groups"],
      solucao: ["aws logs create-log-group --log-group-name /app/prod", "aws logs describe-log-groups"],
      validar: (c, cmd, ok) => ok && ehCmd(cmd, "logs", "describe-log-groups") },
    { id: "cw-8", servico: "cloudwatch", nivel: 1, xp: 50, titulo: "Logs da Lambda",
      descricao: "Crie um grupo de logs <b>/app/lambda</b> (onde a função vai escrever).",
      dicas: ["aws logs create-log-group --log-group-name /app/lambda"],
      solucao: ["aws logs create-log-group --log-group-name /app/lambda"],
      validar: (c) => !!(c.logs && c.logs.grupos["/app/lambda"]) },
    { id: "cw-9", servico: "cloudwatch", nivel: 2, xp: 50, titulo: "Faxina nos logs",
      descricao: "Crie o grupo <b>/app/temp</b> e <b>apague</b> ele.",
      dicas: ["aws logs delete-log-group --log-group-name /app/temp"],
      solucao: ["aws logs create-log-group --log-group-name /app/temp", "aws logs delete-log-group --log-group-name /app/temp"],
      validar: (c, cmd, ok) => ok && ehCmd(cmd, "logs", "delete-log-group") && !!c.logs && !c.logs.grupos["/app/temp"] },

    // ==================== CloudFormation (+3) ====================
    { id: "cfn-7", servico: "cloudformation", nivel: 1, xp: 50, titulo: "Valide o template",
      descricao: "Antes de criar, <b>valide</b> o template <b>site-s3.yaml</b>.",
      dicas: ["aws cloudformation validate-template --template-body file://site-s3.yaml"],
      solucao: ["aws cloudformation validate-template --template-body file://site-s3.yaml"],
      validar: (c, cmd, ok) => ok && ehCmd(cmd, "cloudformation", "validate-template") },
    { id: "cfn-8", servico: "cloudformation", nivel: 2, xp: 70, titulo: "Suba e liste stacks",
      descricao: "Crie um stack <b>site2</b> a partir do <b>site-s3.yaml</b> e <b>liste</b> seus stacks.",
      dicas: ["aws cloudformation create-stack ... ; aws cloudformation list-stacks"],
      solucao: ["aws cloudformation create-stack --stack-name site2 --template-body file://site-s3.yaml", "aws cloudformation list-stacks"],
      validar: (c, cmd, ok) => ok && ehCmd(cmd, "cloudformation", "list-stacks") && !!(c.cloudformation && c.cloudformation.stacks["site2"]) },
    { id: "cfn-9", servico: "cloudformation", nivel: 2, xp: 60, titulo: "Detalhe do stack",
      descricao: "Veja os detalhes do stack <b>site2</b>.",
      dicas: ["aws cloudformation describe-stacks --stack-name site2"],
      solucao: ["aws cloudformation describe-stacks --stack-name site2"],
      validar: (c, cmd, ok) => ok && ehCmd(cmd, "cloudformation", "describe-stacks") },

    // ==================== Mundo real (+6) ====================
    { id: "real-19", servico: "mundo-real", nivel: 3, xp: 110, titulo: "Backend de uma API (IAM + DynamoDB + Lambda)",
      descricao: "Monte o backend: a <b>role api-role</b>, a tabela <b>ApiDados</b> e a função <b>api-handler</b> que vai usar tudo isso.",
      dicas: ["São 3 recursos: create-role, create-table e create-function."],
      solucao: ["aws iam create-role --role-name api-role --assume-role-policy-document file://trust.json", "aws dynamodb create-table --table-name ApiDados --attribute-definitions AttributeName=id,AttributeType=S --key-schema AttributeName=id,KeyType=HASH --billing-mode PAY_PER_REQUEST", "aws lambda create-function --function-name api-handler --runtime python3.12 --role arn:aws:iam::123456789012:role/api-role --handler index.handler --zip-file fileb://app.zip"],
      validar: (c) => !!c.iam.roles["api-role"] && !!c.dynamodb.tabelas["ApiDados"] && !!c.lambda.funcoes["api-handler"] },
    { id: "real-20", servico: "mundo-real", nivel: 3, xp: 120, titulo: "Rede de produção com servidor (VPC + EC2)",
      descricao: "Crie a rede <b>10.50.0.0/16</b> com sub-rede e internet gateway conectado, e suba uma instância nela.",
      dicas: ["create-vpc → create-subnet → create-internet-gateway → attach → run-instances."],
      solucao: ["aws ec2 create-vpc --cidr-block 10.50.0.0/16", "aws ec2 create-subnet --vpc-id <vpc-id> --cidr-block 10.50.1.0/24", "aws ec2 create-internet-gateway", "aws ec2 attach-internet-gateway --internet-gateway-id <igw-id> --vpc-id <vpc-id>", "aws ec2 run-instances --image-id ami-0abcd1234ef567890 --instance-type t2.micro"],
      validar: (c) => { const v = c.vpc && Object.values(c.vpc.vpcs).find((x) => x.cidr === "10.50.0.0/16"); return !!(v && v.igw) && Object.values(c.ec2.instancias).some((i) => i.estado === "running"); } },
    { id: "real-21", servico: "mundo-real", nivel: 3, xp: 110, titulo: "App com banco gerenciado (EC2 SG + RDS)",
      descricao: "Crie o security group <b>app-sg</b> liberando a porta do MySQL (<b>3306</b>) pra rede interna, e suba o banco <b>app-db</b>.",
      dicas: ["authorize ... --port 3306 --cidr 10.0.0.0/16 ; depois create-db-instance."],
      solucao: ['aws ec2 create-security-group --group-name app-sg --description "Banco do app"', "aws ec2 authorize-security-group-ingress --group-name app-sg --protocol tcp --port 3306 --cidr 10.0.0.0/16", "aws rds create-db-instance --db-instance-identifier app-db --db-instance-class db.t3.micro --engine mysql --master-username admin --allocated-storage 20"],
      validar: (c) => Object.values(c.ec2.securityGroups).some((g) => g.nome === "app-sg" && g.regras.some((r) => r.porta === 3306)) && !!(c.rds && c.rds.instancias["app-db"]) },
    { id: "real-22", servico: "mundo-real", nivel: 3, xp: 120, titulo: "Site monitorado (S3 + CloudWatch + Logs)",
      descricao: "Hospede o site <b>site-monitorado</b>, crie um alarme <b>site-erros</b> e um grupo de logs <b>/site/acessos</b>.",
      dicas: ["mb → website → put-metric-alarm → logs create-log-group."],
      solucao: ["aws s3 mb s3://site-monitorado", "aws s3 website s3://site-monitorado --index-document index.html", "aws cloudwatch put-metric-alarm --alarm-name site-erros --metric-name 5xxErrorRate --namespace AWS/S3 --threshold 5 --comparison-operator GreaterThanThreshold", "aws logs create-log-group --log-group-name /site/acessos"],
      validar: (c) => { const b = c.s3.buckets["site-monitorado"]; return !!(b && b.website) && !!(c.cloudwatch && c.cloudwatch.alarmes["site-erros"]) && !!(c.logs && c.logs.grupos["/site/acessos"]); } },
    { id: "real-23", servico: "mundo-real", nivel: 2, xp: 90, titulo: "Onboarding de time (IAM completo)",
      descricao: "Crie o grupo <b>time-dados</b> com acesso ao DynamoDB, crie a usuária <b>renata</b> e coloque ela no grupo.",
      dicas: ["create-group → attach-group-policy → create-user → add-user-to-group."],
      solucao: ["aws iam create-group --group-name time-dados", "aws iam attach-group-policy --group-name time-dados --policy-arn arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess", "aws iam create-user --user-name renata", "aws iam add-user-to-group --user-name renata --group-name time-dados"],
      validar: (c) => { const g = c.iam.grupos["time-dados"]; return !!g && g.membros.includes("renata") && (g.politicas || []).length > 0; } },
    { id: "real-24", servico: "mundo-real", nivel: 3, xp: 110, titulo: "Pipeline de dados (S3 + DynamoDB + Lambda)",
      descricao: "Monte um pipeline: o bucket <b>pipeline-entrada</b>, a tabela <b>PipelineDados</b> e a função <b>pipeline-proc</b> que processa.",
      dicas: ["mb → create-table → create-function."],
      solucao: ["aws s3 mb s3://pipeline-entrada", "aws dynamodb create-table --table-name PipelineDados --attribute-definitions AttributeName=id,AttributeType=S --key-schema AttributeName=id,KeyType=HASH --billing-mode PAY_PER_REQUEST", "aws lambda create-function --function-name pipeline-proc --runtime python3.12 --role arn:aws:iam::123456789012:role/lambda-exec --handler index.handler --zip-file fileb://app.zip"],
      validar: (c) => !!c.s3.buckets["pipeline-entrada"] && !!c.dynamodb.tabelas["PipelineDados"] && !!c.lambda.funcoes["pipeline-proc"] },
  ];
  for (const d of D) DESAFIOS.push(d);
})();
