"use strict";
// ============================================================
// CLImb — fontes oficiais das explicações dos simulados
// FONTES: chave -> { texto, url } (páginas oficiais da AWS, verificadas).
// POR_ID: id da questão -> chave da fonte (fonte EXPLÍCITA por questão).
// O motor (simulados.js) mostra a fonte como link no gabarito comentado.
// ============================================================
(function () {
  if (typeof window === "undefined") return;

  const FONTES = {
    // Conceitos / frameworks
    shared: { texto: "AWS — Modelo de Responsabilidade Compartilhada", url: "https://aws.amazon.com/compliance/shared-responsibility-model/" },
    wellarch: { texto: "AWS Well-Architected Framework (pilares e princípios)", url: "https://aws.amazon.com/architecture/well-architected/" },
    sixadv: { texto: "AWS — Seis vantagens da computação em nuvem (whitepaper)", url: "https://docs.aws.amazon.com/whitepapers/latest/aws-overview/six-advantages-of-cloud-computing.html" },
    caf: { texto: "AWS Cloud Adoption Framework — perspectivas e capacidades", url: "https://docs.aws.amazon.com/whitepapers/latest/overview-aws-cloud-adoption-framework/foundational-capabilities.html" },
    cafphases: { texto: "AWS CAF — fases da transformação (Envision, Align, Launch, Scale)", url: "https://docs.aws.amazon.com/whitepapers/latest/overview-aws-cloud-adoption-framework/transformation-phases.html" },
    migration7r: { texto: "AWS — Estratégias de migração (as 7 Rs)", url: "https://docs.aws.amazon.com/prescriptive-guidance/latest/large-migration-guide/migration-strategies.html" },
    deploymodels: { texto: "AWS — Tipos de computação em nuvem (modelos de implantação)", url: "https://docs.aws.amazon.com/whitepapers/latest/aws-overview/types-of-cloud-computing.html" },
    cloudcomputing: { texto: "AWS — O que é computação em nuvem", url: "https://aws.amazon.com/what-is-cloud-computing/" },
    globalinfra: { texto: "AWS — Infraestrutura Global (Regiões, AZs, Edge)", url: "https://aws.amazon.com/about-aws/global-infrastructure/" },
    localzones: { texto: "AWS Local Zones", url: "https://aws.amazon.com/about-aws/global-infrastructure/localzones/" },
    wavelength: { texto: "AWS Wavelength", url: "https://aws.amazon.com/wavelength/" },
    outposts: { texto: "AWS Outposts", url: "https://aws.amazon.com/outposts/" },
    watool: { texto: "AWS Well-Architected Tool", url: "https://aws.amazon.com/well-architected-tool/" },
    marketplace: { texto: "AWS Marketplace", url: "https://aws.amazon.com/marketplace/" },
    serverless: { texto: "AWS — Serverless (computação sem servidor)", url: "https://aws.amazon.com/serverless/" },

    // IAM / identidade / segurança
    iam: { texto: "AWS Identity and Access Management (IAM)", url: "https://aws.amazon.com/iam/" },
    iambest: { texto: "AWS IAM — Práticas recomendadas de segurança", url: "https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html" },
    iampolicy: { texto: "AWS IAM — Políticas e permissões", url: "https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies.html" },
    iamgroups: { texto: "AWS IAM — Grupos de usuários", url: "https://docs.aws.amazon.com/IAM/latest/UserGuide/id_groups.html" },
    iamroles: { texto: "AWS IAM — Funções (roles)", url: "https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles.html" },
    iamrolescross: { texto: "AWS IAM — Acesso entre contas com funções (roles)", url: "https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_common-scenarios_aws-accounts.html" },
    ec2role: { texto: "AWS IAM — Funções para instâncias EC2", url: "https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2.html" },
    accesskeys: { texto: "AWS IAM — Chaves de acesso (acesso programático)", url: "https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html" },
    credreport: { texto: "AWS IAM — Relatório de credenciais (credential report)", url: "https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_getting-report.html" },
    accessanalyzer: { texto: "AWS IAM Access Analyzer", url: "https://docs.aws.amazon.com/IAM/latest/UserGuide/what-is-access-analyzer.html" },
    mfa: { texto: "AWS IAM — Autenticação multifator (MFA)", url: "https://aws.amazon.com/iam/features/mfa/" },
    sts: { texto: "AWS IAM — Credenciais de segurança temporárias (STS)", url: "https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp.html" },
    iamidc: { texto: "AWS IAM Identity Center (logon único)", url: "https://aws.amazon.com/iam/identity-center/" },
    cognito: { texto: "Amazon Cognito", url: "https://aws.amazon.com/cognito/" },
    directoryservice: { texto: "AWS Directory Service", url: "https://aws.amazon.com/directoryservice/" },
    security: { texto: "AWS Cloud Security (segurança na AWS)", url: "https://aws.amazon.com/security/" },
    compliance: { texto: "AWS — Conformidade (Compliance)", url: "https://aws.amazon.com/compliance/" },
    artifact: { texto: "AWS Artifact (relatórios de conformidade)", url: "https://aws.amazon.com/artifact/" },
    cloudtrail: { texto: "AWS CloudTrail", url: "https://aws.amazon.com/cloudtrail/" },
    config: { texto: "AWS Config", url: "https://aws.amazon.com/config/" },
    waf: { texto: "AWS WAF (Web Application Firewall)", url: "https://aws.amazon.com/waf/" },
    shield: { texto: "AWS Shield (proteção DDoS)", url: "https://aws.amazon.com/shield/" },
    guardduty: { texto: "Amazon GuardDuty", url: "https://aws.amazon.com/guardduty/" },
    inspector: { texto: "Amazon Inspector", url: "https://aws.amazon.com/inspector/" },
    macie: { texto: "Amazon Macie", url: "https://aws.amazon.com/macie/" },
    detective: { texto: "Amazon Detective", url: "https://aws.amazon.com/detective/" },
    securityhub: { texto: "AWS Security Hub", url: "https://aws.amazon.com/security-hub/" },
    kms: { texto: "AWS Key Management Service (KMS)", url: "https://aws.amazon.com/kms/" },
    cloudhsm: { texto: "AWS CloudHSM", url: "https://aws.amazon.com/cloudhsm/" },
    secretsmanager: { texto: "AWS Secrets Manager", url: "https://aws.amazon.com/secrets-manager/" },
    acm: { texto: "AWS Certificate Manager (ACM)", url: "https://aws.amazon.com/certificate-manager/" },
    networkfirewall: { texto: "AWS Network Firewall", url: "https://aws.amazon.com/network-firewall/" },
    organizations: { texto: "AWS Organizations", url: "https://aws.amazon.com/organizations/" },
    scp: { texto: "AWS Organizations — Service Control Policies (SCPs)", url: "https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_scps.html" },
    controltower: { texto: "AWS Control Tower", url: "https://aws.amazon.com/controltower/" },

    // Computação
    ec2: { texto: "Amazon EC2", url: "https://aws.amazon.com/ec2/" },
    ec2pricing: { texto: "Amazon EC2 — Preços", url: "https://aws.amazon.com/ec2/pricing/" },
    ec2types: { texto: "Amazon EC2 — Tipos de instância", url: "https://aws.amazon.com/ec2/instance-types/" },
    ami: { texto: "Amazon EC2 — Amazon Machine Images (AMI)", url: "https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AMIs.html" },
    elasticip: { texto: "Amazon EC2 — Elastic IP", url: "https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/elastic-ip-addresses-eip.html" },
    autoscaling: { texto: "Amazon EC2 Auto Scaling", url: "https://aws.amazon.com/ec2/autoscaling/" },
    spot: { texto: "Amazon EC2 — Spot Instances", url: "https://aws.amazon.com/ec2/spot/" },
    dedicatedhosts: { texto: "Amazon EC2 — Dedicated Hosts", url: "https://aws.amazon.com/ec2/dedicated-hosts/" },
    imagebuilder: { texto: "EC2 Image Builder", url: "https://aws.amazon.com/image-builder/" },
    lambda: { texto: "AWS Lambda", url: "https://aws.amazon.com/lambda/" },
    beanstalk: { texto: "AWS Elastic Beanstalk", url: "https://aws.amazon.com/elasticbeanstalk/" },
    lightsail: { texto: "Amazon Lightsail", url: "https://aws.amazon.com/lightsail/" },
    ecs: { texto: "Amazon Elastic Container Service (ECS)", url: "https://aws.amazon.com/ecs/" },
    eks: { texto: "Amazon Elastic Kubernetes Service (EKS)", url: "https://aws.amazon.com/eks/" },
    fargate: { texto: "AWS Fargate", url: "https://aws.amazon.com/fargate/" },
    apprunner: { texto: "AWS App Runner", url: "https://aws.amazon.com/apprunner/" },
    batch: { texto: "AWS Batch", url: "https://aws.amazon.com/batch/" },

    // Armazenamento
    s3: { texto: "Amazon S3", url: "https://aws.amazon.com/s3/" },
    s3classes: { texto: "Amazon S3 — Classes de armazenamento", url: "https://aws.amazon.com/s3/storage-classes/" },
    s3versioning: { texto: "Amazon S3 — Versionamento", url: "https://docs.aws.amazon.com/AmazonS3/latest/userguide/Versioning.html" },
    s3lifecycle: { texto: "Amazon S3 — Regras de ciclo de vida", url: "https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lifecycle-mgmt.html" },
    s3encryption: { texto: "Amazon S3 — Criptografia (proteção de dados)", url: "https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingEncryption.html" },
    s3block: { texto: "Amazon S3 — Block Public Access", url: "https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-control-block-public-access.html" },
    s3web: { texto: "Amazon S3 — Hospedagem de site estático", url: "https://docs.aws.amazon.com/AmazonS3/latest/userguide/WebsiteHosting.html" },
    ebs: { texto: "Amazon Elastic Block Store (EBS)", url: "https://aws.amazon.com/ebs/" },
    ebssnapshot: { texto: "Amazon EBS — Snapshots", url: "https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSSnapshots.html" },
    efs: { texto: "Amazon Elastic File System (EFS)", url: "https://aws.amazon.com/efs/" },
    snow: { texto: "AWS Snow Family", url: "https://aws.amazon.com/snow/" },
    backup: { texto: "AWS Backup", url: "https://aws.amazon.com/backup/" },

    // Bancos de dados
    rds: { texto: "Amazon RDS", url: "https://aws.amazon.com/rds/" },
    rdsmultiaz: { texto: "Amazon RDS — Implantações Multi-AZ", url: "https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.MultiAZ.html" },
    rdsreplica: { texto: "Amazon RDS — Réplicas de leitura", url: "https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_ReadRepl.html" },
    rdsencryption: { texto: "Amazon RDS — Criptografia em repouso", url: "https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Overview.Encryption.html" },
    aurora: { texto: "Amazon Aurora", url: "https://aws.amazon.com/rds/aurora/" },
    dynamodb: { texto: "Amazon DynamoDB", url: "https://aws.amazon.com/dynamodb/" },
    redshift: { texto: "Amazon Redshift", url: "https://aws.amazon.com/redshift/" },
    elasticache: { texto: "Amazon ElastiCache", url: "https://aws.amazon.com/elasticache/" },
    neptune: { texto: "Amazon Neptune", url: "https://aws.amazon.com/neptune/" },
    dms: { texto: "AWS Database Migration Service (DMS)", url: "https://aws.amazon.com/dms/" },

    // Rede
    vpc: { texto: "Amazon VPC", url: "https://aws.amazon.com/vpc/" },
    vpcflowlogs: { texto: "Amazon VPC — Flow Logs", url: "https://docs.aws.amazon.com/vpc/latest/userguide/flow-logs.html" },
    igw: { texto: "Amazon VPC — Internet Gateway", url: "https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Internet_Gateway.html" },
    natgw: { texto: "Amazon VPC — NAT Gateway", url: "https://docs.aws.amazon.com/vpc/latest/userguide/vpc-nat-gateway.html" },
    sg: { texto: "Amazon VPC — Security Groups", url: "https://docs.aws.amazon.com/vpc/latest/userguide/vpc-security-groups.html" },
    nacl: { texto: "Amazon VPC — Network ACLs", url: "https://docs.aws.amazon.com/vpc/latest/userguide/vpc-network-acls.html" },
    sgnacl: { texto: "Amazon VPC — Security Groups e Network ACLs", url: "https://docs.aws.amazon.com/vpc/latest/userguide/vpc-security-groups.html" },
    routetable: { texto: "Amazon VPC — Tabelas de rotas", url: "https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Route_Tables.html" },
    vpcpeering: { texto: "Amazon VPC — Peering", url: "https://docs.aws.amazon.com/vpc/latest/peering/what-is-vpc-peering.html" },
    privatelink: { texto: "AWS PrivateLink (VPC Endpoints)", url: "https://aws.amazon.com/privatelink/" },
    transitgw: { texto: "AWS Transit Gateway", url: "https://aws.amazon.com/transit-gateway/" },
    directconnect: { texto: "AWS Direct Connect", url: "https://aws.amazon.com/directconnect/" },
    vpn: { texto: "AWS VPN (Site-to-Site)", url: "https://aws.amazon.com/vpn/" },
    elb: { texto: "Elastic Load Balancing (ELB)", url: "https://aws.amazon.com/elasticloadbalancing/" },
    globalaccel: { texto: "AWS Global Accelerator", url: "https://aws.amazon.com/global-accelerator/" },
    cloudfront: { texto: "Amazon CloudFront (CDN)", url: "https://aws.amazon.com/cloudfront/" },
    route53: { texto: "Amazon Route 53 (DNS)", url: "https://aws.amazon.com/route53/" },

    // Integração / mensageria / streaming / análise
    sqs: { texto: "Amazon SQS", url: "https://aws.amazon.com/sqs/" },
    sns: { texto: "Amazon SNS", url: "https://aws.amazon.com/sns/" },
    apigateway: { texto: "Amazon API Gateway", url: "https://aws.amazon.com/api-gateway/" },
    stepfunctions: { texto: "AWS Step Functions", url: "https://aws.amazon.com/step-functions/" },
    ses: { texto: "Amazon SES (Simple Email Service)", url: "https://aws.amazon.com/ses/" },
    kinesis: { texto: "Amazon Kinesis", url: "https://aws.amazon.com/kinesis/" },
    emr: { texto: "Amazon EMR", url: "https://aws.amazon.com/emr/" },
    glue: { texto: "AWS Glue", url: "https://aws.amazon.com/glue/" },
    athena: { texto: "Amazon Athena", url: "https://aws.amazon.com/athena/" },
    quicksight: { texto: "Amazon QuickSight", url: "https://aws.amazon.com/quicksight/" },
    lakeformation: { texto: "AWS Lake Formation", url: "https://aws.amazon.com/lake-formation/" },
    iotcore: { texto: "AWS IoT Core", url: "https://aws.amazon.com/iot-core/" },

    // IA / ML
    sagemaker: { texto: "Amazon SageMaker", url: "https://aws.amazon.com/sagemaker/" },
    polly: { texto: "Amazon Polly", url: "https://aws.amazon.com/polly/" },
    rekognition: { texto: "Amazon Rekognition", url: "https://aws.amazon.com/rekognition/" },
    lex: { texto: "Amazon Lex", url: "https://aws.amazon.com/lex/" },
    comprehend: { texto: "Amazon Comprehend", url: "https://aws.amazon.com/comprehend/" },
    textract: { texto: "Amazon Textract", url: "https://aws.amazon.com/textract/" },
    bedrock: { texto: "Amazon Bedrock (IA generativa)", url: "https://aws.amazon.com/bedrock/" },

    // Gerenciamento / operações
    cloudwatch: { texto: "Amazon CloudWatch", url: "https://aws.amazon.com/cloudwatch/" },
    cloudformation: { texto: "AWS CloudFormation (infraestrutura como código)", url: "https://aws.amazon.com/cloudformation/" },
    systemsmanager: { texto: "AWS Systems Manager", url: "https://aws.amazon.com/systems-manager/" },
    computeoptimizer: { texto: "AWS Compute Optimizer", url: "https://aws.amazon.com/compute-optimizer/" },
    trustedadvisor: { texto: "AWS Trusted Advisor", url: "https://aws.amazon.com/premiumsupport/technology/trusted-advisor/" },
    health: { texto: "AWS Health Dashboard", url: "https://aws.amazon.com/premiumsupport/technology/aws-health-dashboard/" },
    servicecatalog: { texto: "AWS Service Catalog", url: "https://aws.amazon.com/servicecatalog/" },
    migrationhub: { texto: "AWS Migration Hub", url: "https://aws.amazon.com/migration-hub/" },
    codepipeline: { texto: "AWS CodePipeline (CI/CD)", url: "https://aws.amazon.com/codepipeline/" },
    console: { texto: "AWS Management Console", url: "https://aws.amazon.com/console/" },
    cli: { texto: "AWS Command Line Interface (CLI)", url: "https://aws.amazon.com/cli/" },

    // Cobrança / preços / suporte
    support: { texto: "AWS — Planos de Suporte", url: "https://aws.amazon.com/premiumsupport/plans/" },
    pricinghow: { texto: "AWS — Preços (como a AWS cobra)", url: "https://aws.amazon.com/pricing/" },
    pricingcalc: { texto: "AWS Pricing Calculator", url: "https://calculator.aws/" },
    freetier: { texto: "AWS Free Tier (nível gratuito)", url: "https://aws.amazon.com/free/" },
    budgets: { texto: "AWS Budgets", url: "https://aws.amazon.com/aws-cost-management/aws-budgets/" },
    costexplorer: { texto: "AWS Cost Explorer", url: "https://aws.amazon.com/aws-cost-management/aws-cost-explorer/" },
    cur: { texto: "AWS Cost and Usage Report (CUR)", url: "https://aws.amazon.com/aws-cost-management/aws-cost-and-usage-reporting/" },
    costmgmt: { texto: "AWS Billing and Cost Management", url: "https://aws.amazon.com/aws-cost-management/" },
    consolidatedbilling: { texto: "AWS — Cobrança consolidada (Organizations)", url: "https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/consolidated-billing.html" },
    costtags: { texto: "AWS — Tags de alocação de custos", url: "https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/cost-alloc-tags.html" },
    savingsplans: { texto: "AWS Savings Plans", url: "https://aws.amazon.com/savingsplans/" },
  };

  // Fonte EXPLÍCITA por questão (id -> chave). Verificado nas páginas oficiais.
  const POR_ID = {
    // ---- parte 1 (prova real) ----
    "clf-p01": "shared", "clf-p02": "cloudtrail", "clf-p03": "waf", "clf-p04": "imagebuilder",
    "clf-p05": "pricingcalc", "clf-p06": "sixadv", "clf-p07": "iambest", "clf-p08": "vpcflowlogs",
    "clf-p09": "inspector", "clf-p10": "sixadv", "clf-p11": "wellarch", "clf-p12": "igw",
    "clf-p13": "aurora", "clf-p14": "sgnacl", "clf-p15": "savingsplans", "clf-p16": "wellarch",
    "clf-p17": "budgets", "clf-p18": "caf", "clf-p19": "config", "clf-p20": "dynamodb",
    "clf-p21": "wellarch", "clf-p22": "iam", "clf-p23": "beanstalk", "clf-p24": "kms",
    "clf-p25": "wellarch", "clf-p26": "s3versioning", "clf-p27": "cloudtrail", "clf-p28": "iambest",
    "clf-p29": "sixadv", "clf-p30": "shared", "clf-p31": "credreport", "clf-p32": "rds",
    "clf-p33": "iamrolescross", "clf-p34": "cafphases", "clf-p35": "spot", "clf-p36": "accesskeys",
    "clf-p37": "shared", "clf-p38": "caf", "clf-p39": "shared", "clf-p40": "ec2role",
    "clf-p41": "console", "clf-p42": "trustedadvisor", "clf-p43": "budgets",

    // ---- parte 2: conceitos ----
    "clf-c01": "sixadv", "clf-c02": "sixadv", "clf-c03": "sixadv", "clf-c04": "globalinfra",
    "clf-c05": "globalinfra", "clf-c06": "globalinfra", "clf-c07": "globalinfra", "clf-c08": "wellarch",
    "clf-c09": "wellarch", "clf-c10": "wellarch", "clf-c11": "wellarch", "clf-c12": "wellarch",
    "clf-c13": "caf", "clf-c14": "caf", "clf-c15": "deploymodels", "clf-c16": "cloudcomputing",
    "clf-c17": "cloudcomputing", "clf-c18": "wellarch", "clf-c19": "migration7r", "clf-c20": "migration7r",
    "clf-c21": "sixadv", "clf-c22": "sixadv", "clf-c23": "outposts", "clf-c24": "wellarch",
    "clf-c25": "wellarch", "clf-c26": "wellarch", "clf-c27": "wellarch", "clf-c28": "globalinfra",
    "clf-c29": "pricingcalc", "clf-c30": "caf", "clf-c31": "s3", "clf-c32": "wellarch",
    "clf-c33": "localzones", "clf-c34": "cloudcomputing", "clf-c35": "wellarch", "clf-c36": "wellarch",
    "clf-c37": "caf", "clf-c38": "sixadv", "clf-c39": "migration7r", "clf-c40": "marketplace",
    "clf-c41": "cloudcomputing", "clf-c42": "deploymodels", "clf-c43": "cloudformation", "clf-c44": "globalinfra",
    "clf-c45": "globalinfra", "clf-c46": "caf", "clf-c47": "serverless", "clf-c48": "autoscaling",
    "clf-c49": "wellarch", "clf-c50": "sixadv", "clf-c51": "caf", "clf-c52": "watool",
    "clf-c53": "sixadv", "clf-c54": "cloudcomputing", "clf-c55": "migration7r", "clf-c56": "wellarch",
    "clf-c57": "pricinghow", "clf-c58": "wavelength", "clf-c59": "elb", "clf-c60": "wellarch",

    // ---- parte 2: cobrança ----
    "clf-b01": "spot", "clf-b02": "savingsplans", "clf-b03": "savingsplans", "clf-b04": "costexplorer",
    "clf-b05": "support", "clf-b06": "support", "clf-b07": "consolidatedbilling", "clf-b08": "freetier",
    "clf-b09": "budgets", "clf-b10": "cur", "clf-b11": "pricinghow", "clf-b12": "support",
    "clf-b13": "support", "clf-b14": "costtags", "clf-b15": "trustedadvisor", "clf-b16": "ec2pricing",
    "clf-b17": "dedicatedhosts", "clf-b18": "pricinghow", "clf-b19": "consolidatedbilling", "clf-b20": "artifact",
    "clf-b21": "support", "clf-b22": "pricingcalc", "clf-b23": "savingsplans", "clf-b24": "costmgmt",
    "clf-b25": "spot", "clf-b26": "trustedadvisor", "clf-b27": "support", "clf-b28": "iam",
    "clf-b29": "budgets", "clf-b30": "support",

    // ---- parte 3: segurança ----
    "clf-s01": "shared", "clf-s02": "shared", "clf-s03": "shared", "clf-s04": "iambest",
    "clf-s05": "iampolicy", "clf-s06": "iamgroups", "clf-s07": "iamroles", "clf-s08": "shield",
    "clf-s09": "macie", "clf-s10": "guardduty", "clf-s11": "detective", "clf-s12": "acm",
    "clf-s13": "secretsmanager", "clf-s14": "kms", "clf-s15": "waf", "clf-s16": "artifact",
    "clf-s17": "mfa", "clf-s18": "organizations", "clf-s19": "scp", "clf-s20": "controltower",
    "clf-s21": "sgnacl", "clf-s22": "config", "clf-s23": "cloudtrail", "clf-s24": "s3encryption",
    "clf-s25": "iambest", "clf-s26": "credreport", "clf-s27": "accessanalyzer", "clf-s28": "accesskeys",
    "clf-s29": "securityhub", "clf-s30": "shared", "clf-s31": "vpc", "clf-s32": "waf",
    "clf-s33": "iampolicy", "clf-s34": "s3block", "clf-s35": "iamidc", "clf-s36": "inspector",
    "clf-s37": "shared", "clf-s38": "iambest", "clf-s39": "cloudtrail", "clf-s40": "security",
    "clf-s41": "shared", "clf-s42": "cloudhsm", "clf-s43": "ec2role", "clf-s44": "cloudfront",
    "clf-s45": "scp", "clf-s46": "iambest", "clf-s47": "waf", "clf-s48": "security",
    "clf-s49": "config", "clf-s50": "cloudtrail", "clf-s51": "shared", "clf-s52": "iamidc",
    "clf-s53": "iambest", "clf-s54": "macie", "clf-s55": "compliance", "clf-s56": "sts",
    "clf-s57": "scp", "clf-s58": "networkfirewall", "clf-s59": "iam", "clf-s60": "vpc",

    // ---- parte 4: tecnologia ----
    "clf-t01": "ec2", "clf-t02": "lambda", "clf-t03": "beanstalk", "clf-t04": "lightsail",
    "clf-t05": "ecs", "clf-t06": "fargate", "clf-t07": "eks", "clf-t08": "autoscaling",
    "clf-t09": "s3", "clf-t10": "ebs", "clf-t11": "s3classes", "clf-t12": "s3classes",
    "clf-t13": "efs", "clf-t14": "snow", "clf-t15": "s3lifecycle", "clf-t16": "backup",
    "clf-t17": "rds", "clf-t18": "dynamodb", "clf-t19": "redshift", "clf-t20": "elasticache",
    "clf-t21": "aurora", "clf-t22": "neptune", "clf-t23": "rdsmultiaz", "clf-t24": "rdsreplica",
    "clf-t25": "athena", "clf-t26": "cloudfront", "clf-t27": "route53", "clf-t28": "directconnect",
    "clf-t29": "vpn", "clf-t30": "elb", "clf-t31": "natgw", "clf-t32": "privatelink",
    "clf-t33": "transitgw", "clf-t34": "sqs", "clf-t35": "sns", "clf-t36": "apigateway",
    "clf-t37": "stepfunctions", "clf-t38": "emr", "clf-t39": "quicksight", "clf-t40": "glue",
    "clf-t41": "kinesis", "clf-t42": "cloudwatch", "clf-t43": "cloudformation", "clf-t44": "systemsmanager",
    "clf-t45": "health", "clf-t46": "computeoptimizer", "clf-t47": "codepipeline", "clf-t48": "beanstalk",
    "clf-t49": "console", "clf-t50": "cli", "clf-t51": "ami", "clf-t52": "ebssnapshot",
    "clf-t53": "s3web", "clf-t54": "ec2types", "clf-t55": "dynamodb", "clf-t56": "dms",
    "clf-t57": "migrationhub", "clf-t58": "servicecatalog", "clf-t59": "sagemaker", "clf-t60": "polly",
    "clf-t61": "rekognition", "clf-t62": "lex", "clf-t63": "bedrock", "clf-t64": "textract",
    "clf-t65": "comprehend", "clf-t66": "elasticip", "clf-t67": "s3", "clf-t68": "ses",
    "clf-t69": "batch", "clf-t70": "s3classes", "clf-t71": "sg", "clf-t72": "routetable",
    "clf-t73": "directoryservice", "clf-t74": "cognito", "clf-t75": "s3classes", "clf-t76": "route53",
    "clf-t77": "globalaccel", "clf-t78": "lakeformation", "clf-t79": "apprunner", "clf-t80": "vpcpeering",
    "clf-t81": "redshift", "clf-t82": "lambda", "clf-t83": "cloudfront", "clf-t84": "iotcore",
    "clf-t85": "cloudfront",

    // ---- parte 5: complemento ----
    "clf-x01": "sixadv", "clf-x02": "autoscaling", "clf-x03": "deploymodels", "clf-x04": "caf",
    "clf-x05": "globalinfra", "clf-x06": "sixadv", "clf-x07": "globalinfra", "clf-x08": "iamgroups",
    "clf-x09": "cloudtrail", "clf-x10": "s3versioning", "clf-x11": "rdsencryption", "clf-x12": "iamroles",
    "clf-x13": "config", "clf-x14": "shared", "clf-x15": "accessanalyzer", "clf-x16": "mfa",
    "clf-x17": "sqs", "clf-x18": "ec2", "clf-x19": "elasticache", "clf-x20": "lambda",
    "clf-x21": "cloudformation", "clf-x22": "cloudwatch", "clf-x23": "athena", "clf-x24": "efs",
    "clf-x25": "cloudfront", "clf-x26": "dynamodb", "clf-x27": "savingsplans", "clf-x28": "costexplorer",
    "clf-x29": "support", "clf-x30": "freetier",
  };

  // Fallback por domínio, caso algum id não esteja mapeado.
  const FALLBACK = { conceitos: "cloudcomputing", seguranca: "security", tecnologia: "console", cobranca: "pricinghow" };

  window.SIMULADOS_FONTES = FONTES;
  window.SIMULADOS_FONTE_POR_ID = POR_ID;
  window.SIMULADOS_FONTE_FALLBACK = FALLBACK;
})();
