"use strict";
// ============================================================
// CLImb — banco de questões CLF-C02 (parte 1)
// Origem: prova real que o usuário fez (gabarito conferido). Onde o gabarito da
// prova divergia da documentação da AWS, usamos a resposta CORRETA da doc e
// marcamos com `corrigido:true` (ver notas no fim do arquivo).
// Domínios: conceitos | seguranca | tecnologia | cobranca
// ============================================================
(function () {
  if (typeof window === "undefined") return;
  const B = (window.SIMULADOS_CLF = window.SIMULADOS_CLF || []);
  const Q = [
    { id: "clf-p01", d: "seguranca", q: "Uma empresa está usando o Amazon DynamoDB. Qual tarefa é de responsabilidade da empresa, segundo o modelo de responsabilidade compartilhada da AWS?",
      o: ["Corrigir o sistema operacional.", "Gerenciar permissões de acesso ao banco de dados.", "Provisionar hosts.", "Proteger o sistema operacional."], c: [1],
      e: "O DynamoDB é um serviço gerenciado: a AWS cuida do SO, hosts e patches. O cliente cuida do que está 'na' nuvem — incluindo controlar quem acessa as tabelas (IAM)." },
    { id: "clf-p02", d: "seguranca", q: "Qual serviço permite que os clientes auditem chamadas de API em suas contas da AWS?",
      o: ["AWS CloudTrail", "AWS Trusted Advisor", "Amazon Inspector", "AWS X-Ray"], c: [0],
      e: "O CloudTrail registra todas as chamadas de API da conta (quem fez, quando, de onde) — é a ferramenta de auditoria. Inspector busca vulnerabilidades; X-Ray faz tracing de aplicações." },
    { id: "clf-p03", d: "seguranca", q: "Uma empresa precisa bloquear ataques de injeção de SQL. Qual serviço ou recurso da AWS pode atender a esse requisito?",
      o: ["AWS Shield", "AWS WAF", "Network ACLs (ACLs de Rede)", "Security Groups (Grupos de Segurança)"], c: [1],
      e: "O AWS WAF filtra tráfego HTTP/HTTPS na camada de aplicação, bloqueando SQL injection e XSS. Shield protege contra DDoS; NACLs e Security Groups filtram por IP/porta, não inspecionam o conteúdo." },
    { id: "clf-p04", d: "tecnologia", q: "Qual serviço AWS totalmente gerenciado auxilia na criação, teste e gerenciamento de imagens personalizadas do Amazon EC2?",
      o: ["AWS Launch Wizard", "Amazon Machine Image (AMI)", "EC2 Image Builder", "AWS Elastic Beanstalk"], c: [2],
      e: "O EC2 Image Builder automatiza criar, testar e manter AMIs personalizadas. A AMI é o resultado (a imagem), não a ferramenta de gerência." },
    { id: "clf-p05", d: "cobranca", q: "Uma empresa precisa criar uma estimativa de custo para um projeto antes que a infraestrutura seja provisionada. Qual serviço ou recurso da AWS pode ser usado para estimar custos antes da implantação?",
      o: ["AWS Billing and Cost Management", "AWS Cost and Usage Report", "Nível gratuito da AWS", "AWS Pricing Calculator"], c: [3],
      e: "O Pricing Calculator estima custos ANTES de provisionar. As outras opções tratam de custos que JÁ aconteceram (faturamento e relatórios)." },
    { id: "clf-p06", d: "conceitos", q: "Qual opção é um benefício das economias de escala baseadas nas vantagens da computação em nuvem?",
      o: ["Redução dos custos variáveis em relação aos custos fixos", "A capacidade de trocar despesas variáveis por despesas fixas", "Maior velocidade e agilidade", "Aumento dos custos operacionais em data centers"], c: [0],
      e: "Com milhões de clientes, a AWS dilui custos e repassa preços menores ('benefit from massive economies of scale'). Agilidade é outro benefício, mas não é o de economia de escala." },
    { id: "clf-p07", d: "seguranca", q: "Qual recomendação está em conformidade com as práticas recomendadas de segurança do IAM?",
      o: ["Conceder permissões amplas para que todos os funcionários acessem os recursos de que necessitam.", "Ativar a autenticação multifator (MFA) para aumentar a segurança no login.", "Usar as chaves de acesso do usuário root para tarefas administrativas.", "Evitar alternar credenciais para evitar problemas em produção."], c: [1],
      e: "Ativar MFA é prática recomendada. O contrário das outras é o certo: privilégio mínimo (não amplo), não usar o root no dia a dia e rotacionar credenciais." },
    { id: "clf-p08", d: "tecnologia", q: "Qual serviço ou recurso da AWS fornece informações de log do tráfego de entrada e saída em interfaces de rede em uma VPC?",
      o: ["Amazon CloudWatch Logs", "AWS CloudTrail", "VPC Flow Logs", "AWS Identity and Access Management (IAM)"], c: [2],
      e: "O VPC Flow Logs captura metadados do tráfego IP nas interfaces de rede (ENIs). CloudTrail audita chamadas de API, não pacotes de rede." },
    { id: "clf-p09", d: "seguranca", q: "Uma empresa deseja um processo automatizado para verificar continuamente suas instâncias do Amazon EC2 em busca de vulnerabilidades de software. Qual serviço da AWS atenderá a esses requisitos?",
      o: ["Amazon Cognito", "Amazon GuardDuty", "Amazon Inspector", "Amazon Detective"], c: [2],
      e: "O Amazon Inspector avalia continuamente EC2, contêineres e Lambda em busca de vulnerabilidades de software e exposição de rede. GuardDuty detecta ameaças por análise de logs; Cognito faz autenticação de usuários." },
    { id: "clf-p10", d: "conceitos", multi: true, q: "O que significa o conceito de agilidade na computação em nuvem AWS? (Escolha dois.)",
      o: ["A velocidade com que os recursos da AWS são implementados.", "A capacidade de experimentar rapidamente.", "O baixo custo de entrada na computação em nuvem.", "A velocidade com que a AWS cria novas regiões.", "A eliminação do desperdício de capacidade."], c: [0, 1],
      e: "Agilidade = provisionar recursos em minutos e experimentar rápido, com baixo custo de erro. Custo e capacidade são outros benefícios, não a definição de agilidade." },
    { id: "clf-p11", d: "conceitos", q: "Qual das alternativas a seguir é um princípio de design recomendado do AWS Well-Architected Framework?",
      o: ["Reduzir o tempo de inatividade fazendo alterações com pouca frequência e em grandes incrementos.", "Investir tempo para configurar a infraestrutura manualmente.", "Aprender a melhorar com as falhas operacionais.", "Usar design de aplicativo monolítico para centralização."], c: [2],
      e: "'Aprenda com as falhas operacionais' é um princípio do pilar de Excelência Operacional. O recomendado é o oposto das outras: mudanças pequenas e frequentes, automação e baixo acoplamento." },
    { id: "clf-p12", d: "tecnologia", q: "Qual é o propósito de ter um gateway de internet dentro de uma VPC?",
      o: ["Impor restrições de largura de banda ao tráfego da Internet.", "Criar uma conexão VPN com a VPC.", "Permitir a comunicação entre a VPC e a Internet.", "Balancear a carga do tráfego da Internet nas instâncias EC2."], c: [2],
      e: "O Internet Gateway (IGW) conecta a VPC à internet, permitindo tráfego de entrada e saída para sub-redes públicas. VPN é outro recurso; balanceamento é do ELB." },
    { id: "clf-p13", d: "tecnologia", q: "Qual dos seguintes é um banco de dados totalmente gerenciado e compatível com MySQL?",
      o: ["Amazon Redshift", "Amazon S3", "Amazon Aurora", "Amazon DynamoDB"], c: [2],
      e: "O Amazon Aurora é compatível com MySQL e PostgreSQL, com desempenho superior. Redshift é data warehouse; DynamoDB é NoSQL; S3 é armazenamento de objetos." },
    { id: "clf-p14", d: "tecnologia", multi: true, q: "Qual dos seguintes serviços pode ser usado para bloquear o tráfego de rede para uma instância? (Escolha dois.)",
      o: ["Network ACLs (ACLs de Rede)", "Amazon VPC Flow logs", "Security groups (Grupos de Segurança)", "Amazon CloudWatch", "AWS CloudTrail"], c: [0, 2],
      e: "NACLs (nível da sub-rede) e Security Groups (nível da instância) controlam o tráfego permitido/bloqueado. Flow Logs só registram; CloudWatch monitora; CloudTrail audita." },
    { id: "clf-p15", d: "cobranca", multi: true, q: "Uma empresa deseja assumir um compromisso inicial de uso contínuo de suas instâncias de produção do EC2 em troca de um custo geral reduzido. Quais opções de preços atendem a esses requisitos com o custo MAIS BAIXO? (Escolha dois.)",
      o: ["Instâncias Sob Demanda", "Instâncias Reservadas", "Hosts Dedicados", "Savings Plans", "Instâncias Spot"], c: [1, 3],
      e: "Reserved Instances e Savings Plans dão grande desconto em troca de compromisso de 1 ou 3 anos — ideal para cargas estáveis de produção. Spot é barato mas pode ser interrompido; Sob Demanda não tem compromisso nem desconto." },
    { id: "clf-p16", d: "conceitos", q: "Uma empresa vai migrar um aplicativo monolítico para a AWS e dividi-lo em microsserviços. Qual prática recomendada do Well-Architected Framework a empresa está seguindo com este plano?",
      o: ["Integrar testes funcionais como parte da implantação.", "Implantar o aplicativo em vários locais.", "Usar automação para implantar mudanças.", "Implementar dependências fracamente acopladas."], c: [3],
      e: "Quebrar um monolito em microsserviços reduz o acoplamento entre componentes (loosely coupled), um princípio do pilar de Confiabilidade/Excelência Operacional." },
    { id: "clf-p17", d: "cobranca", q: "Qual ferramenta da AWS permite planejar uso e custos do serviço e reservas, além de definir alertas personalizados quando custos ou uso excedem limites?",
      o: ["AWS Cost and Usage Report", "AWS Budgets", "Relatórios de instâncias reservadas", "Cost Explorer"], c: [1],
      e: "O AWS Budgets define orçamentos e dispara alertas ao ultrapassar limites de custo/uso. Cost Explorer analisa o histórico; o CUR é o relatório detalhado." },
    { id: "clf-p18", d: "conceitos", corrigido: true, q: "Qual recurso do AWS Cloud Adoption Framework (AWS CAF) pertence à perspectiva das pessoas (People)?",
      o: ["Parceria estratégica", "Arquitetura de dados", "Gestão de eventos", "Fluência na nuvem"], c: [3],
      e: "A perspectiva de Pessoas (People) cuida de cultura, liderança e capacitação — 'Fluência na nuvem' (Cloud Fluency) é uma de suas capacidades. 'Gestão de eventos' pertence à perspectiva de Operações; 'Arquitetura de dados' à de Plataforma." },
    { id: "clf-p19", d: "seguranca", q: "Qual serviço da AWS é usado para rastrear, registrar e auditar alterações de configuração feitas nos recursos da AWS?",
      o: ["AWS IAM", "Amazon Inspector", "AWS Config", "AWS Shield"], c: [2],
      e: "O AWS Config registra e avalia o histórico de configuração dos recursos e verifica conformidade. CloudTrail registra chamadas de API; Config registra o ESTADO dos recursos." },
    { id: "clf-p20", d: "tecnologia", q: "Para reduzir custos, uma empresa planeja migrar um banco NoSQL para a AWS. Qual serviço é totalmente gerenciado e dimensiona automaticamente a capacidade de transferência conforme a demanda?",
      o: ["Amazon Redshift", "Amazon Aurora", "Amazon DynamoDB", "Amazon RDS"], c: [2],
      e: "O DynamoDB é NoSQL totalmente gerenciado e, no modo on-demand, escala a capacidade automaticamente. RDS/Aurora são relacionais; Redshift é data warehouse." },
    { id: "clf-p21", d: "conceitos", q: "Uma empresa quer proteger suas informações, sistemas e ativos enquanto executa avaliação e mitigação de riscos. Qual pilar do Well-Architected Framework é apoiado por essas metas?",
      o: ["Confiabilidade", "Excelência operacional", "Segurança", "Eficiência de desempenho"], c: [2],
      e: "Proteger dados/sistemas e avaliar/mitigar riscos é a essência do pilar de Segurança do Well-Architected Framework." },
    { id: "clf-p22", d: "cobranca", q: "Qual serviço da AWS é sempre fornecido gratuitamente?",
      o: ["Amazon S3", "AWS Identity and Access Management (IAM)", "Elastic Load Balancer", "AWS WAF"], c: [1],
      e: "O IAM não tem custo — você só paga pelos recursos que os usuários/funções acessam. S3, ELB e WAF são cobrados por uso." },
    { id: "clf-p23", d: "tecnologia", q: "Um desenvolvedor deseja implantar um aplicativo rapidamente na AWS sem criar manualmente os recursos necessários. Qual serviço atenderá a esses requisitos?",
      o: ["Amazon Personalize", "AWS Elastic Beanstalk", "AWS CodeBuild", "Amazon EC2"], c: [1],
      e: "O Elastic Beanstalk provisiona automaticamente a infraestrutura (EC2, balanceador, auto scaling) a partir do código — você só faz o deploy. CodeBuild só compila; EC2 cru exige montar tudo na mão." },
    { id: "clf-p24", d: "seguranca", corrigido: false, q: "Qual serviço AWS é usado para fornecer criptografia para o Amazon EBS?",
      o: ["AWS Systems Manager", "AWS Certificate Manager", "AWS KMS", "AWS Config"], c: [2],
      e: "O AWS KMS gerencia as chaves usadas para criptografar volumes EBS (e muitos outros serviços). ACM gerencia certificados TLS/SSL." },
    { id: "clf-p25", d: "conceitos", q: "Qual benefício da Nuvem AWS é demonstrado pela capacidade de uma arquitetura resistir a falhas com tempo de inatividade mínimo?",
      o: ["Alta disponibilidade", "Escalabilidade", "Elasticidade", "Agilidade"], c: [0],
      e: "Alta disponibilidade (High Availability) é a capacidade de continuar operando apesar de falhas, com downtime mínimo — geralmente usando várias Zonas de Disponibilidade." },
    { id: "clf-p26", d: "tecnologia", q: "Uma empresa armazena dados confidenciais em um bucket S3 e quer protegê-los contra exclusão ou substituição acidental. Qual recurso do S3 deve usar?",
      o: ["Regras do ciclo de vida", "Versionamento", "Criptografia do lado do servidor", "Políticas de bucket"], c: [1],
      e: "O Versionamento do S3 mantém versões anteriores de cada objeto, permitindo recuperar algo excluído ou sobrescrito por engano. Criptografia protege a confidencialidade, não contra exclusão." },
    { id: "clf-p27", d: "seguranca", q: "Uma empresa precisa rastrear a atividade em suas contas e saber quando uma chamada de API é feita em seus recursos. Qual ferramenta atende a esse requisito?",
      o: ["AWS IAM", "Amazon Inspector", "Amazon CloudWatch", "AWS CloudTrail"], c: [3],
      e: "O CloudTrail registra cada chamada de API (quem, quando, qual ação). CloudWatch foca em métricas e logs operacionais, não no histórico de chamadas de API." },
    { id: "clf-p28", d: "seguranca", q: "Usar o IAM para conceder acesso apenas aos recursos necessários para executar uma tarefa é um conceito conhecido como:",
      o: ["Acesso com privilégios mínimos.", "Acesso simbólico.", "Acesso restrito.", "Acesso conforme necessário."], c: [0],
      e: "O princípio do menor privilégio (least privilege) concede só as permissões estritamente necessárias — base da segurança no IAM." },
    { id: "clf-p29", d: "conceitos", q: "Qual é uma vantagem que os usuários experimentam ao migrar cargas de trabalho locais para a Nuvem AWS?",
      o: ["Descontos de preço idênticos aos de fornecedores de hardware.", "Eliminação de todas as despesas operacionais.", "Distribuição de todos os controles operacionais para a AWS.", "Eliminação de despesas com operação e manutenção de data centers."], c: [3],
      e: "Na nuvem você não opera nem mantém data centers próprios — esse custo some. Você ainda tem despesas operacionais (uso) e mantém controles sob sua responsabilidade." },
    { id: "clf-p30", d: "seguranca", q: "Qual opção é de responsabilidade do cliente ao usar o Amazon DynamoDB no modelo de responsabilidade compartilhada da AWS?",
      o: ["Segurança física do DynamoDB", "Acesso às tabelas do DynamoDB", "Aplicação de patch do DynamoDB", "Criptografia de dados em repouso no DynamoDB"], c: [1],
      e: "Em serviços gerenciados, o cliente controla o acesso (IAM) aos dados/tabelas. Segurança física, patches e a infraestrutura de criptografia são da AWS." },
    { id: "clf-p31", d: "seguranca", q: "Uma empresa quer auditar sua senha e os detalhes de rotação de chaves para fins de conformidade. Qual serviço ou ferramenta atende a esse requisito?",
      o: ["AWS Audit Manager", "IAM Credential Report", "IAM Access Analyzer", "AWS Artifact"], c: [1],
      e: "O IAM Credential Report lista todos os usuários e o status de suas credenciais (idade da senha, rotação de chaves, MFA). Access Analyzer acha acesso externo; Artifact entrega relatórios de conformidade da AWS." },
    { id: "clf-p32", d: "tecnologia", q: "Qual serviço da AWS pode executar um banco de dados PostgreSQL gerenciado que fornece processamento de transações online (OLTP)?",
      o: ["Amazon EMR", "Amazon DynamoDB", "Amazon Athena", "Amazon RDS"], c: [3],
      e: "O Amazon RDS roda PostgreSQL (e outros engines) gerenciado, ideal para OLTP. Athena consulta dados no S3; EMR é big data; DynamoDB é NoSQL." },
    { id: "clf-p33", d: "seguranca", corrigido: true, q: "Uma empresa deseja conceder aos usuários de uma conta AWS acesso a recursos de OUTRA conta AWS. Qual serviço/recurso atenderá a esse requisito?",
      o: ["Grupo do IAM", "IAM Access Analyzer", "Função do IAM (IAM Role)", "IAM tag"], c: [2],
      e: "Acesso entre contas (cross-account) é feito com uma Função do IAM (IAM Role): a outra conta assume a função para obter acesso temporário. Grupos do IAM só organizam usuários DENTRO da mesma conta." },
    { id: "clf-p34", d: "conceitos", q: "Uma empresa está identificando suas lacunas de capacidade usando as perspectivas do AWS CAF. Qual fase da jornada de transformação da nuvem inclui essas atividades?",
      o: ["Alinhar (Align)", "Visualizar (Envision)", "Escalar (Scale)", "Lançar (Launch)"], c: [0],
      e: "Na fase Align (Alinhar), você usa as perspectivas do CAF para identificar lacunas de capacidade e dependências. Envision define a visão; Launch faz pilotos; Scale expande." },
    { id: "clf-p35", d: "cobranca", q: "Uma empresa executa milhares de simulações simultâneas no AWS Batch. Cada simulação é sem estado, tolerante a falhas e dura até 3 horas. Qual modelo de precificação otimiza custos?",
      o: ["Instâncias Spot", "Instâncias Sob Demanda", "Instâncias Reservadas", "Instâncias Dedicadas"], c: [0],
      e: "Cargas stateless e tolerantes a falhas são perfeitas para Spot, que oferece os maiores descontos (até 90%) em troca de poderem ser interrompidas." },
    { id: "clf-p36", d: "seguranca", q: "Um usuário precisa de acesso programático aos recursos da AWS por meio da AWS CLI ou da API. Qual opção fornece o acesso apropriado?",
      o: ["SSH Public Keys (Chaves Públicas SSH)", "Access keys (Chaves de Acesso)", "Amazon Inspector", "Chaves do AWS KMS"], c: [1],
      e: "Access keys (ID + secret) autenticam chamadas programáticas via CLI/SDK/API. Chaves SSH servem para conectar a instâncias; KMS é para criptografia." },
    { id: "clf-p37", d: "seguranca", multi: true, q: "Quais tarefas são responsabilidades do cliente, de acordo com o modelo de responsabilidade compartilhada da AWS? (Escolha dois.)",
      o: ["Determinar quais zonas de disponibilidade usar para buckets do S3.", "Configurar o grupo de segurança fornecido pela AWS.", "Classificar os ativos da empresa na Nuvem AWS.", "Corrigir ou atualizar o Amazon DynamoDB.", "Selecionar instâncias EC2 para executar o AWS Lambda."], c: [1, 2],
      e: "O cliente configura os Security Groups e classifica seus próprios dados/ativos. Patches de serviços gerenciados são da AWS; e nem S3 nem Lambda envolvem escolher AZ/instância (são abstraídos)." },
    { id: "clf-p38", d: "conceitos", q: "Qual opção é uma perspectiva do AWS Cloud Adoption Framework (AWS CAF)?",
      o: ["Governança (Governance)", "Eficiência de desempenho", "Sustentabilidade", "Confiabilidade"], c: [0],
      e: "As 6 perspectivas do CAF são: Negócios, Pessoas, Governança, Plataforma, Segurança e Operações. 'Eficiência de desempenho', 'Sustentabilidade' e 'Confiabilidade' são PILARES do Well-Architected, não perspectivas do CAF." },
    { id: "clf-p39", d: "cobranca", q: "Uma empresa de e-commerce migrou sua TI de um data center local para a Nuvem AWS. Qual custo é de responsabilidade direta da empresa?",
      o: ["Custo das licenças de software aplicativo.", "Custo de energia para os servidores AWS.", "Custo de segurança física do data center AWS.", "Custo da infraestrutura de hardware na AWS."], c: [0],
      e: "A empresa continua responsável por licenças do seu próprio software. Energia, segurança física e hardware dos data centers são custos absorvidos pela AWS (já embutidos no preço)." },
    { id: "clf-p40", d: "seguranca", q: "De acordo com as práticas recomendadas de segurança, como uma instância do Amazon EC2 deve receber acesso a um bucket do Amazon S3?",
      o: ["Armazenar a chave secreta e a chave de acesso de um usuário IAM em um arquivo de texto na instância.", "Modificar a política do bucket para que qualquer serviço possa fazer upload a qualquer momento.", "Fazer com que a instância EC2 assuma uma função (role) para obter os privilégios.", "Codificar a chave secreta e a de acesso diretamente no aplicativo."], c: [2],
      e: "A prática recomendada é anexar uma IAM Role à instância EC2 — ela recebe credenciais temporárias e rotacionadas automaticamente, sem chaves fixas em arquivos ou no código." },
    { id: "clf-p41", d: "tecnologia", q: "Uma empresa deseja gerenciar seus recursos da Nuvem AWS por meio de uma interface web. Qual serviço atende a esse requisito?",
      o: ["AWS Management Console", "AWS Cloud9", "AWS CLI", "AWS SDK"], c: [0],
      e: "O AWS Management Console é a interface web para gerenciar recursos pelo navegador. Cloud9 é uma IDE; CLI é linha de comando; SDK é para código." },
    { id: "clf-p42", d: "seguranca", q: "Uma empresa deseja monitorar grupos de segurança mal configurados que permitem acesso irrestrito a portas específicas. Qual serviço atende a esse requisito?",
      o: ["Amazon GuardDuty", "AWS Trusted Advisor", "Amazon CloudWatch", "AWS Health Dashboard"], c: [1],
      e: "O Trusted Advisor faz checagens de segurança e avisa, por exemplo, sobre Security Groups com portas abertas para 0.0.0.0/0. GuardDuty detecta ameaças ativas, mas a verificação de configuração recomendada aqui é do Trusted Advisor." },
    { id: "clf-p43", d: "cobranca", multi: true, q: "Uma empresa deseja receber uma notificação quando um limite de custo específico da AWS for atingido. Quais serviços ou ferramentas pode usar? (Escolha dois.)",
      o: ["Amazon Simple Queue Service (SQS)", "AWS Cost and Usage Report", "Cost Explorer", "AWS Budgets", "Amazon CloudWatch"], c: [3, 4],
      e: "O AWS Budgets dispara alertas ao atingir limites de custo; o CloudWatch também pode alarmar sobre a métrica de cobrança estimada (Billing). CUR e Cost Explorer só relatam/analisam, não notificam." },
  ];
  for (let i = 0; i < Q.length; i++) B.push(Q[i]);
})();
