"use strict";
// ============================================================
// CLImb — banco de questões CLF-C02 (parte 4)
// Domínio: Tecnologia e Serviços (34% do exame).
// Computação, armazenamento, bancos de dados, rede/entrega de conteúdo,
// análise, integração de apps e ferramentas de gerenciamento/monitoramento.
// ============================================================
(function () {
  if (typeof window === "undefined") return;
  const B = (window.SIMULADOS_CLF = window.SIMULADOS_CLF || []);
  const Q = [
    // ---------- COMPUTAÇÃO ----------
    { id: "clf-t01", d: "tecnologia", q: "Qual serviço fornece capacidade de computação redimensionável na forma de máquinas virtuais na nuvem?",
      o: ["Amazon EC2", "Amazon S3", "Amazon RDS", "Amazon Route 53"], c: [0],
      e: "O Amazon EC2 (Elastic Compute Cloud) oferece servidores virtuais (instâncias) com capacidade ajustável conforme a necessidade." },
    { id: "clf-t02", d: "tecnologia", q: "Qual serviço de computação sem servidor (serverless) executa código em resposta a eventos, cobrando apenas pelo tempo de execução?",
      o: ["AWS Lambda", "Amazon EC2", "Amazon Lightsail", "AWS Batch"], c: [0],
      e: "O AWS Lambda roda código em resposta a eventos sem provisionar servidores; você paga pelo tempo de execução e número de requisições." },
    { id: "clf-t03", d: "tecnologia", q: "Qual serviço simplifica a implantação e o gerenciamento de aplicações, cuidando automaticamente de capacidade, balanceamento e escalonamento a partir do código enviado?",
      o: ["AWS Elastic Beanstalk", "Amazon S3", "AWS IAM", "Amazon Athena"], c: [0],
      e: "O Elastic Beanstalk provisiona e gerencia a infraestrutura (EC2, ELB, Auto Scaling) automaticamente; você só envia o código." },
    { id: "clf-t04", d: "tecnologia", q: "Qual serviço oferece servidores virtuais privados simplificados, com preço previsível, ideal para sites e apps pequenos?",
      o: ["Amazon Lightsail", "Amazon EC2 Spot", "AWS Lambda", "Amazon EMR"], c: [0],
      e: "O Amazon Lightsail entrega VPS com preço mensal fixo e configuração simplificada, ótimo para projetos menores e quem está começando." },
    { id: "clf-t05", d: "tecnologia", q: "Qual serviço permite executar contêineres Docker gerenciados na AWS, com integração nativa a outros serviços?",
      o: ["Amazon ECS", "Amazon S3", "Amazon RDS", "Amazon Route 53"], c: [0],
      e: "O Amazon ECS (Elastic Container Service) orquestra contêineres Docker; o EKS faz o mesmo com Kubernetes." },
    { id: "clf-t06", d: "tecnologia", q: "Qual opção permite executar contêineres sem gerenciar os servidores subjacentes (serverless para contêineres)?",
      o: ["AWS Fargate", "Amazon EC2", "Amazon EBS", "Amazon Glacier"], c: [0],
      e: "O AWS Fargate executa contêineres (com ECS ou EKS) sem que você precise provisionar e gerenciar instâncias EC2." },
    { id: "clf-t07", d: "tecnologia", q: "Qual serviço gerenciado executa Kubernetes na AWS?",
      o: ["Amazon EKS", "Amazon ECS", "AWS Lambda", "Amazon Lightsail"], c: [0],
      e: "O Amazon EKS (Elastic Kubernetes Service) é o serviço gerenciado de Kubernetes da AWS." },
    { id: "clf-t08", d: "tecnologia", q: "Qual recurso ajusta automaticamente o número de instâncias EC2 conforme a demanda da aplicação?",
      o: ["Amazon EC2 Auto Scaling", "Amazon S3", "AWS IAM", "Amazon Macie"], c: [0],
      e: "O EC2 Auto Scaling adiciona ou remove instâncias automaticamente para manter o desempenho e otimizar custos conforme a carga." },

    // ---------- ARMAZENAMENTO ----------
    { id: "clf-t09", d: "tecnologia", q: "Qual serviço fornece armazenamento de objetos altamente durável e escalável?",
      o: ["Amazon S3", "Amazon EBS", "Amazon EC2", "Amazon VPC"], c: [0],
      e: "O Amazon S3 armazena objetos (arquivos) com 11 noves de durabilidade, escalabilidade praticamente ilimitada e acesso via HTTP/HTTPS." },
    { id: "clf-t10", d: "tecnologia", q: "Qual serviço fornece volumes de armazenamento em bloco para serem anexados a instâncias EC2?",
      o: ["Amazon EBS", "Amazon S3", "Amazon Glacier", "Amazon Route 53"], c: [0],
      e: "O Amazon EBS (Elastic Block Store) oferece volumes de bloco persistentes que funcionam como discos para instâncias EC2." },
    { id: "clf-t11", d: "tecnologia", q: "Qual classe de armazenamento do S3 é a mais econômica para arquivamento de longo prazo com acesso raríssimo?",
      o: ["S3 Glacier Deep Archive", "S3 Standard", "S3 Standard-IA", "S3 Intelligent-Tiering"], c: [0],
      e: "O S3 Glacier Deep Archive é a opção mais barata, para dados acessados muito raramente, com tempo de recuperação de horas." },
    { id: "clf-t12", d: "tecnologia", q: "Qual classe do S3 move objetos automaticamente entre camadas de acesso para otimizar custo quando o padrão de acesso é imprevisível?",
      o: ["S3 Intelligent-Tiering", "S3 Glacier", "S3 Standard", "S3 One Zone-IA"], c: [0],
      e: "O S3 Intelligent-Tiering move objetos entre camadas (frequente/infrequente) automaticamente conforme o uso, sem taxa de recuperação." },
    { id: "clf-t13", d: "tecnologia", q: "Qual serviço fornece um sistema de arquivos compartilhado (NFS) escalável para várias instâncias EC2 Linux ao mesmo tempo?",
      o: ["Amazon EFS", "Amazon EBS", "Amazon S3 Glacier", "Amazon Redshift"], c: [0],
      e: "O Amazon EFS (Elastic File System) oferece armazenamento de arquivos compartilhado e elástico, montável por várias instâncias simultaneamente." },
    { id: "clf-t14", d: "tecnologia", q: "Qual serviço ajuda a transferir grandes volumes de dados para a AWS usando dispositivos físicos quando a rede é insuficiente?",
      o: ["AWS Snow Family (ex.: Snowball)", "Amazon S3 Select", "AWS Lambda", "Amazon Athena"], c: [0],
      e: "A AWS Snow Family (Snowcone/Snowball) usa dispositivos físicos para migrar petabytes de dados quando transferir pela internet seria inviável." },
    { id: "clf-t15", d: "tecnologia", q: "Qual recurso do S3 ajuda a reduzir custos movendo objetos automaticamente entre classes de armazenamento com base em regras de tempo?",
      o: ["Regras de ciclo de vida (Lifecycle).", "Versionamento.", "Bucket policy.", "Static website hosting."], c: [0],
      e: "As regras de ciclo de vida transicionam objetos para classes mais baratas (ou os expiram) automaticamente conforme a idade." },
    { id: "clf-t16", d: "tecnologia", q: "Para fazer backup gerenciado e centralizado de vários serviços (EBS, RDS, DynamoDB, EFS) com políticas, qual serviço usar?",
      o: ["AWS Backup", "Amazon S3 Glacier", "AWS Config", "Amazon Inspector"], c: [0],
      e: "O AWS Backup centraliza e automatiza backups de múltiplos serviços com políticas de retenção, simplificando a conformidade." },

    // ---------- BANCOS DE DADOS ----------
    { id: "clf-t17", d: "tecnologia", q: "Qual serviço gerenciado de banco de dados relacional suporta engines como MySQL, PostgreSQL, MariaDB, Oracle e SQL Server?",
      o: ["Amazon RDS", "Amazon DynamoDB", "Amazon S3", "Amazon Redshift"], c: [0],
      e: "O Amazon RDS gerencia bancos relacionais (provisão, patches, backup, failover) em vários engines populares." },
    { id: "clf-t18", d: "tecnologia", q: "Qual banco de dados é NoSQL, totalmente gerenciado, de chave-valor e documento, com latência de milissegundos de um dígito?",
      o: ["Amazon DynamoDB", "Amazon Aurora", "Amazon RDS", "Amazon Redshift"], c: [0],
      e: "O DynamoDB é um banco NoSQL serverless com desempenho consistente em qualquer escala, ideal para alta taxa de requisições." },
    { id: "clf-t19", d: "tecnologia", q: "Qual serviço é um data warehouse para análise de grandes volumes de dados com SQL?",
      o: ["Amazon Redshift", "Amazon DynamoDB", "Amazon RDS", "Amazon ElastiCache"], c: [0],
      e: "O Amazon Redshift é o data warehouse da AWS, otimizado para consultas analíticas (OLAP) sobre grandes conjuntos de dados." },
    { id: "clf-t20", d: "tecnologia", q: "Qual serviço fornece cache em memória gerenciado (Redis/Memcached) para acelerar aplicações?",
      o: ["Amazon ElastiCache", "Amazon RDS", "Amazon S3", "Amazon Athena"], c: [0],
      e: "O Amazon ElastiCache oferece cache em memória (Redis ou Memcached) para reduzir a latência e aliviar a carga sobre os bancos." },
    { id: "clf-t21", d: "tecnologia", q: "Qual banco de dados relacional da AWS é compatível com MySQL/PostgreSQL e foi projetado para nuvem com alto desempenho e replicação?",
      o: ["Amazon Aurora", "Amazon DynamoDB", "Amazon Neptune", "Amazon Redshift"], c: [0],
      e: "O Amazon Aurora é compatível com MySQL e PostgreSQL, oferecendo desempenho superior e armazenamento auto-replicado entre AZs." },
    { id: "clf-t22", d: "tecnologia", q: "Qual serviço é um banco de dados de grafos gerenciado, útil para redes sociais e mecanismos de recomendação?",
      o: ["Amazon Neptune", "Amazon RDS", "Amazon Redshift", "Amazon S3"], c: [0],
      e: "O Amazon Neptune é um banco de dados de grafos gerenciado, ideal para dados altamente conectados (relacionamentos)." },
    { id: "clf-t23", d: "tecnologia", q: "Qual recurso do Amazon RDS aumenta a disponibilidade mantendo uma cópia em espera (standby) em outra Zona de Disponibilidade?",
      o: ["Implantação Multi-AZ", "Read Replica", "Versionamento", "Elastic IP"], c: [0],
      e: "O Multi-AZ mantém uma réplica em espera em outra AZ e faz failover automático em caso de falha, aumentando a disponibilidade." },
    { id: "clf-t24", d: "tecnologia", q: "Qual recurso do RDS melhora o desempenho de LEITURA distribuindo consultas para cópias somente leitura?",
      o: ["Read Replicas", "Multi-AZ", "Snapshots", "Security Groups"], c: [0],
      e: "Read Replicas são cópias somente leitura que aliviam a carga de leitura do banco principal, melhorando a escalabilidade de leitura." },
    { id: "clf-t25", d: "tecnologia", q: "Qual serviço permite consultar dados diretamente no Amazon S3 usando SQL, sem precisar carregar em um banco?",
      o: ["Amazon Athena", "Amazon RDS", "Amazon DynamoDB", "Amazon ElastiCache"], c: [0],
      e: "O Amazon Athena é um serviço serverless de consulta que roda SQL diretamente sobre arquivos no S3, pagando por consulta." },

    // ---------- REDE E ENTREGA DE CONTEÚDO ----------
    { id: "clf-t26", d: "tecnologia", q: "Qual serviço é uma rede de entrega de conteúdo (CDN) que distribui conteúdo com baixa latência a partir de locais de borda?",
      o: ["Amazon CloudFront", "Amazon Route 53", "Amazon VPC", "AWS Direct Connect"], c: [0],
      e: "O Amazon CloudFront armazena conteúdo em cache nas Edge Locations, entregando-o aos usuários com baixa latência." },
    { id: "clf-t27", d: "tecnologia", q: "Qual serviço é um DNS gerenciado e escalável, com roteamento e verificação de integridade?",
      o: ["Amazon Route 53", "Amazon CloudFront", "AWS WAF", "Amazon S3"], c: [0],
      e: "O Amazon Route 53 é o serviço de DNS da AWS, que também registra domínios e roteia tráfego com várias políticas e health checks." },
    { id: "clf-t28", d: "tecnologia", q: "Qual serviço estabelece uma conexão de rede DEDICADA e privada entre o data center do cliente e a AWS?",
      o: ["AWS Direct Connect", "AWS VPN", "Amazon CloudFront", "Amazon Route 53"], c: [0],
      e: "O AWS Direct Connect cria um link físico dedicado entre o ambiente local e a AWS, com largura de banda consistente e menor latência." },
    { id: "clf-t29", d: "tecnologia", q: "Qual serviço cria um túnel criptografado pela internet entre uma rede local e uma VPC?",
      o: ["AWS Site-to-Site VPN", "AWS Direct Connect", "Amazon CloudFront", "Amazon Athena"], c: [0],
      e: "O AWS Site-to-Site VPN estabelece uma conexão criptografada (IPsec) pela internet entre a rede on-premises e a VPC." },
    { id: "clf-t30", d: "tecnologia", q: "Qual recurso distribui automaticamente o tráfego de entrada entre várias instâncias/alvos saudáveis?",
      o: ["Elastic Load Balancing (ELB)", "Amazon S3", "AWS IAM", "Amazon SQS"], c: [0],
      e: "O Elastic Load Balancing distribui o tráfego entre múltiplos alvos (instâncias, contêineres, IPs) em uma ou mais AZs, aumentando disponibilidade." },
    { id: "clf-t31", d: "tecnologia", q: "Qual recurso da VPC permite que instâncias em sub-redes privadas acessem a internet para saída (ex.: baixar atualizações) sem aceitar conexões de entrada?",
      o: ["NAT Gateway", "Internet Gateway aberto a todos", "Bucket S3 público", "Elastic IP no banco"], c: [0],
      e: "O NAT Gateway permite que recursos em sub-redes privadas iniciem conexões de saída para a internet sem ficarem acessíveis de fora." },
    { id: "clf-t32", d: "tecnologia", q: "Qual recurso permite conectar de forma privada uma VPC a serviços da AWS sem passar pela internet pública?",
      o: ["VPC Endpoint (PrivateLink)", "Internet Gateway", "Elastic IP", "Route 53"], c: [0],
      e: "VPC Endpoints (incluindo o AWS PrivateLink) permitem acesso privado a serviços (ex.: S3, DynamoDB) sem tráfego pela internet." },
    { id: "clf-t33", d: "tecnologia", q: "Para conectar muitas VPCs e redes on-premises de forma centralizada e escalável, qual serviço é indicado?",
      o: ["AWS Transit Gateway", "Amazon S3", "AWS Budgets", "Amazon Athena"], c: [0],
      e: "O AWS Transit Gateway atua como um hub central que interliga várias VPCs e conexões on-premises, simplificando a topologia de rede." },

    // ---------- INTEGRAÇÃO DE APLICAÇÕES / MENSAGERIA ----------
    { id: "clf-t34", d: "tecnologia", q: "Qual serviço é uma fila de mensagens gerenciada que desacopla componentes de uma aplicação?",
      o: ["Amazon SQS", "Amazon SNS", "Amazon S3", "Amazon RDS"], c: [0],
      e: "O Amazon SQS (Simple Queue Service) é uma fila gerenciada que armazena mensagens entre componentes, permitindo acoplamento fraco e resiliência." },
    { id: "clf-t35", d: "tecnologia", q: "Qual serviço é de mensagens no modelo publish/subscribe (pub/sub), entregando notificações a múltiplos assinantes?",
      o: ["Amazon SNS", "Amazon SQS", "Amazon EBS", "Amazon Redshift"], c: [0],
      e: "O Amazon SNS (Simple Notification Service) envia mensagens a vários assinantes (e-mail, SMS, SQS, Lambda) no padrão pub/sub." },
    { id: "clf-t36", d: "tecnologia", q: "Qual serviço cria, publica e gerencia APIs REST/HTTP/WebSocket em escala, servindo de 'porta de entrada' para back-ends?",
      o: ["Amazon API Gateway", "Amazon Route 53", "Amazon CloudFront", "AWS Config"], c: [0],
      e: "O Amazon API Gateway gerencia APIs (criação, segurança, throttling, versionamento), conectando clientes a Lambda, EC2 e outros back-ends." },
    { id: "clf-t37", d: "tecnologia", q: "Qual serviço coordena fluxos de trabalho (workflows) com várias etapas e estados, orquestrando funções Lambda e outros serviços?",
      o: ["AWS Step Functions", "Amazon SQS", "Amazon S3", "Amazon Athena"], c: [0],
      e: "O AWS Step Functions orquestra etapas de um fluxo de trabalho como uma máquina de estados, coordenando serviços com tratamento de erros e retries." },

    // ---------- ANÁLISE / BIG DATA ----------
    { id: "clf-t38", d: "tecnologia", q: "Qual serviço processa grandes volumes de dados usando frameworks como Apache Spark e Hadoop de forma gerenciada?",
      o: ["Amazon EMR", "Amazon RDS", "Amazon Route 53", "Amazon SNS"], c: [0],
      e: "O Amazon EMR executa frameworks de big data (Spark, Hadoop, Hive) em clusters gerenciados para processamento e análise em larga escala." },
    { id: "clf-t39", d: "tecnologia", q: "Qual serviço de business intelligence cria painéis e visualizações interativas a partir de dados da AWS?",
      o: ["Amazon QuickSight", "Amazon Athena", "Amazon EMR", "Amazon S3"], c: [0],
      e: "O Amazon QuickSight é o serviço de BI da AWS para criar dashboards e relatórios interativos." },
    { id: "clf-t40", d: "tecnologia", q: "Qual serviço é um ETL (extração, transformação e carga) serverless para preparar e integrar dados?",
      o: ["AWS Glue", "Amazon Redshift", "Amazon SQS", "Amazon Route 53"], c: [0],
      e: "O AWS Glue é um serviço de ETL serverless que descobre, prepara e combina dados para análise e machine learning." },
    { id: "clf-t41", d: "tecnologia", q: "Qual serviço captura, processa e analisa dados de streaming em tempo real?",
      o: ["Amazon Kinesis", "Amazon Glacier", "Amazon RDS", "AWS Artifact"], c: [0],
      e: "O Amazon Kinesis ingere e processa dados em streaming (logs, telemetria, cliques) em tempo real e em escala." },

    // ---------- GERENCIAMENTO E MONITORAMENTO ----------
    { id: "clf-t42", d: "tecnologia", q: "Qual serviço coleta métricas, logs e cria alarmes para monitorar recursos e aplicações da AWS?",
      o: ["Amazon CloudWatch", "AWS CloudTrail", "AWS Config", "Amazon Inspector"], c: [0],
      e: "O Amazon CloudWatch monitora métricas e logs, cria alarmes e painéis, e pode acionar ações automáticas (ex.: Auto Scaling)." },
    { id: "clf-t43", d: "tecnologia", q: "Qual serviço provisiona infraestrutura como código usando templates declarativos (JSON/YAML)?",
      o: ["AWS CloudFormation", "AWS CodeDeploy", "Amazon EC2", "Amazon S3"], c: [0],
      e: "O AWS CloudFormation cria e gerencia recursos de forma automatizada e repetível a partir de templates de infraestrutura como código." },
    { id: "clf-t44", d: "tecnologia", q: "Qual serviço ajuda a gerenciar, configurar e aplicar patches em frota de instâncias e recursos em escala?",
      o: ["AWS Systems Manager", "Amazon Inspector", "AWS Artifact", "Amazon QuickSight"], c: [0],
      e: "O AWS Systems Manager oferece visibilidade e controle operacional (patches, automações, parâmetros, acesso seguro) sobre os recursos." },
    { id: "clf-t45", d: "tecnologia", q: "Qual serviço dá uma visão personalizada da saúde dos serviços da AWS que afetam especificamente a sua conta?",
      o: ["AWS Health Dashboard (Personal Health)", "AWS Trusted Advisor", "Amazon CloudWatch", "AWS Config"], c: [0],
      e: "O AWS Health Dashboard mostra eventos e a saúde dos serviços que impactam seus recursos, com avisos personalizados para a conta." },
    { id: "clf-t46", d: "tecnologia", q: "Qual serviço recomenda o redimensionamento (right-sizing) de instâncias EC2 com base em uso real para otimizar custo e desempenho?",
      o: ["AWS Compute Optimizer", "AWS Shield", "Amazon Macie", "AWS Artifact"], c: [0],
      e: "O AWS Compute Optimizer analisa métricas de utilização e recomenda os tipos/tamanhos de recurso ideais." },
    { id: "clf-t47", d: "tecnologia", q: "Qual conjunto de serviços apoia integração e entrega contínuas (CI/CD)?",
      o: ["AWS CodeCommit, CodeBuild, CodeDeploy e CodePipeline", "Amazon S3, EBS e Glacier", "Route 53 e CloudFront", "SQS e SNS"], c: [0],
      e: "A família 'Code' (CodeCommit, CodeBuild, CodeDeploy, CodePipeline) cobre versionamento, build, deploy e orquestração de pipelines CI/CD." },
    { id: "clf-t48", d: "tecnologia", q: "Qual serviço facilita o lançamento rápido de uma aplicação completa (computação, banco etc.) seguindo as melhores práticas, ideal para iniciantes?",
      o: ["AWS App Runner / Elastic Beanstalk", "Amazon S3 Glacier", "AWS Artifact", "Amazon Macie"], c: [0],
      e: "Serviços como o Elastic Beanstalk (e o App Runner para apps em contêiner) abstraem a infraestrutura, permitindo subir aplicações rapidamente." },

    // ---------- INTERFACES / ACESSO ----------
    { id: "clf-t49", d: "tecnologia", q: "Quais são formas válidas de interagir com os serviços da AWS?",
      o: ["AWS Management Console, AWS CLI e SDKs.", "Apenas o console web.", "Apenas a CLI.", "Apenas e-mail."], c: [0],
      e: "É possível usar o Console (web), a AWS CLI (linha de comando) e os SDKs (em várias linguagens) para gerenciar recursos." },
    { id: "clf-t50", d: "tecnologia", q: "Qual ferramenta permite automatizar e executar comandos da AWS em scripts no terminal?",
      o: ["AWS CLI", "AWS Management Console", "AWS Artifact", "Amazon QuickSight"], c: [0],
      e: "A AWS CLI permite controlar serviços da AWS via linha de comando, ideal para automação e scripts." },

    // ---------- MAIS COMPUTAÇÃO/ARMAZENAMENTO/BANCO ----------
    { id: "clf-t51", d: "tecnologia", q: "O que é uma Amazon Machine Image (AMI)?",
      o: ["Um modelo com o sistema operacional e configurações usado para lançar instâncias EC2.", "Um tipo de bucket S3.", "Uma política do IAM.", "Um plano de suporte."], c: [0],
      e: "A AMI é a imagem-modelo (SO + software + configs) a partir da qual instâncias EC2 são lançadas." },
    { id: "clf-t52", d: "tecnologia", q: "Qual a finalidade de um snapshot do Amazon EBS?",
      o: ["Criar um backup incremental do volume armazenado no S3.", "Aumentar a CPU da instância.", "Distribuir tráfego.", "Criar um usuário IAM."], c: [0],
      e: "Snapshots do EBS são backups incrementais (armazenados no S3) que permitem restaurar volumes ou criar novos." },
    { id: "clf-t53", d: "tecnologia", q: "Qual serviço é mais adequado para hospedar um site estático com alta durabilidade e baixo custo?",
      o: ["Amazon S3 (static website hosting)", "Amazon RDS", "Amazon EMR", "Amazon Neptune"], c: [0],
      e: "O S3 pode hospedar sites estáticos (HTML/CSS/JS) com alta durabilidade e baixo custo, frequentemente combinado com CloudFront." },
    { id: "clf-t54", d: "tecnologia", q: "Para uma carga que exige instâncias EC2 com GPUs para machine learning, o cliente deve:",
      o: ["Escolher uma família/tipo de instância otimizada para GPU.", "Usar apenas o S3.", "Usar o Route 53.", "Usar o AWS Budgets."], c: [0],
      e: "O EC2 oferece famílias de instâncias para diferentes necessidades (computação, memória, GPU, armazenamento); cargas de ML usam tipos com GPU." },
    { id: "clf-t55", d: "tecnologia", q: "Qual serviço serverless de banco de dados é indicado quando se quer escalar automaticamente e pagar pelo uso, sem gerenciar capacidade?",
      o: ["Amazon DynamoDB (on-demand) / Aurora Serverless", "Amazon EC2", "Amazon EBS", "Amazon CloudFront"], c: [0],
      e: "DynamoDB on-demand e Aurora Serverless ajustam a capacidade automaticamente e cobram conforme o uso, sem provisionar servidores fixos." },
    { id: "clf-t56", d: "tecnologia", q: "Qual serviço é indicado para migrar bancos de dados para a AWS com mínima indisponibilidade?",
      o: ["AWS Database Migration Service (DMS)", "Amazon CloudFront", "AWS Budgets", "Amazon QuickSight"], c: [0],
      e: "O AWS DMS migra bancos de dados para a AWS de forma contínua, mantendo a origem operacional durante a migração." },
    { id: "clf-t57", d: "tecnologia", q: "Qual serviço ajuda a descobrir, inventariar e planejar a migração de servidores on-premises para a AWS?",
      o: ["AWS Migration Hub / Application Discovery Service", "Amazon Athena", "AWS WAF", "Amazon SNS"], c: [0],
      e: "O AWS Migration Hub acompanha migrações em um só lugar, e o Application Discovery Service coleta dados dos servidores locais para planejar a migração." },
    { id: "clf-t58", d: "tecnologia", q: "Qual serviço fornece uma loja de aplicações pré-aprovadas para que equipes implantem recursos de forma padronizada e governada?",
      o: ["AWS Service Catalog", "Amazon S3", "Amazon Route 53", "Amazon Macie"], c: [0],
      e: "O AWS Service Catalog permite criar e gerenciar catálogos de produtos de TI aprovados, garantindo conformidade e padronização no provisionamento." },
    { id: "clf-t59", d: "tecnologia", q: "Qual serviço de IA/ML totalmente gerenciado permite construir, treinar e implantar modelos de machine learning?",
      o: ["Amazon SageMaker", "Amazon Athena", "Amazon Redshift", "Amazon SQS"], c: [0],
      e: "O Amazon SageMaker cobre todo o ciclo de ML (preparar, treinar, ajustar e implantar modelos) de forma gerenciada." },
    { id: "clf-t60", d: "tecnologia", q: "Qual serviço de IA converte texto em fala realista?",
      o: ["Amazon Polly", "Amazon Rekognition", "Amazon Translate", "Amazon Comprehend"], c: [0],
      e: "O Amazon Polly transforma texto em fala (TTS). Rekognition analisa imagens/vídeo; Translate traduz; Comprehend faz NLP." },
    { id: "clf-t61", d: "tecnologia", q: "Qual serviço de IA analisa imagens e vídeos para detectar objetos, rostos e conteúdo?",
      o: ["Amazon Rekognition", "Amazon Polly", "Amazon Lex", "Amazon Kendra"], c: [0],
      e: "O Amazon Rekognition oferece análise de imagem e vídeo (detecção de objetos, rostos, texto, moderação de conteúdo)." },
    { id: "clf-t62", d: "tecnologia", q: "Qual serviço permite criar chatbots e assistentes de voz/texto (conversational AI)?",
      o: ["Amazon Lex", "Amazon Polly", "Amazon Rekognition", "Amazon Athena"], c: [0],
      e: "O Amazon Lex constrói interfaces conversacionais (chatbots) com reconhecimento de fala e linguagem natural, a mesma tecnologia da Alexa." },
    { id: "clf-t63", d: "tecnologia", q: "Qual serviço de IA generativa da AWS dá acesso a modelos de fundação (foundation models) por API?",
      o: ["Amazon Bedrock", "Amazon Redshift", "Amazon EBS", "AWS Config"], c: [0],
      e: "O Amazon Bedrock oferece acesso gerenciado a modelos de fundação de vários provedores via API, para construir aplicações de IA generativa." },
    { id: "clf-t64", d: "tecnologia", q: "Qual serviço de IA extrai texto e dados de documentos digitalizados (OCR inteligente)?",
      o: ["Amazon Textract", "Amazon Polly", "Amazon Lex", "Amazon Kinesis"], c: [0],
      e: "O Amazon Textract extrai texto, formulários e tabelas de documentos automaticamente, além de simples OCR." },
    { id: "clf-t65", d: "tecnologia", q: "Qual serviço usa processamento de linguagem natural para extrair insights (sentimento, entidades) de textos?",
      o: ["Amazon Comprehend", "Amazon Rekognition", "Amazon Polly", "Amazon EMR"], c: [0],
      e: "O Amazon Comprehend faz NLP para identificar idioma, entidades, frases-chave e sentimento em textos." },
    { id: "clf-t66", d: "tecnologia", q: "Qual recurso do EC2 permite reservar um endereço IPv4 público estático que pode ser remapeado entre instâncias?",
      o: ["Elastic IP", "Internet Gateway", "Security Group", "Snapshot"], c: [0],
      e: "Um Elastic IP é um endereço IPv4 público estático associável a instâncias, podendo ser remapeado em caso de falha." },
    { id: "clf-t67", d: "tecnologia", q: "Qual afirmação sobre o Amazon S3 e a estrutura de pastas é correta?",
      o: ["O S3 é armazenamento de objetos plano; 'pastas' são apenas prefixos no nome da chave.", "O S3 é um sistema de arquivos hierárquico real.", "O S3 só guarda bancos relacionais.", "O S3 exige uma instância EC2 para funcionar."], c: [0],
      e: "O S3 é um armazenamento de objetos com namespace plano; o que parece 'pasta' é, na verdade, um prefixo no nome (key) do objeto." },
    { id: "clf-t68", d: "tecnologia", q: "Para uma aplicação que precisa enviar e-mails transacionais em escala, qual serviço é indicado?",
      o: ["Amazon SES (Simple Email Service)", "Amazon SQS", "Amazon S3", "AWS Config"], c: [0],
      e: "O Amazon SES envia e recebe e-mails (transacionais e de marketing) de forma escalável e econômica." },
    { id: "clf-t69", d: "tecnologia", q: "Qual serviço é mais indicado para uma carga de trabalho de processamento em lote que gerencia filas e provisiona recursos de computação automaticamente?",
      o: ["AWS Batch", "Amazon Route 53", "Amazon CloudFront", "AWS Artifact"], c: [0],
      e: "O AWS Batch planeja e executa jobs em lote, provisionando dinamicamente a quantidade ideal de computação (inclusive Spot)." },
    { id: "clf-t70", d: "tecnologia", q: "Qual serviço de armazenamento é melhor para dados acessados com pouca frequência, mas que ainda exigem acesso em milissegundos quando necessários?",
      o: ["S3 Standard-Infrequent Access (Standard-IA)", "S3 Glacier Deep Archive", "Amazon EBS io2", "Amazon EFS"], c: [0],
      e: "O S3 Standard-IA é para dados acessados raramente, mas com recuperação imediata; tem armazenamento mais barato e taxa por recuperação." },
    { id: "clf-t71", d: "tecnologia", q: "Qual recurso de rede controla o tráfego permitido no nível da INSTÂNCIA EC2 e é stateful?",
      o: ["Security Group", "Network ACL", "Route Table", "Internet Gateway"], c: [0],
      e: "O Security Group é um firewall virtual stateful no nível da instância: ao permitir uma entrada, a resposta de saída é liberada automaticamente." },
    { id: "clf-t72", d: "tecnologia", q: "Qual componente da VPC define para onde o tráfego de uma sub-rede deve ser encaminhado?",
      o: ["Tabela de rotas (Route Table)", "Security Group", "Snapshot", "Bucket policy"], c: [0],
      e: "A tabela de rotas associa sub-redes a destinos de tráfego (ex.: rota 0.0.0.0/0 para um Internet Gateway torna a sub-rede pública)." },
    { id: "clf-t73", d: "tecnologia", q: "Qual serviço gerenciado de diretório permite integrar o Microsoft Active Directory com a AWS?",
      o: ["AWS Directory Service", "Amazon Cognito", "AWS IAM", "Amazon Macie"], c: [0],
      e: "O AWS Directory Service oferece diretórios gerenciados (incluindo AWS Managed Microsoft AD) para integrar recursos da AWS ao Active Directory." },
    { id: "clf-t74", d: "tecnologia", q: "Qual serviço gerencia identidade e autenticação de USUÁRIOS de aplicativos web e móveis (sign-up/sign-in)?",
      o: ["Amazon Cognito", "AWS IAM", "AWS Organizations", "Amazon Inspector"], c: [0],
      e: "O Amazon Cognito gerencia cadastro, login e federação de usuários de aplicações (diferente do IAM, que gerencia acesso a recursos da AWS)." },
    { id: "clf-t75", d: "tecnologia", q: "Qual a melhor opção para arquivar dados que quase nunca serão acessados, com o menor custo, aceitando horas para recuperação?",
      o: ["Amazon S3 Glacier Deep Archive", "Amazon S3 Standard", "Amazon EBS", "Amazon ElastiCache"], c: [0],
      e: "O Glacier Deep Archive é a camada de menor custo para arquivamento de longuíssimo prazo, com tempo de recuperação na casa de horas." },
    { id: "clf-t76", d: "tecnologia", q: "Qual serviço da AWS é usado para registrar domínios e gerenciar o roteamento DNS?",
      o: ["Amazon Route 53", "Amazon CloudFront", "Amazon VPC", "AWS Direct Connect"], c: [0],
      e: "O Route 53 registra domínios, hospeda zonas DNS e roteia o tráfego dos usuários para os recursos certos." },
    { id: "clf-t77", d: "tecnologia", q: "Qual serviço acelera o desempenho de aplicações globais roteando o tráfego pela rede da AWS até o endpoint ótimo?",
      o: ["AWS Global Accelerator", "Amazon Athena", "AWS Config", "Amazon SQS"], c: [0],
      e: "O AWS Global Accelerator usa a rede global da AWS e IPs anycast para direcionar usuários ao endpoint mais saudável e próximo, melhorando latência e disponibilidade." },
    { id: "clf-t78", d: "tecnologia", q: "Qual serviço fornece um data lake e facilita configurá-lo com segurança e governança de forma centralizada?",
      o: ["AWS Lake Formation", "Amazon EBS", "Amazon Route 53", "AWS Shield"], c: [0],
      e: "O AWS Lake Formation simplifica a criação, a segurança e a governança de data lakes no S3." },
    { id: "clf-t79", d: "tecnologia", q: "Qual serviço é indicado para entregar uma aplicação em contêiner sem gerenciar a infraestrutura, a partir do código-fonte ou imagem?",
      o: ["AWS App Runner", "Amazon EC2", "Amazon EBS", "AWS Config"], c: [0],
      e: "O AWS App Runner executa aplicações web e APIs em contêiner de forma totalmente gerenciada, escalando automaticamente, sem gerenciar servidores." },
    { id: "clf-t80", d: "tecnologia", q: "Qual recurso permite que duas VPCs se comuniquem de forma privada usando IPs privados?",
      o: ["VPC Peering", "Internet Gateway", "Elastic IP", "Bucket policy"], c: [0],
      e: "O VPC Peering conecta duas VPCs para que se comuniquem usando endereços IP privados, como se estivessem na mesma rede." },
    { id: "clf-t81", d: "tecnologia", q: "Qual serviço você usaria para executar consultas analíticas em petabytes de dados estruturados com alto desempenho?",
      o: ["Amazon Redshift", "Amazon DynamoDB", "Amazon ElastiCache", "Amazon SQS"], c: [0],
      e: "O Amazon Redshift é otimizado para análise (OLAP) de grandes volumes de dados estruturados com SQL e alto desempenho." },
    { id: "clf-t82", d: "tecnologia", q: "Qual a principal vantagem do AWS Lambda em relação a executar a mesma lógica em uma instância EC2 sempre ligada?",
      o: ["Você paga apenas pelo tempo de execução e não gerencia servidores.", "É sempre mais lento.", "Exige reservar capacidade por 3 anos.", "Não escala."], c: [0],
      e: "Com o Lambda você não provisiona nem mantém servidores e paga só pela execução, escalando automaticamente conforme os eventos." },
    { id: "clf-t83", d: "tecnologia", q: "Qual serviço você usaria para distribuir um vídeo para usuários no mundo todo com baixa latência?",
      o: ["Amazon CloudFront", "Amazon EBS", "Amazon RDS", "AWS Config"], c: [0],
      e: "O CloudFront (CDN) entrega o conteúdo a partir das Edge Locations mais próximas dos usuários, reduzindo a latência globalmente." },
    { id: "clf-t84", d: "tecnologia", q: "Qual serviço facilita criar e gerenciar uma frota de dispositivos IoT conectados à nuvem?",
      o: ["AWS IoT Core", "Amazon Redshift", "AWS Budgets", "Amazon Macie"], c: [0],
      e: "O AWS IoT Core conecta dispositivos IoT à nuvem de forma segura e em escala, permitindo coletar dados e atuar sobre eles." },
    { id: "clf-t85", d: "tecnologia", q: "Qual combinação é comum para servir um site estático global com baixa latência e segurança?",
      o: ["Amazon S3 (hospedagem) + Amazon CloudFront (CDN).", "Amazon RDS + Amazon SQS.", "Amazon EMR + Amazon Redshift.", "AWS Config + AWS Artifact."], c: [0],
      e: "Hospedar os arquivos estáticos no S3 e distribuí-los via CloudFront entrega o site rapidamente em todo o mundo, com cache e HTTPS." },
  ];
  for (let i = 0; i < Q.length; i++) B.push(Q[i]);
})();
