"use strict";
// ============================================================
// CLImb — banco de questões CLF-C02 (parte 3)
// Domínio: Segurança e Conformidade (30% do exame).
// Modelo de responsabilidade compartilhada, IAM, serviços de segurança,
// criptografia, conformidade e governança.
// ============================================================
(function () {
  if (typeof window === "undefined") return;
  const B = (window.SIMULADOS_CLF = window.SIMULADOS_CLF || []);
  const Q = [
    { id: "clf-s01", d: "seguranca", q: "No modelo de responsabilidade compartilhada, a AWS é responsável pela segurança 'DA' nuvem. O que isso inclui?",
      o: ["Configurar Security Groups do cliente.", "A infraestrutura física, hardware, software base e rede que executam os serviços.", "Gerenciar permissões IAM dos usuários.", "Classificar os dados do cliente."], c: [1],
      e: "A AWS protege a infraestrutura subjacente (data centers, hardware, virtualização, rede). O cliente cuida da segurança 'NA' nuvem (dados, IAM, configurações)." },
    { id: "clf-s02", d: "seguranca", q: "No modelo de responsabilidade compartilhada, qual item é SEMPRE responsabilidade do cliente, independentemente do serviço?",
      o: ["A segurança física dos data centers.", "Os dados do cliente e o gerenciamento de identidades/acessos.", "O hipervisor.", "A manutenção do hardware de rede."], c: [1],
      e: "Independentemente do modelo de serviço, os dados do cliente e o controle de quem os acessa (IAM) são sempre responsabilidade do cliente." },
    { id: "clf-s03", d: "seguranca", q: "Para um serviço de IaaS como o Amazon EC2, quem é responsável por aplicar patches no sistema operacional convidado?",
      o: ["A AWS.", "O cliente.", "Ninguém, é automático.", "O fornecedor da AMI sempre."], c: [1],
      e: "No EC2 (IaaS), o cliente gerencia e aplica patches no SO convidado, aplicações e firewall (Security Groups). A AWS cuida da infraestrutura física e do hipervisor." },
    { id: "clf-s04", d: "seguranca", q: "Qual prática protege a conta de usuário root da AWS?",
      o: ["Usar o root para todas as tarefas diárias.", "Ativar MFA no root e usá-lo apenas para tarefas que exigem o root.", "Compartilhar as credenciais do root com a equipe.", "Criar chaves de acesso do root e colocá-las no código."], c: [1],
      e: "O root deve ter MFA ativo e ser usado só em tarefas específicas; o dia a dia deve ser feito com usuários/funções IAM de privilégio mínimo." },
    { id: "clf-s05", d: "seguranca", q: "O que é uma IAM Policy (política do IAM)?",
      o: ["Um documento (JSON) que define permissões de acesso a recursos da AWS.", "Um tipo de instância EC2.", "Uma chave de criptografia.", "Um relatório de custos."], c: [0],
      e: "Políticas do IAM são documentos JSON que concedem ou negam permissões a ações sobre recursos, anexáveis a usuários, grupos ou funções." },
    { id: "clf-s06", d: "seguranca", q: "Qual é a melhor forma de conceder permissões iguais a vários usuários do IAM de uma vez?",
      o: ["Anexar a política a cada usuário individualmente sempre.", "Adicionar os usuários a um grupo do IAM e anexar a política ao grupo.", "Compartilhar a senha do root.", "Usar uma única chave de acesso para todos."], c: [1],
      e: "Grupos do IAM permitem gerenciar permissões em lote: anexa-se a política ao grupo e todos os membros herdam as permissões." },
    { id: "clf-s07", d: "seguranca", q: "Quando uma IAM Role (função) deve ser usada em vez de um usuário do IAM?",
      o: ["Para conceder credenciais permanentes a uma pessoa.", "Para conceder permissões temporárias a serviços, aplicações ou acesso entre contas.", "Para armazenar arquivos.", "Para faturar recursos."], c: [1],
      e: "Funções fornecem credenciais temporárias assumidas por serviços (ex.: EC2), aplicações ou contas externas — sem chaves fixas." },
    { id: "clf-s08", d: "seguranca", q: "Qual serviço da AWS oferece proteção gerenciada contra ataques DDoS, com uma camada básica sem custo adicional?",
      o: ["AWS Shield", "AWS Config", "Amazon Macie", "AWS Artifact"], c: [0],
      e: "O AWS Shield Standard protege contra DDoS comuns sem custo extra; o Shield Advanced (pago) oferece proteção e suporte ampliados." },
    { id: "clf-s09", d: "seguranca", q: "Qual serviço usa machine learning para descobrir e proteger dados sensíveis (ex.: PII) armazenados no Amazon S3?",
      o: ["Amazon Macie", "Amazon Inspector", "AWS WAF", "AWS Shield"], c: [0],
      e: "O Amazon Macie usa ML para identificar e classificar dados sensíveis (como informações pessoais) em buckets do S3." },
    { id: "clf-s10", d: "seguranca", q: "Qual serviço detecta atividades maliciosas e comportamento anômalo analisando logs como CloudTrail, VPC Flow Logs e DNS?",
      o: ["Amazon GuardDuty", "AWS Config", "AWS Artifact", "Amazon QuickSight"], c: [0],
      e: "O Amazon GuardDuty é um serviço de detecção de ameaças que analisa continuamente logs para identificar comportamento suspeito." },
    { id: "clf-s11", d: "seguranca", q: "Qual serviço ajuda a investigar e analisar a causa-raiz de problemas de segurança correlacionando dados de várias fontes?",
      o: ["Amazon Detective", "AWS WAF", "AWS Shield", "Amazon CloudFront"], c: [0],
      e: "O Amazon Detective ajuda a analisar e visualizar dados de segurança para entender a causa e o escopo de incidentes." },
    { id: "clf-s12", d: "seguranca", q: "Qual serviço gerencia o ciclo de vida de certificados SSL/TLS para uso com serviços como o Elastic Load Balancing e o CloudFront?",
      o: ["AWS Certificate Manager (ACM)", "AWS KMS", "AWS Secrets Manager", "AWS IAM"], c: [0],
      e: "O ACM provisiona, gerencia e renova certificados TLS/SSL públicos gratuitamente para uso com serviços integrados da AWS." },
    { id: "clf-s13", d: "seguranca", q: "Qual serviço armazena e rotaciona automaticamente segredos como senhas de banco de dados e chaves de API?",
      o: ["AWS Secrets Manager", "AWS Config", "Amazon Inspector", "AWS Artifact"], c: [0],
      e: "O AWS Secrets Manager guarda segredos com segurança e pode rotacioná-los automaticamente, evitando credenciais fixas no código." },
    { id: "clf-s14", d: "seguranca", q: "Qual é a finalidade do AWS Key Management Service (KMS)?",
      o: ["Criar e gerenciar chaves criptográficas para proteger dados.", "Distribuir conteúdo em cache.", "Monitorar métricas de desempenho.", "Balancear carga de tráfego."], c: [0],
      e: "O KMS cria, controla e gerencia chaves de criptografia usadas para proteger dados em muitos serviços da AWS." },
    { id: "clf-s15", d: "seguranca", q: "Qual serviço da AWS protege aplicações web filtrando requisições maliciosas com base em regras (ex.: SQL injection, XSS)?",
      o: ["AWS WAF", "AWS Shield", "Amazon GuardDuty", "AWS Config"], c: [0],
      e: "O AWS WAF (Web Application Firewall) cria regras para permitir/bloquear requisições HTTP com base em padrões maliciosos." },
    { id: "clf-s16", d: "seguranca", q: "Onde estão disponíveis, sob demanda, os relatórios de conformidade da AWS (SOC, PCI DSS, ISO)?",
      o: ["AWS Artifact", "AWS Trusted Advisor", "Amazon Inspector", "AWS Budgets"], c: [0],
      e: "O AWS Artifact fornece acesso self-service a relatórios de auditoria e documentos de conformidade da AWS." },
    { id: "clf-s17", d: "seguranca", q: "Qual recurso adiciona uma segunda camada de verificação ao login, além da senha?",
      o: ["Multi-Factor Authentication (MFA)", "Security Group", "Network ACL", "Subnet pública"], c: [0],
      e: "O MFA exige um segundo fator (ex.: código de um app autenticador ou chave física) além da senha, dificultando acessos indevidos." },
    { id: "clf-s18", d: "seguranca", q: "Qual serviço permite gerenciar centralmente várias contas da AWS e aplicar políticas de controle (SCPs)?",
      o: ["AWS Organizations", "AWS IAM", "Amazon CloudWatch", "AWS Config"], c: [0],
      e: "O AWS Organizations gerencia múltiplas contas, agrupa-as em OUs e aplica Service Control Policies (SCPs) para limitar permissões em escala." },
    { id: "clf-s19", d: "seguranca", q: "O que são Service Control Policies (SCPs) no AWS Organizations?",
      o: ["Políticas que definem o teto máximo de permissões para contas-membro.", "Regras de firewall de rede.", "Certificados TLS.", "Planos de suporte."], c: [0],
      e: "SCPs definem o limite máximo de permissões que contas/OUs podem ter, mesmo que o IAM local conceda mais — funcionam como guarda-corpo (guardrail)." },
    { id: "clf-s20", d: "seguranca", q: "Qual serviço facilita configurar e governar um ambiente AWS com múltiplas contas seguindo as melhores práticas, com uma landing zone?",
      o: ["AWS Control Tower", "Amazon Inspector", "AWS Shield", "Amazon Athena"], c: [0],
      e: "O AWS Control Tower automatiza a criação de uma landing zone segura e multicontas, aplicando guardrails e melhores práticas." },
    { id: "clf-s21", d: "seguranca", q: "Em que situação o uso de um Network ACL difere de um Security Group?",
      o: ["NACL atua no nível da sub-rede e é sem estado (stateless); Security Group atua na instância e é com estado (stateful).", "São idênticos.", "Security Group atua na sub-rede.", "NACL criptografa dados."], c: [0],
      e: "O Security Group é stateful (resposta liberada automaticamente) e protege a instância; o NACL é stateless e filtra no nível da sub-rede, exigindo regras de entrada e saída." },
    { id: "clf-s22", d: "seguranca", q: "Qual serviço registra continuamente as configurações dos recursos e avalia se elas estão em conformidade com regras definidas?",
      o: ["AWS Config", "AWS CloudTrail", "Amazon Inspector", "AWS Shield"], c: [0],
      e: "O AWS Config rastreia o histórico de configuração dos recursos e dispara avaliações de conformidade contra regras (Config Rules)." },
    { id: "clf-s23", d: "seguranca", q: "Qual é a diferença principal entre AWS CloudTrail e AWS Config?",
      o: ["São a mesma coisa.", "CloudTrail registra QUEM fez qual chamada de API; Config registra COMO os recursos estão configurados ao longo do tempo.", "Config audita logins; CloudTrail mede custos.", "CloudTrail criptografa dados; Config faz backup."], c: [1],
      e: "CloudTrail = histórico de ações/API (quem, quando). Config = histórico de estado/configuração dos recursos e conformidade." },
    { id: "clf-s24", d: "seguranca", q: "Para garantir que dados em um bucket S3 sejam criptografados em repouso, o cliente pode:",
      o: ["Habilitar a criptografia do lado do servidor (SSE) no bucket.", "Desabilitar o versionamento.", "Tornar o bucket público.", "Remover as políticas de IAM."], c: [0],
      e: "A criptografia do lado do servidor (SSE-S3, SSE-KMS) protege os objetos em repouso automaticamente ao serem gravados no S3." },
    { id: "clf-s25", d: "seguranca", q: "Qual afirmação reflete o princípio do menor privilégio?",
      o: ["Conceder a todos acesso de administrador por conveniência.", "Conceder apenas as permissões necessárias para executar a tarefa.", "Compartilhar credenciais entre usuários.", "Desabilitar logs de auditoria."], c: [1],
      e: "O menor privilégio limita as permissões ao estritamente necessário, reduzindo a superfície de ataque e o impacto de credenciais comprometidas." },
    { id: "clf-s26", d: "seguranca", q: "Qual serviço fornece um relatório que lista todos os usuários e o status de suas credenciais (idade da senha, MFA, chaves de acesso)?",
      o: ["IAM Credential Report", "AWS Artifact", "Amazon Macie", "AWS Shield"], c: [0],
      e: "O IAM Credential Report exporta o status de credenciais de todos os usuários, útil para auditorias de segurança e conformidade." },
    { id: "clf-s27", d: "seguranca", q: "Qual serviço identifica recursos (ex.: buckets S3, funções IAM) que foram compartilhados com entidades externas à conta/organização?",
      o: ["IAM Access Analyzer", "AWS CloudTrail", "Amazon Inspector", "AWS Budgets"], c: [0],
      e: "O IAM Access Analyzer analisa políticas e identifica acessos concedidos a entidades externas, ajudando a evitar exposição indevida." },
    { id: "clf-s28", d: "seguranca", q: "Qual é uma boa prática para credenciais de acesso programático de longa duração?",
      o: ["Nunca rotacioná-las.", "Rotacioná-las regularmente e preferir funções/credenciais temporárias quando possível.", "Publicá-las em repositórios de código.", "Compartilhá-las por e-mail."], c: [1],
      e: "Chaves de acesso devem ser rotacionadas com frequência; melhor ainda é usar IAM Roles com credenciais temporárias, evitando chaves fixas." },
    { id: "clf-s29", d: "seguranca", q: "Qual serviço da AWS centraliza e prioriza alertas de segurança de vários serviços (GuardDuty, Inspector, Macie) em um só painel?",
      o: ["AWS Security Hub", "AWS Config", "AWS Artifact", "Amazon QuickSight"], c: [0],
      e: "O AWS Security Hub agrega e prioriza descobertas de segurança de vários serviços e parceiros, dando uma visão unificada da postura de segurança." },
    { id: "clf-s30", d: "seguranca", q: "No modelo de responsabilidade compartilhada, configurar a criptografia de dados e gerenciar as chaves é responsabilidade de quem?",
      o: ["Sempre da AWS.", "Do cliente (que decide criptografar e controla o acesso às chaves), com a AWS fornecendo as ferramentas (ex.: KMS).", "De ninguém.", "Do fornecedor de internet."], c: [1],
      e: "O cliente decide criptografar e gerencia o uso/permissões das chaves (mesmo com KMS), enquanto a AWS provê e protege o serviço de criptografia." },
    { id: "clf-s31", d: "seguranca", q: "Qual recurso de rede ajuda a isolar logicamente recursos em uma rede virtual privada na AWS?",
      o: ["Amazon VPC", "Amazon S3", "AWS IAM", "Amazon SNS"], c: [0],
      e: "A Amazon VPC fornece uma rede virtual isolada onde você controla sub-redes, roteamento e segurança dos recursos." },
    { id: "clf-s32", d: "seguranca", q: "Uma empresa precisa de uma maneira de aplicar firewall a nível de aplicação em escala, com regras gerenciadas contra ameaças comuns da web. Qual combinação ajuda?",
      o: ["AWS WAF com regras gerenciadas (AWS Managed Rules).", "Somente Security Groups.", "Apenas Network ACLs.", "AWS Budgets."], c: [0],
      e: "O AWS WAF com Managed Rules aplica conjuntos de regras mantidos pela AWS/parceiros contra ameaças comuns (OWASP Top 10, bots etc.)." },
    { id: "clf-s33", d: "seguranca", q: "Qual é o propósito de uma política baseada em recurso (resource-based policy), como uma bucket policy do S3?",
      o: ["Definir permissões anexadas diretamente ao recurso, indicando quem pode acessá-lo.", "Medir o custo do recurso.", "Criar uma instância EC2.", "Rotacionar chaves KMS."], c: [0],
      e: "Políticas baseadas em recurso (ex.: bucket policy) são anexadas ao próprio recurso e definem quais identidades podem realizar quais ações sobre ele." },
    { id: "clf-s34", d: "seguranca", q: "Qual prática reduz o risco de exposição acidental de um bucket S3 com dados sensíveis?",
      o: ["Habilitar o S3 Block Public Access e aplicar políticas restritivas.", "Tornar o bucket público para facilitar o acesso.", "Desativar a criptografia.", "Compartilhar a chave root."], c: [0],
      e: "O recurso S3 Block Public Access impede configurações que tornem o bucket público, evitando vazamentos por engano." },
    { id: "clf-s35", d: "seguranca", q: "O que é o AWS IAM Identity Center (antigo AWS SSO)?",
      o: ["Um serviço para gerenciar acesso de usuários (login único) a várias contas e aplicações da AWS.", "Um serviço de armazenamento.", "Uma ferramenta de faturamento.", "Um banco de dados NoSQL."], c: [0],
      e: "O IAM Identity Center oferece logon único (SSO) e gestão centralizada de acesso de usuários a múltiplas contas AWS e aplicações." },
    { id: "clf-s36", d: "seguranca", q: "Qual serviço avalia automaticamente instâncias EC2 e imagens de contêiner em busca de vulnerabilidades conhecidas (CVEs)?",
      o: ["Amazon Inspector", "Amazon Macie", "AWS Shield", "AWS Artifact"], c: [0],
      e: "O Amazon Inspector verifica continuamente cargas de trabalho (EC2, ECR, Lambda) contra vulnerabilidades conhecidas e exposição de rede." },
    { id: "clf-s37", d: "seguranca", q: "Em conformidade, o que significa dizer que a AWS é responsável pela segurança 'DA' nuvem e o cliente pela segurança 'NA' nuvem?",
      o: ["A AWS protege a infraestrutura; o cliente protege o que coloca nela (dados, acessos, configurações).", "O cliente protege os data centers da AWS.", "A AWS gerencia as senhas dos usuários do cliente.", "Não há divisão de responsabilidade."], c: [0],
      e: "Esse é o resumo do modelo de responsabilidade compartilhada: AWS = infraestrutura; cliente = dados, identidades e configurações." },
    { id: "clf-s38", d: "seguranca", q: "Qual ação melhora a segurança de credenciais de um usuário do IAM que precisa de acesso ao console?",
      o: ["Definir uma política de senhas forte e exigir MFA.", "Remover a senha e compartilhar a do root.", "Conceder acesso de administrador total.", "Desativar o registro de atividades."], c: [0],
      e: "Política de senhas forte + MFA reduz muito o risco de comprometimento de contas de usuários do IAM." },
    { id: "clf-s39", d: "seguranca", q: "Qual serviço pode ser usado para criar uma trilha de auditoria imutável das chamadas de API para fins de conformidade?",
      o: ["AWS CloudTrail (com integridade de log/validação)", "Amazon S3 Glacier", "AWS Budgets", "Amazon Comprehend"], c: [0],
      e: "O CloudTrail registra chamadas de API e oferece validação de integridade dos arquivos de log, apoiando requisitos de auditoria e conformidade." },
    { id: "clf-s40", d: "seguranca", q: "Para proteger dados em trânsito entre um cliente e um serviço da AWS, qual mecanismo é usado?",
      o: ["Criptografia TLS/SSL (HTTPS).", "Versionamento do S3.", "Tags de custo.", "Auto Scaling."], c: [0],
      e: "Dados em trânsito são protegidos com TLS/SSL (HTTPS), garantindo confidencialidade e integridade durante a transmissão." },
    { id: "clf-s41", d: "seguranca", q: "Qual é uma responsabilidade do cliente ao usar o Amazon S3?",
      o: ["Manter o hardware dos servidores de armazenamento.", "Configurar permissões de acesso, criptografia e políticas do bucket.", "Substituir discos com defeito.", "Gerenciar a rede física do data center."], c: [1],
      e: "No S3, o cliente controla o acesso (IAM/bucket policy), a criptografia e a classificação dos dados; a AWS cuida da infraestrutura física." },
    { id: "clf-s42", d: "seguranca", q: "Qual destes serviços ajuda a cumprir requisitos que exigem o uso de módulos de segurança de hardware dedicados (HSM)?",
      o: ["AWS CloudHSM", "Amazon S3", "AWS Budgets", "Amazon Athena"], c: [0],
      e: "O AWS CloudHSM fornece HSMs dedicados e gerenciados para casos que exigem controle exclusivo e conformidade rígida sobre chaves criptográficas." },
    { id: "clf-s43", d: "seguranca", q: "Por que NÃO se deve embutir chaves de acesso diretamente no código de uma aplicação que roda no EC2?",
      o: ["Porque torna o código mais rápido.", "Porque é um risco de segurança; o correto é usar uma IAM Role anexada à instância.", "Porque chaves não funcionam no EC2.", "Porque aumenta o custo."], c: [1],
      e: "Chaves no código podem vazar facilmente. A prática segura é anexar uma IAM Role à instância, que recebe credenciais temporárias automaticamente." },
    { id: "clf-s44", d: "seguranca", q: "Qual serviço de borda ajuda a mitigar ataques DDoS ao distribuir e absorver tráfego globalmente, além de servir conteúdo em cache?",
      o: ["Amazon CloudFront", "Amazon RDS", "AWS Config", "Amazon Athena"], c: [0],
      e: "O CloudFront, por estar na borda e integrar-se ao Shield e ao WAF, ajuda a absorver e filtrar tráfego malicioso, mitigando DDoS." },
    { id: "clf-s45", d: "seguranca", q: "Qual recurso permite definir 'guardrails' que impedem contas de uma organização de usar serviços ou Regiões não aprovados?",
      o: ["Service Control Policies (SCPs) no AWS Organizations", "Security Groups", "Cost Explorer", "Amazon SNS"], c: [0],
      e: "SCPs aplicam limites de permissão em escala, podendo bloquear serviços/Regiões para todas as contas afetadas, funcionando como guardrails." },
    { id: "clf-s46", d: "seguranca", q: "Qual afirmação sobre o usuário root da conta AWS é verdadeira?",
      o: ["Deve ser usado para o trabalho do dia a dia.", "Tem acesso total e irrestrito; seu uso deve ser minimizado e protegido com MFA.", "Não pode ter MFA.", "É gratuito apenas no plano Enterprise."], c: [1],
      e: "O root tem poder total sobre a conta; por isso seu uso deve ser raro, protegido por MFA e as credenciais guardadas com segurança." },
    { id: "clf-s47", d: "seguranca", q: "Uma empresa quer garantir que apenas tráfego de uma faixa de IP específica acesse uma aplicação web. Qual recurso pode ajudar a aplicar essa regra?",
      o: ["Regras de IP no AWS WAF e/ou Security Groups.", "Cost Explorer.", "AWS Artifact.", "Amazon Macie."], c: [0],
      e: "Security Groups controlam acesso por IP/porta à instância; o WAF pode criar regras baseadas em IP no nível da aplicação web." },
    { id: "clf-s48", d: "seguranca", q: "O que descreve melhor 'defesa em profundidade' (defense in depth)?",
      o: ["Confiar em uma única camada de segurança.", "Aplicar múltiplas camadas de segurança (rede, identidade, criptografia, monitoramento).", "Desativar logs.", "Usar apenas senhas."], c: [1],
      e: "Defesa em profundidade combina várias camadas de proteção, de modo que a falha de uma não comprometa todo o sistema." },
    { id: "clf-s49", d: "seguranca", q: "Qual serviço pode notificar e automatizar respostas quando uma regra de conformidade de configuração é violada?",
      o: ["AWS Config (com regras e remediação)", "Amazon S3", "AWS Pricing Calculator", "Amazon QuickSight"], c: [0],
      e: "O AWS Config avalia recursos contra regras e pode acionar remediações automáticas ou notificações quando algo sai de conformidade." },
    { id: "clf-s50", d: "seguranca", q: "Qual prática ajuda a auditar e rastrear ações administrativas em uma conta para investigação de incidentes?",
      o: ["Desativar o CloudTrail.", "Manter o CloudTrail habilitado registrando eventos em todas as Regiões.", "Apagar logs diariamente.", "Usar apenas o root."], c: [1],
      e: "Manter o CloudTrail ativo (idealmente multi-Região e com logs protegidos) garante uma trilha de auditoria para investigações de segurança." },
    { id: "clf-s51", d: "seguranca", q: "Qual é a responsabilidade do cliente em relação à segurança de uma aplicação serverless no AWS Lambda?",
      o: ["Aplicar patches no sistema operacional do Lambda.", "Escrever código seguro e configurar permissões IAM adequadas para a função.", "Gerenciar o hardware dos servidores.", "Manter a rede física."], c: [1],
      e: "No Lambda, a AWS gerencia o ambiente de execução; o cliente é responsável pelo código seguro e pelas permissões (função de execução) com menor privilégio." },
    { id: "clf-s52", d: "seguranca", q: "Qual recurso permite conceder acesso temporário e federado à AWS para usuários autenticados por um provedor de identidade externo (ex.: corporativo)?",
      o: ["Federação de identidades com IAM Roles / IAM Identity Center", "Chaves de acesso permanentes no código", "Security Groups", "Cost Allocation Tags"], c: [0],
      e: "A federação permite que usuários de um IdP externo assumam IAM Roles e obtenham credenciais temporárias, sem criar usuários IAM individuais." },
    { id: "clf-s53", d: "seguranca", q: "Qual é uma forma recomendada de proteger dados altamente sensíveis quanto ao acesso entre equipes?",
      o: ["Aplicar políticas de menor privilégio e separar funções por necessidade de acesso.", "Dar admin a todos.", "Remover a criptografia.", "Compartilhar credenciais."], c: [0],
      e: "Separar responsabilidades e conceder o menor privilégio garante que cada equipe acesse apenas o necessário, reduzindo riscos." },
    { id: "clf-s54", d: "seguranca", q: "Qual serviço você usaria para descobrir se há dados pessoais (PII) expostos inadvertidamente em buckets S3?",
      o: ["Amazon Macie", "Amazon RDS", "AWS Budgets", "Amazon SNS"], c: [0],
      e: "O Amazon Macie classifica e alerta sobre dados sensíveis (como PII) no S3, ajudando a evitar exposição indevida." },
    { id: "clf-s55", d: "seguranca", q: "Sobre conformidade, qual afirmação é correta?",
      o: ["A AWS é responsável por toda a conformidade do cliente automaticamente.", "A conformidade é compartilhada: a AWS certifica a infraestrutura e o cliente é responsável pelo uso em conformidade dos serviços.", "Conformidade não se aplica à nuvem.", "Só o plano Enterprise tem conformidade."], c: [1],
      e: "A AWS mantém certificações da infraestrutura (herdadas pelo cliente), mas o cliente deve configurar e operar seus recursos em conformidade com as exigências do seu setor." },
    { id: "clf-s56", d: "seguranca", q: "Qual é o benefício de usar credenciais temporárias (STS) em vez de chaves de acesso de longa duração?",
      o: ["Elas nunca expiram.", "Elas expiram automaticamente, reduzindo o risco se forem expostas.", "Elas são mais lentas.", "Elas exigem o plano Business."], c: [1],
      e: "Credenciais temporárias do AWS STS têm vida curta e expiram sozinhas, limitando o impacto caso sejam comprometidas." },
    { id: "clf-s57", d: "seguranca", q: "Uma organização precisa impedir que qualquer conta-membro desabilite o CloudTrail. Qual recurso aplica esse controle de cima para baixo?",
      o: ["Service Control Policy (SCP) no AWS Organizations", "Security Group", "Bucket policy", "Cost Explorer"], c: [0],
      e: "Uma SCP pode negar a ação de desabilitar o CloudTrail para todas as contas afetadas, garantindo a auditoria de forma centralizada." },
    { id: "clf-s58", d: "seguranca", q: "Qual serviço da AWS oferece firewall de rede gerenciado e com estado para proteger o tráfego dentro de uma VPC?",
      o: ["AWS Network Firewall", "Amazon Macie", "AWS Artifact", "Amazon QuickSight"], c: [0],
      e: "O AWS Network Firewall fornece filtragem de tráfego com estado e regras de IPS/IDS no nível da VPC, complementando Security Groups e NACLs." },
    { id: "clf-s59", d: "seguranca", q: "Qual é a melhor descrição de 'autenticação' versus 'autorização'?",
      o: ["São a mesma coisa.", "Autenticação confirma quem você é; autorização define o que você pode fazer.", "Autorização confirma a identidade; autenticação define permissões.", "Ambas tratam apenas de criptografia."], c: [1],
      e: "Autenticação = provar a identidade (login/MFA). Autorização = quais ações/recursos essa identidade pode acessar (políticas do IAM)." },
    { id: "clf-s60", d: "seguranca", q: "Qual prática ajuda a garantir que uma instância EC2 em uma sub-rede privada não seja acessível diretamente da internet?",
      o: ["Colocá-la em uma sub-rede sem rota para um Internet Gateway e restringir o Security Group.", "Atribuir um IP público e abrir todas as portas.", "Desativar o IAM.", "Tornar o bucket S3 público."], c: [0],
      e: "Sem rota para um IGW (sub-rede privada) e com Security Group restritivo, a instância não recebe tráfego direto da internet; o acesso de saída pode passar por um NAT." },
  ];
  for (let i = 0; i < Q.length; i++) B.push(Q[i]);
})();
