"use strict";
// ============================================================
// CLImb — banco de questões CLF-C02 (parte 5, complemento)
// Mistura dos quatro domínios para o banco passar de 300 questões,
// mantendo a proporção próxima aos pesos do exame.
// ============================================================
(function () {
  if (typeof window === "undefined") return;
  const B = (window.SIMULADOS_CLF = window.SIMULADOS_CLF || []);
  const Q = [
    // CONCEITOS
    { id: "clf-x01", d: "conceitos", q: "Uma empresa quer reduzir o tempo entre ter uma ideia e colocá-la em produção. Qual benefício da nuvem isso representa?",
      o: ["Agilidade e velocidade na entrega.", "Maior CapEx.", "Capacidade fixa.", "Eliminação da segurança."], c: [0],
      e: "A nuvem encurta o ciclo de ideia→produção provisionando recursos em minutos, aumentando a agilidade e a velocidade de inovação." },
    { id: "clf-x02", d: "conceitos", q: "Qual prática de design do Well-Architected ajuda a lidar com mudanças de demanda sem intervenção manual?",
      o: ["Escalar automaticamente (elasticidade/auto scaling).", "Comprar servidores fixos.", "Fazer mudanças grandes e raras.", "Centralizar tudo em uma única instância."], c: [0],
      e: "Escalar automaticamente conforme a demanda mantém desempenho e custo equilibrados, sem intervenção manual." },
    { id: "clf-x03", d: "conceitos", q: "O que melhor descreve um modelo de implantação em nuvem (cloud-native)?",
      o: ["Toda a aplicação é executada e construída sobre serviços da nuvem.", "Tudo roda em servidores locais.", "Metade local, metade na nuvem.", "Sem uso de computação."], c: [0],
      e: "No modelo totalmente em nuvem, a aplicação é construída e executada usando serviços de nuvem, sem depender de infraestrutura local." },
    { id: "clf-x04", d: "conceitos", q: "Qual perspectiva do AWS CAF foca em cultura organizacional, liderança e desenvolvimento de habilidades?",
      o: ["Pessoas (People)", "Plataforma (Platform)", "Operações (Operations)", "Segurança (Security)"], c: [0],
      e: "A perspectiva de Pessoas trata de evolução cultural, liderança transformacional e capacitação (cloud fluency) das equipes." },
    { id: "clf-x05", d: "conceitos", q: "Por que distribuir uma aplicação por múltiplas Zonas de Disponibilidade aumenta a confiabilidade?",
      o: ["Porque as AZs são isoladas; a falha de uma não derruba as outras.", "Porque reduz o custo a zero.", "Porque elimina a necessidade de backups.", "Porque dobra a latência."], c: [0],
      e: "As AZs têm infraestrutura independente; espalhar a carga entre elas garante continuidade se uma sofrer falha." },
    { id: "clf-x06", d: "conceitos", q: "Qual afirmação sobre economia de escala da AWS é correta?",
      o: ["Quanto mais clientes a AWS atende, mais ela pode reduzir custos e repassar preços menores.", "Os preços só aumentam com o tempo.", "A escala não afeta o preço.", "Só grandes empresas pagam menos."], c: [0],
      e: "O volume agregado de uso permite à AWS obter eficiências e repassar reduções de preço a todos os clientes." },
    { id: "clf-x07", d: "conceitos", q: "Uma carga de trabalho precisa estar sempre disponível, mesmo durante manutenção. Qual abordagem ajuda?",
      o: ["Redundância em várias AZs com balanceamento de carga.", "Uma única instância sem backup.", "Desligar tudo durante a manutenção.", "Usar apenas armazenamento local."], c: [0],
      e: "Redundância entre AZs e balanceamento permitem manutenção e falhas sem interromper o serviço aos usuários." },

    // SEGURANÇA
    { id: "clf-x08", d: "seguranca", q: "Qual é uma forma recomendada de organizar permissões quando vários times precisam de acessos diferentes?",
      o: ["Criar grupos do IAM por função e anexar políticas de menor privilégio a cada grupo.", "Dar admin a todos.", "Usar o root para todos os times.", "Compartilhar uma única chave de acesso."], c: [0],
      e: "Grupos por função com políticas de menor privilégio facilitam a gestão e reduzem riscos de acesso excessivo." },
    { id: "clf-x09", d: "seguranca", q: "Qual serviço deve ser habilitado para registrar todas as chamadas de API e apoiar investigações forenses?",
      o: ["AWS CloudTrail", "Amazon QuickSight", "AWS Budgets", "Amazon Polly"], c: [0],
      e: "O CloudTrail mantém o histórico de chamadas de API, essencial para auditoria e investigação de incidentes." },
    { id: "clf-x10", d: "seguranca", q: "Qual recurso protege contra a exclusão acidental de objetos críticos em um bucket S3 versionado?",
      o: ["MFA Delete", "Static website hosting", "Transfer Acceleration", "Requester Pays"], c: [0],
      e: "O MFA Delete exige autenticação multifator para excluir versões de objetos ou desativar o versionamento, prevenindo exclusões acidentais ou maliciosas." },
    { id: "clf-x11", d: "seguranca", q: "Uma empresa precisa garantir que dados em um banco RDS estejam criptografados em repouso. Como isso é feito?",
      o: ["Habilitando a criptografia do RDS (integrada ao AWS KMS) na criação da instância.", "Tornando o banco público.", "Desativando backups.", "Removendo o Security Group."], c: [0],
      e: "O RDS oferece criptografia em repouso usando chaves do KMS, protegendo dados, snapshots e réplicas." },
    { id: "clf-x12", d: "seguranca", q: "Qual prática melhora a postura de segurança ao conceder acesso a uma aplicação de terceiros à sua conta?",
      o: ["Usar uma IAM Role com permissões mínimas e credenciais temporárias.", "Entregar as chaves do root.", "Criar um usuário admin com chave fixa.", "Desativar o CloudTrail."], c: [0],
      e: "Uma IAM Role com menor privilégio e credenciais temporárias limita o que o terceiro pode fazer e por quanto tempo." },
    { id: "clf-x13", d: "seguranca", q: "Qual serviço ajuda a manter contas múltiplas em conformidade aplicando regras e remediações de configuração automaticamente?",
      o: ["AWS Config (com Conformance Packs)", "Amazon CloudFront", "Amazon SQS", "Amazon Lightsail"], c: [0],
      e: "O AWS Config avalia configurações contra regras e pode remediar automaticamente, inclusive de forma agregada em organizações." },
    { id: "clf-x14", d: "seguranca", q: "Qual afirmação sobre o modelo de responsabilidade compartilhada e patches está correta?",
      o: ["Em serviços gerenciados (ex.: DynamoDB, S3), a AWS aplica os patches da infraestrutura; em IaaS (EC2), o cliente aplica os patches do SO convidado.", "O cliente sempre aplica todos os patches.", "A AWS aplica todos os patches em todos os serviços.", "Patches não são necessários na nuvem."], c: [0],
      e: "Quanto mais gerenciado o serviço, mais a AWS assume os patches; no EC2 (IaaS), o SO convidado é responsabilidade do cliente." },
    { id: "clf-x15", d: "seguranca", q: "Qual recurso permite revisar se as políticas concedem acesso mais amplo do que o necessário, ajudando a aplicar o menor privilégio?",
      o: ["IAM Access Analyzer (gerador/validação de políticas)", "Amazon Athena", "AWS Budgets", "Amazon Kinesis"], c: [0],
      e: "O IAM Access Analyzer ajuda a validar políticas e a gerar políticas baseadas no acesso realmente utilizado, reduzindo permissões excessivas." },
    { id: "clf-x16", d: "seguranca", q: "Qual é a melhor maneira de proteger a conta contra acesso indevido caso a senha de um usuário vaze?",
      o: ["Exigir MFA para o login.", "Desativar logs.", "Usar a mesma senha para todos.", "Conceder admin a todos."], c: [0],
      e: "O MFA adiciona um segundo fator, de modo que uma senha vazada sozinha não basta para acessar a conta." },

    // TECNOLOGIA
    { id: "clf-x17", d: "tecnologia", q: "Uma aplicação precisa desacoplar o recebimento de pedidos do processamento, absorvendo picos. Qual serviço usar?",
      o: ["Amazon SQS (fila de mensagens).", "Amazon RDS.", "Amazon CloudFront.", "AWS Artifact."], c: [0],
      e: "Uma fila SQS armazena os pedidos e permite que o processamento ocorra no próprio ritmo, absorvendo picos e desacoplando os componentes." },
    { id: "clf-x18", d: "tecnologia", q: "Qual serviço escolher para um site dinâmico que precisa de servidores web escaláveis com controle do ambiente?",
      o: ["Amazon EC2 com Auto Scaling e Load Balancer.", "Amazon S3 sozinho.", "Amazon Glacier.", "AWS Artifact."], c: [0],
      e: "Sites dinâmicos com controle do ambiente costumam usar EC2 + Auto Scaling + ELB; o S3 sozinho serve apenas conteúdo estático." },
    { id: "clf-x19", d: "tecnologia", q: "Qual serviço é ideal para armazenar sessões de usuário e dados de cache com latência muito baixa?",
      o: ["Amazon ElastiCache.", "Amazon Glacier.", "Amazon Athena.", "AWS Config."], c: [0],
      e: "O ElastiCache (Redis/Memcached) mantém dados em memória, ideal para sessões e cache com latência de microssegundos a milissegundos." },
    { id: "clf-x20", d: "tecnologia", q: "Qual serviço gerenciado é mais adequado para uma API serverless de back-end?",
      o: ["Amazon API Gateway + AWS Lambda.", "Amazon EC2 + EBS.", "Amazon Redshift.", "Amazon S3 Glacier."], c: [0],
      e: "API Gateway expõe a API e o Lambda executa a lógica sem servidores, formando um back-end totalmente serverless e escalável." },
    { id: "clf-x21", d: "tecnologia", q: "Qual serviço você usaria para criar toda a infraestrutura de forma repetível em vários ambientes (dev, teste, prod)?",
      o: ["AWS CloudFormation.", "Amazon QuickSight.", "Amazon Comprehend.", "Amazon Polly."], c: [0],
      e: "O CloudFormation define a infraestrutura como código, permitindo recriar ambientes idênticos de forma consistente e versionada." },
    { id: "clf-x22", d: "tecnologia", q: "Qual serviço monitora a utilização de CPU de instâncias EC2 e pode disparar um alarme?",
      o: ["Amazon CloudWatch.", "AWS Artifact.", "Amazon Macie.", "AWS Budgets."], c: [0],
      e: "O CloudWatch coleta métricas (como CPU) e permite criar alarmes que notificam ou acionam ações automáticas." },
    { id: "clf-x23", d: "tecnologia", q: "Qual serviço é mais indicado para análise SQL ad hoc de logs armazenados no S3, sem montar infraestrutura?",
      o: ["Amazon Athena.", "Amazon EC2.", "Amazon EBS.", "AWS Direct Connect."], c: [0],
      e: "O Athena consulta dados no S3 com SQL de forma serverless, perfeito para análises pontuais sem provisionar servidores." },
    { id: "clf-x24", d: "tecnologia", q: "Uma empresa precisa de armazenamento compartilhado por dezenas de instâncias Linux simultaneamente. Qual serviço atende?",
      o: ["Amazon EFS.", "Amazon EBS (volume único).", "Amazon S3 Glacier.", "Amazon Redshift."], c: [0],
      e: "O EFS é um sistema de arquivos compartilhado e elástico, montável por muitas instâncias ao mesmo tempo; o EBS comum é anexado a uma instância por vez." },
    { id: "clf-x25", d: "tecnologia", q: "Qual serviço facilita entregar conteúdo estático e dinâmico globalmente com cache na borda e integração a WAF/Shield?",
      o: ["Amazon CloudFront.", "Amazon RDS.", "Amazon SQS.", "AWS Config."], c: [0],
      e: "O CloudFront entrega conteúdo a partir das Edge Locations com cache, e integra-se a WAF e Shield para segurança." },
    { id: "clf-x26", d: "tecnologia", q: "Qual serverless é melhor para um banco NoSQL com escala automática e cobrança por requisição?",
      o: ["Amazon DynamoDB (on-demand).", "Amazon RDS Multi-AZ.", "Amazon Redshift.", "Amazon EC2."], c: [0],
      e: "O DynamoDB on-demand escala automaticamente e cobra por requisição, sem gerenciamento de capacidade." },

    // COBRANÇA
    { id: "clf-x27", d: "cobranca", q: "Uma empresa tem uso de computação previsível e quer o melhor desconto com flexibilidade entre famílias de instância e Regiões. O que escolher?",
      o: ["Compute Savings Plan.", "On-Demand.", "Spot.", "Dedicated Hosts sob demanda."], c: [0],
      e: "O Compute Savings Plan oferece grande desconto com a maior flexibilidade (qualquer família/Região, além de Fargate e Lambda)." },
    { id: "clf-x28", d: "cobranca", q: "Qual ferramenta é melhor para investigar quais serviços causaram um aumento inesperado na fatura do mês passado?",
      o: ["AWS Cost Explorer.", "AWS Pricing Calculator.", "AWS Artifact.", "Amazon Inspector."], c: [0],
      e: "O Cost Explorer analisa o histórico de custos com filtros e gráficos, ideal para descobrir a origem de variações na fatura." },
    { id: "clf-x29", d: "cobranca", q: "Qual plano de suporte é o mínimo recomendado para uma empresa com cargas de PRODUÇÃO que precisam de suporte 24x7 por telefone?",
      o: ["Business.", "Basic.", "Developer.", "Nenhum oferece telefone."], c: [0],
      e: "O plano Business oferece suporte técnico 24x7 por telefone, chat e e-mail, adequado para cargas de produção." },
    { id: "clf-x30", d: "cobranca", q: "Uma empresa quer ser alertada quando o uso do Free Tier estiver perto de gerar cobrança. Qual recurso usar?",
      o: ["Alertas de uso do AWS Free Tier / AWS Budgets.", "Amazon Rekognition.", "AWS Shield.", "Amazon Neptune."], c: [0],
      e: "Os alertas de uso do Free Tier e o AWS Budgets avisam quando o consumo se aproxima dos limites gratuitos, evitando surpresas na fatura." },
  ];
  for (let i = 0; i < Q.length; i++) B.push(Q[i]);
})();
