"use strict";
// ============================================================
// CLImb — banco de questões CLF-C02 (parte 2)
// Domínios: Conceitos de Nuvem + Cobrança, Preços e Suporte.
// Estilo CLF-C02, baseado em fatos consolidados da AWS (Well-Architected,
// CAF, infraestrutura global, modelos de preço, planos de suporte).
// ============================================================
(function () {
  if (typeof window === "undefined") return;
  const B = (window.SIMULADOS_CLF = window.SIMULADOS_CLF || []);
  const Q = [
    // ---------- CONCEITOS DE NUVEM ----------
    { id: "clf-c01", d: "conceitos", q: "Qual benefício da computação em nuvem permite trocar despesas de capital (CapEx) por despesas variáveis (OpEx)?",
      o: ["Pagar adiantado por servidores para o ano todo.", "Pagar apenas pelos recursos que você consome.", "Comprar hardware com desconto por volume.", "Eliminar todos os custos de TI."], c: [1],
      e: "Na nuvem você paga conforme usa (pay-as-you-go), trocando grandes investimentos antecipados em hardware por um custo variável proporcional ao consumo." },
    { id: "clf-c02", d: "conceitos", q: "Uma empresa quer parar de adivinhar a capacidade necessária de seus servidores. Qual benefício da nuvem resolve isso?",
      o: ["Economia de escala.", "Parar de adivinhar a capacidade (escalar conforme a demanda).", "Trocar CapEx por OpEx.", "Tornar-se global em minutos."], c: [1],
      e: "Com a nuvem você provisiona o que precisa e escala para cima ou para baixo conforme a demanda real, sem superdimensionar nem ficar sem capacidade." },
    { id: "clf-c03", d: "conceitos", q: "Qual benefício da nuvem é demonstrado ao implantar uma aplicação em várias regiões do mundo em poucos cliques?",
      o: ["Alta disponibilidade.", "Tornar-se global em minutos.", "Elasticidade.", "Economia de escala."], c: [1],
      e: "'Go global in minutes': a infraestrutura global da AWS permite implantar perto dos usuários em qualquer região rapidamente, reduzindo latência." },
    { id: "clf-c04", d: "conceitos", q: "O que é uma Zona de Disponibilidade (Availability Zone) na AWS?",
      o: ["Um data center único e isolado no mundo.", "Um ou mais data centers isolados dentro de uma Região.", "Um ponto de presença para cache do CloudFront.", "Uma conta da AWS separada."], c: [1],
      e: "Uma AZ é composta por um ou mais data centers com energia, rede e refrigeração independentes, isolados dentro de uma Região para tolerância a falhas." },
    { id: "clf-c05", d: "conceitos", q: "Para projetar uma aplicação altamente disponível, qual prática é recomendada?",
      o: ["Concentrar todos os recursos em uma única Zona de Disponibilidade.", "Distribuir os recursos por várias Zonas de Disponibilidade.", "Usar apenas uma instância grande.", "Desativar backups para economizar."], c: [1],
      e: "Distribuir a carga por múltiplas AZs garante que, se uma falhar, a aplicação continua disponível nas outras." },
    { id: "clf-c06", d: "conceitos", q: "O que é uma Região da AWS?",
      o: ["Um único servidor físico.", "Uma área geográfica com várias Zonas de Disponibilidade.", "Um serviço de DNS global.", "Um tipo de instância EC2."], c: [1],
      e: "Uma Região é uma localização geográfica que contém várias Zonas de Disponibilidade isoladas e fisicamente separadas." },
    { id: "clf-c07", d: "conceitos", q: "O que são Edge Locations (locais de borda) na infraestrutura da AWS?",
      o: ["Data centers para hospedar bancos de dados.", "Pontos de presença usados para entregar conteúdo com baixa latência (CloudFront).", "Zonas de Disponibilidade extras.", "Servidores de e-mail."], c: [1],
      e: "Edge Locations são pontos de presença usados por serviços como o CloudFront para armazenar conteúdo em cache perto dos usuários, reduzindo a latência." },
    { id: "clf-c08", d: "conceitos", q: "Quais são os seis pilares do AWS Well-Architected Framework?",
      o: ["Computação, Rede, Armazenamento, Banco, Análise e Segurança.", "Excelência Operacional, Segurança, Confiabilidade, Eficiência de Desempenho, Otimização de Custos e Sustentabilidade.", "Negócios, Pessoas, Governança, Plataforma, Segurança e Operações.", "Rehost, Replatform, Repurchase, Refactor, Retire e Retain."], c: [1],
      e: "Os seis pilares do Well-Architected são: Excelência Operacional, Segurança, Confiabilidade, Eficiência de Desempenho, Otimização de Custos e Sustentabilidade. (Negócios/Pessoas/... são as perspectivas do CAF.)" },
    { id: "clf-c09", d: "conceitos", q: "Qual pilar do Well-Architected Framework se concentra em usar recursos de computação de forma eficiente e manter essa eficiência conforme a demanda muda?",
      o: ["Confiabilidade", "Eficiência de Desempenho", "Otimização de Custos", "Segurança"], c: [1],
      e: "O pilar de Eficiência de Desempenho trata de usar os recursos de TI com eficiência e adaptar a escolha conforme a tecnologia e a demanda evoluem." },
    { id: "clf-c10", d: "conceitos", q: "Qual pilar do Well-Architected Framework ajuda a evitar gastos desnecessários e a escolher os recursos do tamanho certo?",
      o: ["Otimização de Custos", "Excelência Operacional", "Sustentabilidade", "Confiabilidade"], c: [0],
      e: "O pilar de Otimização de Custos foca em entregar valor pelo menor preço, evitando recursos superdimensionados e gastos desnecessários." },
    { id: "clf-c11", d: "conceitos", q: "Qual pilar do Well-Architected Framework foi adicionado para minimizar o impacto ambiental das cargas de trabalho na nuvem?",
      o: ["Confiabilidade", "Sustentabilidade", "Eficiência de Desempenho", "Segurança"], c: [1],
      e: "O pilar de Sustentabilidade trata de reduzir o impacto ambiental, como consumo de energia e uso eficiente de recursos." },
    { id: "clf-c12", d: "conceitos", q: "Qual é um princípio de design recomendado pelo Well-Architected Framework relacionado a capacidade?",
      o: ["Adivinhar a capacidade necessária e provisionar em excesso.", "Parar de adivinhar a capacidade.", "Usar sempre o maior tipo de instância disponível.", "Fazer mudanças grandes e raras."], c: [1],
      e: "'Stop guessing capacity': com a nuvem você dimensiona conforme a demanda real e usa auto scaling, em vez de adivinhar e superdimensionar." },
    { id: "clf-c13", d: "conceitos", q: "Quais são as seis perspectivas do AWS Cloud Adoption Framework (CAF)?",
      o: ["Negócios, Pessoas, Governança, Plataforma, Segurança e Operações.", "Computação, Armazenamento, Banco, Rede, Análise e ML.", "Os seis pilares do Well-Architected.", "Rehost, Replatform, Repurchase, Refactor, Retire e Retain."], c: [0],
      e: "As seis perspectivas do CAF são: Negócios, Pessoas e Governança (foco em pessoas/processos) e Plataforma, Segurança e Operações (foco em tecnologia)." },
    { id: "clf-c14", d: "conceitos", q: "A perspectiva de Negócios (Business) do AWS CAF tem como foco principal:",
      o: ["Configurar redes e servidores.", "Garantir que os investimentos em nuvem acelerem os objetivos de negócio.", "Aplicar patches de segurança.", "Escrever código de aplicações."], c: [1],
      e: "A perspectiva de Negócios garante que a estratégia de nuvem esteja alinhada e gere resultados de negócio mensuráveis." },
    { id: "clf-c15", d: "conceitos", q: "Qual modelo de implantação combina infraestrutura local (on-premises) com a nuvem AWS?",
      o: ["Modelo totalmente em nuvem (cloud-native).", "Modelo híbrido (hybrid).", "Modelo on-premises.", "Modelo multirregional."], c: [1],
      e: "O modelo híbrido integra recursos locais com a nuvem, comum durante migrações ou quando há exigências de manter parte da carga no local." },
    { id: "clf-c16", d: "conceitos", q: "O que descreve melhor a 'elasticidade' na nuvem?",
      o: ["A capacidade de continuar funcionando após falhas.", "Adicionar e remover recursos automaticamente conforme a demanda.", "Distribuir conteúdo globalmente.", "Criptografar dados em repouso."], c: [1],
      e: "Elasticidade é aumentar ou reduzir os recursos automaticamente conforme a carga sobe ou desce, pagando só pelo que usa." },
    { id: "clf-c17", d: "conceitos", q: "Qual a diferença entre escalabilidade e elasticidade?",
      o: ["São exatamente a mesma coisa.", "Escalabilidade é a capacidade de crescer; elasticidade é ajustar para cima e para baixo automaticamente conforme a demanda.", "Elasticidade só funciona em bancos de dados.", "Escalabilidade só existe on-premises."], c: [1],
      e: "Escalabilidade é poder crescer para suportar mais carga; elasticidade é o ajuste automático (subir e descer) acompanhando a demanda em tempo real." },
    { id: "clf-c18", d: "conceitos", q: "O que significa 'tolerância a falhas' (fault tolerance) em uma arquitetura?",
      o: ["A aplicação para completamente quando há uma falha.", "A aplicação continua operando mesmo com a falha de um ou mais componentes.", "Os dados são apagados em caso de falha.", "A aplicação roda em uma única instância."], c: [1],
      e: "Tolerância a falhas é a capacidade de continuar operando sem interrupção mesmo quando componentes falham, geralmente por redundância." },
    { id: "clf-c19", d: "conceitos", q: "Uma empresa quer mover uma aplicação para a AWS com o mínimo de alterações, apenas 'levantando e mudando'. Qual estratégia de migração descreve isso?",
      o: ["Refactor (refatorar)", "Rehost (lift-and-shift)", "Retire (aposentar)", "Repurchase (recomprar)"], c: [1],
      e: "Rehost ('lift-and-shift') move a aplicação como está, sem mudanças no código — a estratégia mais rápida das '7 Rs' de migração." },
    { id: "clf-c20", d: "conceitos", q: "Na estratégia de migração, trocar uma aplicação atual por um produto SaaS (ex.: trocar um CRM próprio por um SaaS) é chamada de:",
      o: ["Rehost", "Repurchase", "Retain", "Replatform"], c: [1],
      e: "Repurchase é substituir o sistema atual por uma solução diferente, normalmente SaaS (ex.: migrar para um CRM como serviço)." },
    { id: "clf-c21", d: "conceitos", q: "Qual benefício da nuvem é refletido pela capacidade de experimentar ideias rapidamente e descartar o que não funciona com baixo custo?",
      o: ["Agilidade", "Durabilidade", "Conformidade", "Criptografia"], c: [0],
      e: "A agilidade permite provisionar recursos em minutos para testar ideias e, se não derem certo, encerrá-las sem grande perda financeira." },
    { id: "clf-c22", d: "conceitos", q: "Por que a AWS consegue oferecer preços mais baixos conforme cresce?",
      o: ["Porque cobra taxas ocultas.", "Por causa das economias de escala — mais clientes diluem os custos.", "Porque reduz a qualidade do serviço.", "Porque elimina a segurança."], c: [1],
      e: "Com milhões de clientes, a AWS alcança economias de escala massivas e repassa parte dessa eficiência em forma de preços menores." },
    { id: "clf-c23", d: "conceitos", q: "Qual serviço da AWS permite executar serviços da AWS na infraestrutura local do cliente (on-premises)?",
      o: ["AWS Outposts", "Amazon CloudFront", "AWS Lambda", "Amazon Route 53"], c: [0],
      e: "O AWS Outposts leva infraestrutura e serviços da AWS para o data center do cliente, útil para cargas que exigem baixa latência local ou residência de dados." },
    { id: "clf-c24", d: "conceitos", q: "Qual pilar do Well-Architected Framework está relacionado a executar e monitorar sistemas e melhorar continuamente processos e procedimentos?",
      o: ["Excelência Operacional", "Confiabilidade", "Segurança", "Otimização de Custos"], c: [0],
      e: "A Excelência Operacional foca em executar, monitorar e melhorar continuamente as operações e os processos de suporte." },
    { id: "clf-c25", d: "conceitos", q: "Qual pilar do Well-Architected Framework trata da capacidade de um sistema se recuperar de falhas e atender à demanda?",
      o: ["Confiabilidade", "Eficiência de Desempenho", "Sustentabilidade", "Segurança"], c: [0],
      e: "O pilar de Confiabilidade garante que a carga de trabalho execute corretamente e se recupere rapidamente de falhas de infraestrutura ou serviço." },
    { id: "clf-c26", d: "conceitos", q: "Um princípio de design da nuvem recomenda 'automatizar para facilitar a experimentação arquitetural'. Isso ajuda principalmente a:",
      o: ["Aumentar o trabalho manual.", "Criar, replicar e reverter ambientes com baixo custo e esforço.", "Eliminar a necessidade de monitoramento.", "Impedir mudanças na infraestrutura."], c: [1],
      e: "Automação (ex.: infraestrutura como código) permite recriar ambientes de forma consistente, testar mudanças e reverter facilmente." },
    { id: "clf-c27", d: "conceitos", q: "O que é o conceito de 'descartabilidade' / recursos descartáveis na nuvem?",
      o: ["Apagar dados de clientes regularmente.", "Tratar servidores como recursos temporários que podem ser substituídos em vez de consertados.", "Usar apenas instâncias Spot.", "Nunca fazer backup."], c: [1],
      e: "Em vez de 'cuidar' de servidores como bichos de estimação, você os trata como gado: se um apresenta problema, substitui por um novo automaticamente." },
    { id: "clf-c28", d: "conceitos", q: "Qual é uma vantagem de usar a infraestrutura global da AWS para uma base de usuários mundial?",
      o: ["Reduzir a latência implantando perto dos usuários.", "Eliminar a necessidade de segurança.", "Tornar todos os serviços gratuitos.", "Remover a necessidade de monitoramento."], c: [0],
      e: "Implantar recursos em Regiões e Edge Locations próximas aos usuários reduz a latência e melhora a experiência." },
    { id: "clf-c29", d: "conceitos", q: "Qual ferramenta ajuda a comparar o custo de rodar cargas de trabalho on-premises versus na AWS (custo total de propriedade)?",
      o: ["AWS Pricing Calculator", "Amazon Inspector", "AWS Shield", "Amazon Macie"], c: [0],
      e: "O AWS Pricing Calculator estima custos na AWS e ajuda em análises de TCO, comparando com o ambiente local." },
    { id: "clf-c30", d: "conceitos", q: "A perspectiva de Governança (Governance) do AWS CAF foca principalmente em:",
      o: ["Escrever código de aplicações.", "Gerenciar e medir o negócio para maximizar o valor e minimizar riscos.", "Conectar cabos de rede.", "Criar funções Lambda."], c: [1],
      e: "A perspectiva de Governança ajuda a orquestrar iniciativas de nuvem, gerenciando riscos, conformidade e maximizando valor de negócio." },
    { id: "clf-c31", d: "conceitos", q: "O que melhor descreve a 'durabilidade' no contexto de armazenamento na nuvem?",
      o: ["A velocidade de leitura dos dados.", "A probabilidade de os dados não serem perdidos ao longo do tempo.", "O custo do armazenamento.", "A região onde os dados ficam."], c: [1],
      e: "Durabilidade indica a proteção contra perda de dados ao longo do tempo (ex.: o S3 oferece 99,999999999% de durabilidade — 11 noves)." },
    { id: "clf-c32", d: "conceitos", q: "Qual conceito descreve a separação de componentes de uma aplicação para que a falha de um não derrube os outros?",
      o: ["Acoplamento forte (tight coupling).", "Acoplamento fraco (loose coupling).", "Monolito.", "Escalonamento vertical."], c: [1],
      e: "O acoplamento fraco isola componentes (ex.: via filas SQS), de modo que a falha de um não se propague para o sistema inteiro." },
    { id: "clf-c33", d: "conceitos", q: "Uma empresa precisa de baixíssima latência para uma aplicação em uma área metropolitana específica, mais perto que a Região mais próxima. Qual recurso da infraestrutura AWS ajuda?",
      o: ["AWS Local Zones", "Amazon S3", "AWS IAM", "Amazon SNS"], c: [0],
      e: "As AWS Local Zones colocam computação e armazenamento mais perto de grandes centros populacionais, reduzindo a latência para aplicações sensíveis." },
    { id: "clf-c34", d: "conceitos", q: "Qual é o principal benefício de usar serviços gerenciados (managed services) da AWS, como o Amazon RDS, em vez de gerenciar tudo manualmente?",
      o: ["A AWS assume tarefas operacionais como patches e backups, reduzindo o esforço do cliente.", "Eliminam totalmente o custo.", "Removem a necessidade de qualquer configuração.", "Garantem que nada nunca falhará."], c: [0],
      e: "Serviços gerenciados transferem o trabalho pesado indiferenciado (patches, backups, escalonamento) para a AWS, deixando o cliente focar na aplicação." },
    { id: "clf-c35", d: "conceitos", q: "Qual destes NÃO é um dos seis pilares do Well-Architected Framework?",
      o: ["Segurança", "Confiabilidade", "Elasticidade", "Sustentabilidade"], c: [2],
      e: "Elasticidade é uma característica da nuvem, não um pilar. Os pilares são Excelência Operacional, Segurança, Confiabilidade, Eficiência de Desempenho, Otimização de Custos e Sustentabilidade." },
    { id: "clf-c36", d: "conceitos", q: "Por que projetar para falhas (design for failure) é recomendado na nuvem?",
      o: ["Porque falhas nunca acontecem na nuvem.", "Porque qualquer componente pode falhar; planejar isso aumenta a resiliência.", "Para aumentar os custos propositalmente.", "Para evitar usar várias AZs."], c: [1],
      e: "Assumir que componentes vão falhar e projetar redundância e recuperação automática torna a arquitetura resiliente." },
    { id: "clf-c37", d: "conceitos", q: "O AWS Cloud Adoption Framework (CAF) é usado principalmente para:",
      o: ["Calcular a fatura mensal.", "Orientar organizações na jornada de adoção e transformação na nuvem.", "Monitorar tráfego de rede.", "Criar instâncias EC2."], c: [1],
      e: "O CAF oferece orientação e melhores práticas para planejar e executar a adoção da nuvem em toda a organização." },
    { id: "clf-c38", d: "conceitos", q: "Qual benefício é alcançado ao parar de gastar dinheiro mantendo e operando data centers físicos?",
      o: ["Focar nos clientes em vez de em racks e energia.", "Eliminar a necessidade de software.", "Garantir disponibilidade de 100%.", "Remover a responsabilidade de segurança do cliente."], c: [0],
      e: "Sem data centers para operar, a empresa investe esforço no que diferencia o negócio e nos clientes, não em infraestrutura física." },
    { id: "clf-c39", d: "conceitos", q: "Uma empresa quer migrar e, ao mesmo tempo, fazer pequenas otimizações (ex.: trocar um banco autogerenciado pelo Amazon RDS) sem reescrever a aplicação. Qual estratégia?",
      o: ["Rehost", "Replatform (lift-tinker-and-shift)", "Retire", "Retain"], c: [1],
      e: "Replatform mantém a arquitetura central, mas faz otimizações pontuais na nuvem, como adotar um serviço gerenciado." },
    { id: "clf-c40", d: "conceitos", q: "O que é o AWS Marketplace?",
      o: ["Um catálogo digital para encontrar, comprar e implantar software de terceiros que roda na AWS.", "Uma ferramenta de faturamento.", "Um serviço de banco de dados.", "Um painel de monitoramento."], c: [0],
      e: "O AWS Marketplace é uma loja de software de terceiros (AMIs, SaaS, contêineres) que você pode assinar e implantar rapidamente, com cobrança integrada à conta AWS." },
    { id: "clf-c41", d: "conceitos", q: "Qual afirmação sobre a nuvem AWS está correta em relação a escalar recursos?",
      o: ["É preciso comprar hardware antecipadamente.", "Você pode aumentar ou reduzir a capacidade sob demanda em minutos.", "Mudanças de capacidade levam semanas.", "Só é possível escalar para cima, nunca para baixo."], c: [1],
      e: "A nuvem permite ajustar a capacidade rapidamente, para cima ou para baixo, conforme a necessidade do momento." },
    { id: "clf-c42", d: "conceitos", q: "Em qual situação um modelo de implantação 100% on-premises ainda pode ser exigido?",
      o: ["Quando há requisitos regulatórios ou de latência que obrigam manter dados/processos no local.", "Quando a empresa quer pagar menos sempre.", "Quando precisa de escalabilidade automática.", "Quando quer alcance global imediato."], c: [0],
      e: "Algumas cargas precisam ficar on-premises por exigências legais, de residência de dados ou de latência muito baixa com sistemas locais." },
    { id: "clf-c43", d: "conceitos", q: "O que é o conceito de 'infraestrutura como código' (IaC)?",
      o: ["Escrever a infraestrutura à mão no console toda vez.", "Definir e provisionar recursos por meio de arquivos de configuração/templates versionáveis.", "Um tipo de instância EC2.", "Um plano de suporte."], c: [1],
      e: "IaC descreve a infraestrutura em arquivos (ex.: AWS CloudFormation), permitindo criar, versionar e reproduzir ambientes de forma automática e consistente." },
    { id: "clf-c44", d: "conceitos", q: "Qual recurso é considerado parte da infraestrutura global da AWS?",
      o: ["Regiões, Zonas de Disponibilidade e Edge Locations.", "Apenas o console web.", "Somente o IAM.", "Apenas instâncias EC2."], c: [0],
      e: "A infraestrutura global inclui Regiões, Zonas de Disponibilidade, Edge Locations e recursos como Local Zones e Outposts." },
    { id: "clf-c45", d: "conceitos", q: "Uma vantagem de usar várias Regiões da AWS é:",
      o: ["Reduzir latência para usuários globais e atender a requisitos de residência de dados.", "Eliminar custos de transferência.", "Tornar o IAM desnecessário.", "Garantir que nunca haverá falhas."], c: [0],
      e: "Distribuir cargas por Regiões aproxima os serviços dos usuários e ajuda a cumprir leis de localidade dos dados, além de aumentar a resiliência." },
    { id: "clf-c46", d: "conceitos", q: "Qual perspectiva do CAF está associada à execução, monitoramento e suporte de cargas de trabalho na nuvem no dia a dia?",
      o: ["Operações (Operations)", "Negócios (Business)", "Pessoas (People)", "Plataforma (Platform)"], c: [0],
      e: "A perspectiva de Operações cuida de executar, monitorar, recuperar e melhorar continuamente as cargas de trabalho na nuvem." },
    { id: "clf-c47", d: "conceitos", q: "O que caracteriza uma arquitetura 'serverless' do ponto de vista do cliente?",
      o: ["Não há servidores envolvidos em lugar nenhum.", "O cliente não gerencia servidores; a AWS provisiona e escala automaticamente.", "É sempre mais cara.", "Exige reservar instâncias antecipadamente."], c: [1],
      e: "Serverless (ex.: AWS Lambda) significa que o cliente não administra servidores — eles existem, mas são totalmente gerenciados e escalados pela AWS." },
    { id: "clf-c48", d: "conceitos", q: "Qual é um benefício de usar Auto Scaling em uma aplicação?",
      o: ["Garantir que a capacidade acompanhe a demanda automaticamente, otimizando custo e desempenho.", "Impedir qualquer mudança de capacidade.", "Eliminar a necessidade de balanceadores de carga.", "Desligar a aplicação à noite obrigatoriamente."], c: [0],
      e: "O Auto Scaling adiciona ou remove instâncias conforme a demanda, mantendo desempenho nos picos e economizando nos vales." },
    { id: "clf-c49", d: "conceitos", q: "Qual afirmação descreve corretamente 'alta disponibilidade' versus 'tolerância a falhas'?",
      o: ["São idênticas.", "Alta disponibilidade minimiza o tempo de inatividade; tolerância a falhas busca operação contínua mesmo com componentes falhando.", "Tolerância a falhas só vale para redes.", "Alta disponibilidade impede qualquer falha."], c: [1],
      e: "Alta disponibilidade reduz ao máximo a indisponibilidade (recupera rápido); tolerância a falhas mantém a operação sem interrupção apesar de falhas, com redundância." },
    { id: "clf-c50", d: "conceitos", q: "Qual destes é um exemplo de 'trabalho pesado indiferenciado' (undifferentiated heavy lifting) que a nuvem ajuda a eliminar?",
      o: ["Definir a estratégia de produto.", "Comprar, instalar e manter servidores físicos e refrigeração.", "Atender clientes.", "Desenvolver funcionalidades exclusivas."], c: [1],
      e: "Tarefas como adquirir hardware, energia e refrigeração não diferenciam o negócio; a AWS assume isso para o cliente focar no que agrega valor." },
    { id: "clf-c51", d: "conceitos", q: "A perspectiva de Plataforma (Platform) do AWS CAF foca principalmente em:",
      o: ["Construir uma plataforma de nuvem escalável e moderna (arquitetura, dados, provisionamento).", "Negociar contratos comerciais.", "Treinar a liderança.", "Definir orçamentos."], c: [0],
      e: "A perspectiva de Plataforma trata de projetar e construir a plataforma de nuvem, incluindo arquitetura, engenharia de plataforma e dados." },
    { id: "clf-c52", d: "conceitos", q: "O que é o AWS Well-Architected Tool?",
      o: ["Uma ferramenta gratuita que avalia cargas de trabalho contra os pilares e aponta melhorias.", "Um serviço de banco de dados.", "Um plano de suporte pago.", "Um tipo de instância."], c: [0],
      e: "A Well-Architected Tool ajuda a revisar arquiteturas, medir contra as melhores práticas dos pilares e identificar pontos de melhoria." },
    { id: "clf-c53", d: "conceitos", q: "Por que a nuvem favorece a inovação em comparação com data centers tradicionais?",
      o: ["Porque exige compra de hardware antes de testar.", "Porque permite provisionar recursos rapidamente para testar e errar barato.", "Porque proíbe experimentos.", "Porque elimina a necessidade de equipes."], c: [1],
      e: "A agilidade da nuvem reduz drasticamente o custo e o tempo de experimentação, acelerando a inovação." },
    { id: "clf-c54", d: "conceitos", q: "Qual é uma característica de um data center tradicional comparado à nuvem?",
      o: ["Capacidade praticamente ilimitada sob demanda.", "Alto investimento inicial (CapEx) e capacidade fixa.", "Pagamento apenas pelo uso.", "Provisionamento em minutos."], c: [1],
      e: "Data centers tradicionais exigem grande investimento antecipado e têm capacidade fixa, o oposto do modelo elástico e sob demanda da nuvem." },
    { id: "clf-c55", d: "conceitos", q: "Uma empresa quer aposentar sistemas legados que não são mais necessários durante a migração. Qual estratégia das '7 Rs' descreve isso?",
      o: ["Retain", "Retire", "Rehost", "Refactor"], c: [1],
      e: "Retire significa desativar/aposentar aplicações que não são mais úteis, reduzindo custo e superfície de gerenciamento." },
    { id: "clf-c56", d: "conceitos", q: "Qual é o objetivo principal do pilar de Sustentabilidade ao escolher Regiões e dimensionar recursos?",
      o: ["Maximizar o consumo de energia.", "Reduzir o impacto ambiental, usando recursos de forma eficiente.", "Aumentar a latência.", "Eliminar a redundância."], c: [1],
      e: "Sustentabilidade busca minimizar o impacto ambiental, por exemplo escolhendo Regiões com energia mais limpa e ajustando o tamanho dos recursos." },
    { id: "clf-c57", d: "conceitos", q: "O que significa 'pagar conforme o uso' (pay-as-you-go) na AWS?",
      o: ["Pagar uma assinatura fixa anual independentemente do uso.", "Pagar apenas pelos recursos que consome, quando consome.", "Pagar somente se a aplicação falhar.", "Pagar adiantado por 3 anos sempre."], c: [1],
      e: "Pay-as-you-go significa pagar pelo consumo real, sem contratos longos obrigatórios nem grandes investimentos antecipados." },
    { id: "clf-c58", d: "conceitos", q: "Qual recurso aproxima conteúdo de jogos/streaming com altíssima exigência de latência de dispositivos 5G?",
      o: ["AWS Wavelength", "Amazon S3 Glacier", "AWS IAM", "Amazon Athena"], c: [0],
      e: "O AWS Wavelength coloca computação na borda das redes 5G das operadoras, reduzindo latência para aplicações móveis exigentes." },
    { id: "clf-c59", d: "conceitos", q: "Qual o papel de um Load Balancer (balanceador de carga) em uma arquitetura de alta disponibilidade?",
      o: ["Criptografar dados em repouso.", "Distribuir o tráfego entre vários alvos/instâncias, inclusive em várias AZs.", "Armazenar objetos.", "Auditar chamadas de API."], c: [1],
      e: "O balanceador distribui as requisições entre instâncias saudáveis (em uma ou mais AZs), aumentando disponibilidade e desempenho." },
    { id: "clf-c60", d: "conceitos", q: "Qual destes é um benefício direto da automação na nuvem?",
      o: ["Maior chance de erro humano.", "Implantações consistentes e repetíveis com menos erros manuais.", "Impossibilidade de reverter mudanças.", "Necessidade de mais hardware físico."], c: [1],
      e: "Automatizar provisionamento e implantações reduz erros manuais e garante ambientes consistentes e reproduzíveis." },

    // ---------- COBRANÇA, PREÇOS E SUPORTE ----------
    { id: "clf-b01", d: "cobranca", q: "Qual modelo de preço do EC2 oferece o MAIOR desconto, mas as instâncias podem ser encerradas pela AWS com pouco aviso?",
      o: ["Sob Demanda", "Reservadas", "Spot", "Dedicated Hosts"], c: [2],
      e: "As Spot Instances usam capacidade ociosa com desconto de até 90%, mas podem ser recuperadas pela AWS com aviso curto — ideais para cargas tolerantes a interrupção." },
    { id: "clf-b02", d: "cobranca", q: "Uma carga de trabalho estável roda 24/7 o ano inteiro. Qual opção reduz mais o custo com compromisso de 1 ou 3 anos?",
      o: ["Instâncias Sob Demanda", "Reserved Instances ou Savings Plans", "Spot Instances", "Pagamento por hora sem compromisso"], c: [1],
      e: "Para uso contínuo e previsível, Reserved Instances ou Savings Plans dão grandes descontos em troca de um compromisso de 1 ou 3 anos." },
    { id: "clf-b03", d: "cobranca", q: "O que são os Savings Plans?",
      o: ["Um plano de suporte premium.", "Um modelo de preço com desconto em troca de um compromisso de gasto por hora (USD/h) por 1 ou 3 anos.", "Um serviço de backup.", "Um relatório de custos."], c: [1],
      e: "Savings Plans dão desconto sobre computação (EC2, Fargate, Lambda) em troca de um compromisso de um valor fixo por hora durante 1 ou 3 anos." },
    { id: "clf-b04", d: "cobranca", q: "Qual ferramenta permite VISUALIZAR e ANALISAR seus custos e uso ao longo do tempo, com gráficos e filtros?",
      o: ["AWS Cost Explorer", "AWS Pricing Calculator", "Amazon Inspector", "AWS Shield"], c: [0],
      e: "O Cost Explorer mostra e analisa o histórico de custos e uso, ajudando a identificar tendências. O Pricing Calculator estima custos futuros." },
    { id: "clf-b05", d: "cobranca", q: "Qual plano de suporte da AWS é gratuito para todos os clientes?",
      o: ["Developer", "Business", "Basic", "Enterprise"], c: [2],
      e: "O plano Basic é gratuito e inclui documentação, fóruns, Personal Health Dashboard e algumas checagens do Trusted Advisor." },
    { id: "clf-b06", d: "cobranca", q: "Qual plano de suporte é o MÍNIMO que oferece um Technical Account Manager (TAM) dedicado?",
      o: ["Business", "Developer", "Enterprise", "Basic"], c: [2],
      e: "O TAM dedicado está disponível no plano Enterprise (o Enterprise On-Ramp oferece um TAM em pool). Business não inclui TAM dedicado." },
    { id: "clf-b07", d: "cobranca", q: "Qual recurso da AWS permite agrupar várias contas e receber uma única fatura, com possíveis descontos por volume?",
      o: ["Cobrança consolidada (Consolidated Billing) via AWS Organizations", "AWS IAM", "Amazon CloudWatch", "AWS Config"], c: [0],
      e: "Com o AWS Organizations e a cobrança consolidada, várias contas pagam por uma fatura única e podem se beneficiar de descontos por uso agregado." },
    { id: "clf-b08", d: "cobranca", q: "O que o AWS Free Tier (nível gratuito) inclui?",
      o: ["Apenas serviços pagos.", "Ofertas 'sempre gratuitas', gratuitas por 12 meses e testes de curto prazo.", "Suporte Enterprise grátis.", "Hardware físico gratuito."], c: [1],
      e: "O Free Tier tem três tipos: sempre gratuito (ex.: limites do Lambda), 12 meses gratuitos (ex.: certo uso de EC2/S3) e trials de curto prazo." },
    { id: "clf-b09", d: "cobranca", q: "Uma empresa quer definir um limite de gasto mensal e ser avisada por e-mail quando se aproximar dele. Qual serviço usar?",
      o: ["AWS Budgets", "AWS CloudTrail", "Amazon Inspector", "AWS Artifact"], c: [0],
      e: "O AWS Budgets permite criar orçamentos de custo/uso e disparar alertas quando os valores se aproximam ou ultrapassam o limite." },
    { id: "clf-b10", d: "cobranca", q: "Qual ferramenta fornece o relatório mais DETALHADO de custos e uso, no nível de cada recurso e hora?",
      o: ["AWS Cost and Usage Report (CUR)", "AWS Pricing Calculator", "AWS Trusted Advisor", "Amazon Macie"], c: [0],
      e: "O Cost and Usage Report (CUR) é o conjunto de dados de cobrança mais granular, detalhando uso por recurso e período, exportável para análise." },
    { id: "clf-b11", d: "cobranca", q: "Qual princípio fundamental de preço da AWS está correto?",
      o: ["Pague mais quanto mais usar.", "Pague conforme o uso, pague menos ao reservar e pague menos quanto mais usar (volume).", "Preço fixo independentemente do uso.", "Só há um modelo de preço para tudo."], c: [1],
      e: "Os fundamentos de preço da AWS: pague conforme usa, pague menos ao se comprometer (reservas/Savings Plans) e pague menos por volume (descontos por maior uso)." },
    { id: "clf-b12", d: "cobranca", q: "Qual plano de suporte oferece tempo de resposta de menos de 1 hora para sistemas de produção INDISPONÍVEIS (business-critical)?",
      o: ["Basic", "Developer", "Enterprise", "Nenhum oferece"], c: [2],
      e: "O plano Enterprise oferece resposta em até 15 minutos para casos críticos de negócio (business/mission-critical). Business responde em até 1h para produção fora do ar." },
    { id: "clf-b13", d: "cobranca", q: "Uma startup quer suporte técnico por e-mail durante o horário comercial enquanto testa na AWS, com o menor custo possível. Qual plano?",
      o: ["Developer", "Enterprise", "Business", "Basic"], c: [0],
      e: "O plano Developer oferece suporte técnico por e-mail em horário comercial a baixo custo, adequado para ambientes de teste/desenvolvimento." },
    { id: "clf-b14", d: "cobranca", q: "O que são Cost Allocation Tags (tags de alocação de custos)?",
      o: ["Etiquetas físicas nos servidores.", "Rótulos aplicados a recursos para organizar e rastrear custos por projeto, equipe ou ambiente.", "Um tipo de instância EC2.", "Chaves de criptografia."], c: [1],
      e: "Tags de alocação de custos marcam recursos (ex.: Projeto=X) para que a fatura possa ser segmentada e analisada por categoria." },
    { id: "clf-b15", d: "cobranca", q: "Qual serviço/recurso recomenda otimizações de custo, como identificar instâncias EC2 ociosas?",
      o: ["AWS Trusted Advisor", "AWS CloudTrail", "Amazon GuardDuty", "AWS WAF"], c: [0],
      e: "O Trusted Advisor faz checagens em várias categorias, incluindo otimização de custos (ex.: recursos subutilizados ou ociosos)." },
    { id: "clf-b16", d: "cobranca", q: "Qual modelo de precificação NÃO exige compromisso de prazo e cobra por hora/segundo conforme o uso?",
      o: ["Reserved Instances", "Savings Plans", "On-Demand (Sob Demanda)", "Dedicated Hosts reservados"], c: [2],
      e: "On-Demand cobra pelo uso sem compromisso de prazo, ideal para cargas imprevisíveis ou de curta duração." },
    { id: "clf-b17", d: "cobranca", q: "Para cargas que precisam de hardware físico dedicado para atender a requisitos de licenciamento por núcleo/soquete, qual opção é indicada?",
      o: ["Spot Instances", "Dedicated Hosts", "On-Demand compartilhado", "Lambda"], c: [1],
      e: "Dedicated Hosts fornecem um servidor físico inteiro dedicado, útil para licenças que exigem visibilidade de soquetes/núcleos (BYOL)." },
    { id: "clf-b18", d: "cobranca", q: "Qual afirmação sobre custos de transferência de dados na AWS geralmente é verdadeira?",
      o: ["Todo tráfego é sempre gratuito.", "Dados que ENTRAM (inbound) geralmente são gratuitos; dados que SAEM (outbound) para a internet costumam ser cobrados.", "Apenas a entrada é cobrada.", "Transferência dentro da mesma AZ é sempre cara."], c: [1],
      e: "Em geral, a entrada de dados é gratuita e a saída para a internet é cobrada; transferências entre Regiões/AZs também podem ter custo." },
    { id: "clf-b19", d: "cobranca", q: "Qual recurso permite que a conta de gerenciamento de uma organização compartilhe descontos de Savings Plans e Reserved Instances entre as contas-membro?",
      o: ["Cobrança consolidada no AWS Organizations", "AWS IAM Identity Center", "Amazon CloudFront", "AWS Config"], c: [0],
      e: "Com a cobrança consolidada, benefícios de RIs e Savings Plans não usados por uma conta podem ser aplicados a outras contas da organização." },
    { id: "clf-b20", d: "cobranca", q: "Onde um cliente acessa relatórios de conformidade da AWS (ex.: SOC, ISO, PCI) sob demanda?",
      o: ["AWS Artifact", "AWS Budgets", "Amazon Inspector", "AWS Cost Explorer"], c: [0],
      e: "O AWS Artifact é o portal de download de relatórios de conformidade e acordos da AWS, sem custo." },
    { id: "clf-b21", d: "cobranca", q: "Qual benefício adicional o plano Enterprise On-Ramp oferece em relação ao Business?",
      o: ["Nenhuma diferença.", "Acesso a um pool de Technical Account Managers e tempos de resposta mais rápidos para casos críticos.", "Remove o suporte técnico.", "Torna o serviço gratuito."], c: [1],
      e: "O Enterprise On-Ramp adiciona um pool de TAMs, revisões e tempos de resposta melhores (15 min para business-critical) por um custo menor que o Enterprise pleno." },
    { id: "clf-b22", d: "cobranca", q: "Uma empresa quer estimar o custo mensal de uma arquitetura com EC2, S3 e RDS antes de criar os recursos. Qual ferramenta usar?",
      o: ["AWS Pricing Calculator", "AWS Cost Explorer", "AWS Cost and Usage Report", "Amazon CloudWatch"], c: [0],
      e: "O AWS Pricing Calculator monta estimativas de custo combinando vários serviços antes do provisionamento." },
    { id: "clf-b23", d: "cobranca", q: "Qual é a vantagem de usar o Compute Savings Plan em comparação com Reserved Instances de EC2?",
      o: ["É mais caro.", "Oferece flexibilidade para aplicar o desconto a EC2, Fargate e Lambda em qualquer Região/família.", "Funciona só com uma instância específica.", "Não dá descontos."], c: [1],
      e: "O Compute Savings Plan é o mais flexível: o desconto vale para EC2 (qualquer família/Região), Fargate e Lambda, conforme o compromisso de gasto." },
    { id: "clf-b24", d: "cobranca", q: "Qual painel ajuda a visualizar a fatura atual e os serviços que mais geram custo no mês corrente?",
      o: ["AWS Billing and Cost Management Console", "Amazon Inspector", "AWS Shield", "AWS Config"], c: [0],
      e: "O console de Billing and Cost Management mostra a fatura atual, detalhamento por serviço e ferramentas de gestão de custos." },
    { id: "clf-b25", d: "cobranca", q: "Para uma carga de trabalho de processamento em lote que pode ser interrompida e reiniciada, qual modelo de preço minimiza o custo?",
      o: ["Spot Instances", "Reserved Instances", "On-Demand", "Dedicated Hosts"], c: [0],
      e: "Cargas em lote tolerantes a interrupção aproveitam o desconto das Spot Instances, com economia de até 90%." },
    { id: "clf-b26", d: "cobranca", q: "Qual recurso ajuda a receber recomendações proativas e checagens em segurança, custos, desempenho, tolerância a falhas e limites de serviço?",
      o: ["AWS Trusted Advisor", "AWS CloudTrail", "AWS Artifact", "Amazon Macie"], c: [0],
      e: "O Trusted Advisor avalia a conta em cinco categorias: otimização de custos, desempenho, segurança, tolerância a falhas e limites de serviço." },
    { id: "clf-b27", d: "cobranca", q: "Qual plano de suporte é necessário para ter acesso ao conjunto COMPLETO de checagens do AWS Trusted Advisor?",
      o: ["Basic", "Developer", "Business ou Enterprise", "Nenhum"], c: [2],
      e: "Os planos Business e Enterprise (e Enterprise On-Ramp) liberam o conjunto completo de checagens do Trusted Advisor; o Basic/Developer têm apenas um subconjunto." },
    { id: "clf-b28", d: "cobranca", q: "Qual afirmação sobre o IAM e custos está correta?",
      o: ["O IAM cobra por usuário criado.", "O IAM é gratuito; você paga apenas pelos recursos que os usuários acessam.", "O IAM exige o plano Business.", "O IAM cobra por política anexada."], c: [1],
      e: "O IAM não tem custo próprio — a cobrança vem do uso dos recursos da AWS acessados pelos usuários/funções." },
    { id: "clf-b29", d: "cobranca", q: "Uma empresa precisa prever quanto gastará e ser alertada se o uso de um serviço específico ultrapassar um limite definido. Qual ferramenta atende melhor?",
      o: ["AWS Budgets", "AWS Pricing Calculator", "AWS Artifact", "AWS CloudTrail"], c: [0],
      e: "O AWS Budgets permite orçamentos por custo ou uso com alertas automáticos ao atingir limites previstos." },
    { id: "clf-b30", d: "cobranca", q: "Qual é uma característica do plano de suporte Business da AWS?",
      o: ["Suporte técnico 24x7 por telefone, chat e e-mail, com acesso completo ao Trusted Advisor.", "Nenhum suporte técnico.", "Apenas suporte por fórum.", "TAM dedicado incluído."], c: [0],
      e: "O Business oferece suporte 24x7 (telefone, chat, e-mail) e Trusted Advisor completo, mas o TAM dedicado é exclusivo do Enterprise." },
  ];
  for (let i = 0; i < Q.length; i++) B.push(Q[i]);
})();
